### ISSUE TITLE
Support plus signs in email addresses

### ISSUE THREAD

**Issue by solace** [perak/kitchen-site#100]
`.meteor-kitchen/templates/bootstrap/form_utils.js`'s `isValidEmail` doesn't support plus signs in email addresses. Is it possible to update the regex?

It'll support address formats like username+label@gmail.com.

Thanks

**Comment by perak** [comment]
Fixed! (and will be uploaded in next version v0.9.40)

**Comment by perak** [comment]
Version v0.9.40 is uploaded.
