### ISSUE TITLE
Collection hooks generated twice

### ISSUE THREAD

**Issue by baysao** [perak/kitchen-site#105]
Dear @perak ,
There is the bug related to generate collection hooks twice in version 0.9.39.
Please help me check it.

**Comment by perak** [comment]
@baysao OK, let's do it now before I upload 0.9.40. Let me see...

**Comment by perak** [comment]
Ooops, yes it's a bug. Fixing...

**Comment by perak** [comment]
Fixed. Will upload new version (0.9.40) in ~1 hour

**Comment by baysao** [comment]
thanks @perak for extremely supportive.

**Comment by perak** [comment]
Uploaded v0.9.40
