### ISSUE TITLE
browser back button and nested templates

### ISSUE THREAD

**Issue by Billybobbonnet** [perak/kitchen-site#107]
Hello @perak 

I noticed that when you have nested pages (sub-page), the user can't use the back button of his browser (example here: http://generator-subpages.meteor.com/). I know that it is because the main page redirects to the subpage using iron-router and I have no trouble to make my own back button ( using `history.go(-2);`)

This is a naive question, do you know or have an hint on how to make nested pages with no redirect (i.e. keep the ability for the user to use its browser back button) ?

If you don't, I'll look into it later anyway and share.

**Comment by perak** [comment]
hum.. I didnt't played with that. Maybe inside route controler in parent page should replace url instead redirect...? If you find a good solution, please let me know, I'l implement it.

**Comment by Billybobbonnet** [comment]
damn you're right, the parent page was routing to the main page, not the sub-page. It makes sense. Maybe you should consider in MK to set the path of every menu to the redirected page directly (if there is one) instead of the main one.

I'll close the issue. Thanks again Petar :-)
