### ISSUE TITLE
config packages.mrt

### ISSUE THREAD

**Issue by solace** [perak/kitchen-site#108]
When adding atmosphere packages to the mrt array, I see the error:

`Error executing "mrt". Error executing "mrt". No such file or directory`.

However I've had success adding the package to the `packages.meteor` array with `mrt:package-name`.  What syntax should be used for `mrt`?

**Comment by perak** [comment]
`mrt` member inside `packages` object is not used anymore and will be removed. Please use `packages.meteor`.

**Comment by perak** [comment]
BTW, "mrt" is "meteorite", that is old package manager for meteor (from beta ages). When you list packages in `mrt` array, meteor-kitchen is trying to execute meteorite - but you don't have meteorite and that's why you got that error message.

**Comment by perak** [comment]
P.S. `Error executing "mrt".` is printed twice -that's in case you miss the first occurrence :D :)

**Comment by solace** [comment]
Thanks :)
