### ISSUE TITLE
dataview example with user roles

### ISSUE THREAD

**Issue by lancefb** [perak/kitchen-site#110]
Thank you for MK. Really enjoying it. I want to use the dataview example but add user roles such that an admin can edit and delete customer fields but other users can only toggle the "Active" field in their accounts. The data will be loaded once at startup. What do I need to add to the json file to make this happen? (I have successfully added user accounts but they are not interacting with the data.)

**Comment by perak** [comment]
Lance, you need application with user account system. Maybe to merge
example-admin with example-dataview. Copy collections array from dataview
example and pages array from dataview into public_zone. Let me know how
goes it.

**Comment by lancefb** [comment]
Petar, I'm back and still stuck with this.  Here is what I've done so far: 
https://github.com/lancefb/TestAdmin
I want the admin to be able to add new users and edit the database example, and the normal users to be able to view the database but only modify part of the database (click on and off Active, in this case).
Thanks so much for this.

**Comment by perak** [comment]
Hey dude, I answered (made pull request with comments to your https://github.com/lancefb/TestAdmin repository). Closing this issue here.

**Comment by lancefb** [comment]
Dude!  You're the best!

L.
