### ISSUE TITLE
Collection2: cannot get type in schema with "bool" type

### ISSUE THREAD

**Issue by baysao** [perak/kitchen-site#112]
Dear @perak ,
In collections definition with collection2 support, i cannot get field "type" in schema with "bool" type.

**Comment by perak** [comment]
Hi @baysao 

sorry for late answer. Can you please give me more details / explain better - I don't understand what is the issue.

Thanks!

**Comment by Billybobbonnet** [comment]
I already noticed that. In the `collection.js` file within the `both` folder,  the mandatory `type` schema attribute is missing with boolean values.

**Comment by perak** [comment]
Thank you guys, working on a fix...

**Comment by perak** [comment]
@baysao @Billybobbonnet fixed. Will be included into next version (0.9.43)
