### ISSUE TITLE
Error HTML File Form Select - unexpected space  {{optionIsSelected .userLanguage "FR"}}

### ISSUE THREAD

**Issue by bvinel** [perak/kitchen-site#114]
Error with HTML file generated that contains a <space> after {{optionIsSelected 
Error msg:
client/views/home_private/accounts/accounts.html:743: Expected space
   ... {{optionIsSelected .userLanguage "FR"}}>...
File accounts.html extract:
<select class="form-control" name="userLanguage" data-type="string">
   <option value="FR" {{optionIsSelected .userLanguage "FR"}}>
       French
  </option>
Workaround: remove manually all the spaces.

**Comment by perak** [comment]
@bvinel just reviewing old issues and found this one... is this issue solved?

Correct is: `{{optionIsSelected userLanguage "FR"}}` (you should not remove space - you should remove leading dot in `.userLanguage`), but why is that dot `.` created? How to reproduce this?

**Comment by bvinel** [comment]
Hi Petar

Yes. I got it solved by a developer on Meteor group. Conflict with the name
used for one collection.

Thanks a lot.

Best regards.

Bruno

On Wednesday, 14 October 2015, Petar Korponaić <notifications@github.com>
wrote:

> @bvinel <https://github.com/bvinel> just reviewing old issues and found
> this one... is this issue solved?
>
> Correct is: {{optionIsSelected userLanguage "FR"}} (you should not remove
> space - you should remove leading dot in .userLanguage), but why is that
> dot . created? How to reproduce this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/perak/kitchen-site/issues/114#issuecomment-147987223>.
>


-- 

Bruno Vinel
Phone +44 (0) 7786062490
Email b.vinel@gmail.com
Skype b.vinel - Twitter @bvinel
LinkedIn http a://uk.linkedin.com/in/brunovinel

**Comment by perak** [comment]
OK :+1:

**Comment by perak** [comment]
(and excuse me for too late reply) :(
