### ISSUE TITLE
while using yaml input copy_files not working

### ISSUE THREAD

**Issue by kadirerdogan** [perak/kitchen-site#115]
it gives below error since kitchen looks to the temporary directory that json file generated.

Error copying files: source file not found "/private/var/tmp/js/methods.js".

**Comment by perak** [comment]
Sorry for late answer: yeah, you're right. I will fix it.

**Comment by perak** [comment]
@kadirerdogan fixed. Will be available in v0.9.48 (~August 6th). Now all relative filenames are relative to original input file - not to converted input file.

**Comment by perak** [comment]
fixed now (v0.9.48)
