### ISSUE TITLE
User always redirected back to home_public when app is refreshed. 

### ISSUE THREAD

**Issue by edionmelarosa** [perak/kitchen-site#119]
File: both/router/router.js
Reason:  Meteor.user() is called/used before user collection is available. 
Note: Issue may only exist when user has slow inet connection.

This issue happen inside ensureLogged() function. Meteor.user() returns null value(even user is logged in) before this code block is executed:

Router.ensureLogged = function() {
               console.log(Meteor,user()); // this will return null first.
		if(!Meteor.user()) {
			// user is not logged in - redirect to public home
				this.redirect("/home_public");
			return;
		} else {
			// user is logged in - check role
			if(!routeGranted(this.route.name) ) {
				// user is not in allowedRoles - redirect to private home
				this.redirect("news");
				return;				
			}
			this.next();
		}
	};
Fix: put Meteor.subscribe("current_user_data"); inside waitOn() function like this:
Router.waitOn(function(){ Meteor.subscribe("current_user_data"); });

That ensure the users collection is available before the app will be rendered.

**Comment by perak** [comment]
Thanks! Fixed and wil be uploaded in next version. Until then, you can change this in ~/.meteor-kitchen/templates/code/client_accounts.js (note: any change in these files will be overwritten when you install next version).

**Comment by perak** [comment]
Fixed (v0.9.48)
