### ISSUE TITLE
Custom_Components

### ISSUE THREAD

**Issue by truck0321** [perak/kitchen-site#120]
I was attempting to create a custom_component for a simple chat feature.   I have code in the javascript section that should only be run server side, not on the client.  All of the javascript ends up in the /Client folder so the server side javascript never executes.  Where is the best place to put that code?  In the API,  there is a place for server startup code but I don't see a way to specify javascript that should only be run on the server.  It would also be ideal to package that with the custom_component,  maybe a server side javascript and client javascript area in custom_components?

**Comment by perak** [comment]
Hi, components are only for client side. You can create .js with any content inside and do something like this in your json input file:

```
{
  "copy_files": [
    { " source": "path/to/your/file/relative/to/this/json/input/file", "dest": "SERVER_DIR/your_file.js" }
  ]
}
```

SERVER_DIR is one of possible constants, please see api reference, file_pair for other constants.

that is if you are doing directly from json (without GUI). If you are using kitchen gui, therecis no possibility to do something like that except server_startup_code

**Comment by perak** [comment]
`server_startup_code` will 100% execute server-side only because it is located in /server dir (see meteor docs about "structuring your app"). For code that resides in /server or /client you don't need `if(Meteor.isServer)` or `if(Meteor.isClient)`.

**Comment by truck0321** [comment]
That makes sense and dropping my server side code in the server_startup_code worked perfectly.  Thank you!

**Comment by perak** [comment]
:+1:
