### ISSUE TITLE
storage adapter on gui

### ISSUE THREAD

**Issue by palpinter** [perak/kitchen-site#135]
Hi,

in examples (kitchen-examples/example-upload/example-upload.json) I've found:
"storage_adapters": ["gridfs"]
in collection definition.

Is it supported in gui? I haven't found yet.

Thx

**Comment by perak** [comment]
Hi @palpinter 

You're right - no "storage_adapters" property in GUI. This is a bug - I just checked metadata.json and it simply doesn't have that property listed in collection object.

I already fixed the bug, but fix will be visible in next version (v0.9.49). Unfortunately it will not be available before next week.

Thanks for bug-catch!

**Comment by palpinter** [comment]
Thanks @perak! :) Its not crucial for me at the moment, I use gridfs adapter, and if I understand well this is the default.

BTW, if you need any help, don't hesitate the ask me. :)

And of course I would like to thank you your fantastic product.

**Comment by perak** [comment]
Thanks @palpinter for kind words about "kitchen" and also for your offer to help.
 
Currently, I'm preparing to open "kitchen-cli" source code, and to start brand new "kitchen-gui" (open source of course) project. 

So, everyone willing to contribute is highly welcome!

- kitchen-cli is C++
- kitchen-gui is meteor-kitchen project (it will use "semantic-ui" frontend and I wish if some "bad ass" frontend designer can help here too).

:+1:

**Comment by kadirerdogan** [comment]
:+1:  At last :)

**Comment by palpinter** [comment]
I'm interested in frontend development and localization. So...
I plan a complete materialize template set for my new customer, the fashion, you know... :)

**Comment by perak** [comment]
If you want to create http://materializecss.com/ templates, that's great! Take a look into `~/.meteor-kitchen/templates/ui/bootstrap3/`.

What you need is to create directory `~/.meteor-kitchen/templates/ui/materialize/`, copy all files from `~/.meteor-kitchen/templates/ui/bootstrap3/` and change markup - materialize class names instead bootstrap class names etc.

Then, you'll be able to build any application (including examples) with "materialize" by specifying in your json:
```
{
  "application":  {
    "frontend": "materialize"
    ...
  }
}
```

@kadirerdogan already did it for `semantic-ui` and it will be available in v0.9.49.

If you do it for materialize, that's great - share it with me, I'l add it into "official" distribution and add you to contributors list. :)

**Comment by palpinter** [comment]
OK, thanks for help, I'm on it. :)

**Comment by kadirerdogan** [comment]
@palpinter I can give a hand on materialize template if you need help. I learned a lot while building semantic-ui template.

**Comment by palpinter** [comment]
Thank you very match. Learning for me is best.

**Comment by palpinter** [comment]
Hi @perak,

I've started to implement materialize , and I have got some questions about layout structure, mainly with material's SideNav, which is totally different than bootstrap one.. Where and how can we dicsuss about it? Here or e-mail?

And @kadirerdogan, how can I get your hand on?

thx Sirs

**Comment by perak** [comment]
Let's go into gitter chatroom

**Comment by perak** [comment]
https://gitter.im/perak/kitchen-site

**Comment by kadirerdogan** [comment]
Chatroom is a good idea :) Otherwise i am getting the stick because of chatting :P

**Comment by kadirerdogan** [comment]
@palpinter  Let me give you a brief info

Before v0.9.47 i have created a sidemenu with semantic-ui. To do that i have cloned bootstrap template files and modified mostly layout_content_navbar.html and menu.html files. (and the js files accordingly)

I did not add sidemenu feature to the current semantic-ui template since the current menu definition doesn't let us define some needed paramaters like orientation, position etc. So it's not that easy to add two different types of menus to the templates unless the ui library lets you do that by just changing the menu css style.

What i can advise you is that choose navbar or sidenav as your menu style and concentrate on that initially. When and if @perak adds the needed features to the menu definition it will be possible to add more menu templates :)

We can go into deep at gitter chat or you can contact me from ekadir@metu.edu.tr whenever you like. Meanwhile let me check materialize's sidenav.

**Comment by perak** [comment]
@kadirerdogan @palpinter before I add required features to enable different types of menu, you can define menu component like this:

```
{
  "name": "my_fancy_menu",
  "type": "menu",
  "template": "awesome_menu"
  ...
}
```

With this setup, you can implement `awesome_menu.html` and `awesome_menu.js` and put them into `~/.meteor-kitchen/templates/ui/components/` directory.

This is actually the same thing as providing "type" property to menu - as @kadirerdogan requested earlier (sorry Kadir, I just realized this :) ).

Your `awesome_menu.html` and `awesome_menu.js` can containe anything, but make sure you set correct `id` attributes to menu, menu items etc. more precisely:

- element `id="menu-items"` is menu items container (in bootstrap this is usually `<ul>` element)
- element `id="menu-item-simple"` is menu item without child items (in bootstrap this is usually `<li>` element)
- element `"id="menu-item-collapse"` is menu item that can contain subitems (yeah, name "collapse" is wrong).

This is how bootstrap `menu.html` looks like:

```html
<template name="TEMPLATE_NAME">
	<ul id="menu-items" class="COMPONENT_CLASS">
	</ul>
</template>

<li id="menu-item-simple" class="ITEM_CLASS"><a href="ITEM_LINK"><span id="item-icon" class="ICON_CLASS"></span> <span class="item-title">ITEM_TITLE</span></a></li>

<li id="menu-item-dropdown" class="dropdown ITEM_CLASS">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown"><span id="item-icon" class="ICON_CLASS"></span> <span class="item-title">ITEM_TITLE</span> <b class="caret"></b></a>
	<ul id="menu-items" class="dropdown-menu">
	</ul>
</li>

<li id="menu-item-collapse" class="menu-item-collapse ITEM_CLASS">
	<a href="#ITEM_ID" class="dropdown-toggle" data-toggle="collapse"><span id="item-icon" class="ICON_CLASS"></span> <span class="item-title">ITEM_TITLE</span> <b class="caret"></b></a>
	<div id="ITEM_ID" class="collapse">
		<ul id="menu-items" class="COMPONENT_CLASS">
		</ul>
	</div>
</li>
```

**Comment by perak** [comment]
One more thing: if you implement different types of menu (by using "template" property), take a note that I will not include them into official distribution if we don't have the same thing for all frameworks ("bootstrap", "semantic-ui" and "materialize"). 

This is because we strictly want input.json file to be 1:1 compatible with multiple frameworks (yeah, it still isn't but let's keep into that direction). So if you implement some menu type for "semantic-ui", and I want to build application using "bootstrap", I just want to change "frontend" property in my .json and that's it. We don't want user to get message "template xxx is not found" - that will look buggy.

**Comment by ljack** [comment]
I was just yesterday thinking about the storage adapter issue. It would also be nice to be able to specify transformWrite/transformRead functions as specified in https://github.com/CollectionFS/Meteor-CollectionFS/wiki/Image-Manipulation 

Currently kitchen json is like this; 	
```
{
				"name": "files",
				"type": "file_collection",
				"storage_adapters": [
					"gridfs"
				]
}
```
which generated this js-contents
```
this.Files = new FS.Collection("files", {
	stores: [new FS.Store.GridFS("files")]
});
```
and I need to have it like this ;)
```
this.Files = new FS.Collection("files", {
	stores: [  
          new FS.Store.GridFS("files")
          new FS.Store.FileSystem("thumbs", {
                transformWrite: function(fileObj, readStream, writeStream) {
                // Transform the image into a 10x10px thumbnail
                 gm(readStream, fileObj.name()).resize('10', '10').stream().pipe(writeStream);
        }
      })
]
});
```

**Comment by perak** [comment]
@palpinter @kadirerdogan @ljack Guys, we went too much off topic here, let's move converstions:

Materialize: https://github.com/perak/kitchen-site/issues/138
CollectionFS: https://github.com/perak/kitchen-site/issues/139

**Comment by perak** [comment]
Original issue from this conversation is solved, so... closing this issue.
