### ISSUE TITLE
'input_items' in field definition is missing on gui

### ISSUE THREAD

**Issue by palpinter** [perak/kitchen-site#137]
Hi @perak,

from API:
input_items	array of input_item	Item list for input type "radio" and "select"
is missing on gui.

Thx

**Comment by perak** [comment]
It's there, but not in form, it's in the tree (well, yes, GUI is little bit inconsistent)

![input_items](https://cloud.githubusercontent.com/assets/5630814/9944502/fed8a6d8-5d87-11e5-995b-ae3e99ce9b44.png)

**Comment by palpinter** [comment]
OK, thx.
