### ISSUE TITLE
Error executing "meteorcreate <output_dir>\" on Windows 10

### ISSUE THREAD

**Issue by KoenLav** [perak/kitchen-site#140]
After running:
meteor-kitchen --example-<name> <output_dir> (with <name> = admin (or any of the others) and <output_dir> = test)

meteor-kitchen outputs:
Reading input file...
Executing "meteor create test\"...

Error executing "**meteorcreate** test\".

Node v4.1.1
Meteor v1.2.0.1
Meteor-kitchen v0.9.49

**Comment by perak** [comment]
Hi @KoenLav,

Just tested and works for me (under linux). 

What OS are you using? (I guess you are using Windows because I see "backslash" after folder name).

Do you have any other error messages?

Please try executing meteor create command without "kitchen": `meteor create test\` and let me know what happens. If you cannot create application directly using meteor command, then problem is not in the "kitchen".

**Comment by KoenLav** [comment]
Running Windows 10.

Meteor create test\ works fine.

I noticed a space missing between meteor and create in the error message (could it be a simple typo?).

**Comment by perak** [comment]
Space in error message is bug in formatting error message, but code that executes meteor properly adds space. I'l try it under windows later to see what happens.

**Comment by KoenLav** [comment]
Thanks a lot!

Great project by the way ;)

**Comment by perak** [comment]
#141 possible the same issue

**Comment by KoenLav** [comment]
where.exe is available on my system

**Comment by perak** [comment]
I'l see what I can do later (~2 hours from now)

**Comment by perak** [comment]
@KoenLav I just tried in Windows 7, it works normally. Sorry, I don't have Windows 10 box... it must be some incompatibility with Windows 10.

Anyway, I'm curious about this problem, thinking about how to diagnose... got some idea?

**Comment by perak** [comment]
![kitchen-windows7](https://cloud.githubusercontent.com/assets/5630814/10144266/fc6c1176-661c-11e5-95a6-a42500234c85.png)

**Comment by KoenLav** [comment]
It doesn't seem it should break on that command, as I can execute in directly. 

It might be caused by the specific example configuration file which is passed to meteor?

**Comment by kadirerdogan** [comment]
I have successfully generated dataview and admin examples on a win10 running under virtualbox. Here are the screenshots of the generation process and the running admin application. 

@KoenLav have you tried with a local json file? 

![screen shot 2015-09-29 at 15 52 52](https://cloud.githubusercontent.com/assets/12003295/10164667/7745a294-66c3-11e5-9882-2acf4fd86c23.png)

![screen shot 2015-09-29 at 15 53 21](https://cloud.githubusercontent.com/assets/12003295/10164665/77450c80-66c3-11e5-9b87-a18b26b37e50.png)

![screen shot 2015-09-29 at 15 57 09](https://cloud.githubusercontent.com/assets/12003295/10164666/7745605e-66c3-11e5-800f-eaec69b302eb.png)

**Comment by KoenLav** [comment]
Just tried with a local JSON file for the meteor-kitchen website, no joy.

If I knew the exact command meteor-kitchen was passing to meteor create it might be easier for me to reproduce the issue in meteor (without meteor-kitchen).

Could you provide me with that?

(Or the commands leading up to this point where the error is formulated.)

**Comment by perak** [comment]
@kadirerdogan thank you!
@KoenLav it looks like kitchen works under win10, but let's try to debug your issue. Before executing meteor, kitchen obtains its full path by executing `where meteor`, now, what's the output  if you run that command?

**Comment by perak** [comment]
After obtaining full path to meteor, kitchen executes `full_path_to_meteor create input_file output_directory`

**Comment by kadirerdogan** [comment]
@perak i guess you added ```input_file``` incorrectly :)

**Comment by KoenLav** [comment]
@perak

where meteor output:

C:\Users\myName\AppData\Local\.meteor\meteor
C:\Users\myName\AppData\Local\.meteor\meteor.bat

**Comment by kadirerdogan** [comment]
@KoenLav i guess there is your problem. First of all the output should be a single line so that kitchen can run it correctly.

What you can try quickly is that setting an alias like below for "where.exe" just before running meteor-kitchen
```
doskey where=echo C:\Users\myName\AppData\Local\.meteor\meteor.bat
meteor-kitchen --example-admin test
```

**Comment by KoenLav** [comment]
I thought two lines would make it difficult, thanks for confirming.

I'm currently working, but will get back to you once I've had the chance to test is.

**Comment by perak** [comment]
@kadirerdogan @KoenLav ok we foind what's the issue, thank you. Now, I'll make mereorkitchen to parse output from where.exe and use first line (or... last line...).

**Comment by kadirerdogan** [comment]
Btw another easy way of testing is to move ```C:\Users\myName\AppData\Local\.meteor\meteor``` to another temporary place and run ```meteor-kitchen --example-admin test``` again.

**Comment by perak** [comment]
I don' think moving .meteor\meteor is good idea. Previous answer is good.

**Comment by kadirerdogan** [comment]
i think .meteor\meteor comes from an old version of meteor since i don't have it with my fresh installation of the latest version of meteor. 

Btw i advised to move the file to another temporary place in case that i am wrong :)

**Comment by perak** [comment]
@kadirerdogan you are not wrong. Two paths returned from where.exe causes issue. Adding that correction into 0.9.50. I'll implement search for .bat in returned filenames, if found execute that, if not found execute first path

**Comment by KoenLav** [comment]
I just tried this:

doskey where=echo C:\Users\myName\AppData\Local\.meteor\meteor.bat
doskey where.exe=echo C:\Users\myName\AppData\Local\.meteor\meteor.bat

(replacing myName with my name)
and then run

meteor-kitchen --example-admin test

and it returns the same error.
(also tried meteor instead of meteor.bat in the doskey entry)

So there might be more going on here, not sure, but at least we squashed one bug.

I'll check it out again once 0.9.50 is released.

**Comment by perak** [comment]
@KoenLav I believe 0.9.50 will be released in next 2 hours

**Comment by perak** [comment]
@KoenLav trying to upload latest version, but it looks like meteor got problems with "galaxy":

```
Error deploying application: Service temporarily unavailable. Please try again
later.
```

:(

**Comment by perak** [comment]
@KoenLav I just uploaded 0.9.50. Install meteor-kitchen again and try - it should work now.

**Comment by KoenLav** [comment]
I hoped so, but it isn't working yet (same error message, except with the missing space added now).

What are the next steps for meteor-kitchen?

**Comment by perak** [comment]
OK... now I am watching the code... it's still a bug in 0.9.50 - it executes first path returned by where instead prioritizing the one with .bat extension... I'll patch it later today.

Anyway, do you still got two outputs from `where meteor`? If you temporary rename first file returned (the one without extension) I believe where will return only single one and kitchen will work. However I wish meteor-kitchen to avoid case like this automatically.

**Comment by KoenLav** [comment]
Renaming meteor to meteor.bak fixes the issue (but indeed, it would be nice of Meteor recognized this scenario on its own).

Thanks for helping me troubleshoot this!

**Comment by perak** [comment]
Glad to hear that! But, please stay tuned just a little bit, I'll upload 0.9.51 today and I wish if you can revert renamed file to original and try. Thanks!

**Comment by perak** [comment]
@KoenLav version 0.9.51 is just uploaded, it should work with multiple paths returned from where.exe.

It prioritizes path to meteor with .bat extension, if no path with .bat extension returned then executes first returned path.

Please check does it work correctly when you find some free time.

Thank you! :)

**Comment by KoenLav** [comment]
I tried and got a little bit further now, however I found another issue.

Future attempts to 'mkdir C:\WINDOWS\system32\test'

So for some reason the current working directory isn't passed properly from meteor-kitchen, I think. It might also be an issue with Future though.

**Comment by perak** [comment]
@KoenLav is this issue related with where.exe? You wrote (few messages ago) that renaming meteor to .bak worked (and you didn't have issues with working directory etc). Now, with 0.9.51 which properly chooses corect filename, issue with cwd raises?

**Comment by KoenLav** [comment]
Strange, the issue I mentioned with system32 seems resolved now. Might have been a glitch, or maybe I had to restart before something started working properly.

Anyhow thanks for all your help, I can confirm creating one of the example projects is working now!

**Comment by perak** [comment]
:+1:

**Comment by fjafjan** [comment]
Please please please remove the meteor.bat file, it must cause so many headaches for new users that you cannot use any of hte standard examples.
