### ISSUE TITLE
onAfterAction not set

### ISSUE THREAD

**Issue by belmarca** [perak/kitchen-site#142]
First of all, thanks for the great work.

This:
```javascript
"public_zone": {
	"navbar_class": "navbar-inverse navbar-fixed-top",
	"pages": [
		{
			"name": "login",
			"template": "login",
			"type": "page",
			"controller_after_action": "console.log(\"Login\");"
		},...
```
does not translate into 

```javascript
onAfterAction: function() {
    console.log("Login");
}
```
in the controllers fo both Public and Private pages. This is particularly annoying in the case of the Logout controller, as I want to redirect to the landing page upon logout.

Can't submit a pull request without the code! I can't wait for it to be open sourced =)

**Comment by perak** [comment]
@belmarca Hi, I just fixed it and will be available in v0.9.52

Until then, quick fix is to add `/*AFTER_FUNCTION*/` into `.meteor-kitchen/templates/code/controller_client.js` as shown in screenshot.

![after_action](https://cloud.githubusercontent.com/assets/5630814/10215867/74f15390-6825-11e5-9600-e1c7b23094d0.png)

**Comment by belmarca** [comment]
@perak Thanks for the fix. I can't edit these files though, I don't have access to the CLI.

Are you talking about [this repo](https://github.com/perak/kitchen-templates)?

**Comment by perak** [comment]
@belmarca No, I am talking about "templates" directory where you installed meteor-kitchen. In linux/macos that's `~/.meteor-kitchen/templates/...`, in windows that's dire where you extracted it.

**Comment by belmarca** [comment]
Petar,

As I wrote my comment I fired up terminal and looked for ~/.meteor-kitchen, where I found all of your tempaltes. That's when I deleted my comment. Sorry for the confusion!

Petar Korponaić wrote:

**Comment by perak** [comment]
@belmarca OK, I replied from e-mail inbox, so I didn't saw you deleted comment. :D :+1:

**Comment by perak** [comment]
v0.9.52 is now up and running.
