### ISSUE TITLE
Is it possible to rename form buttons from within the kitchen GUI?

### ISSUE THREAD

**Issue by xauxatz** [perak/kitchen-site#143]
I'd like to rename the "Save" button to "Submit" but don't see a way to do it.
I can override the HTML generated by Kitchen GUI but that doesn't help much.
Am I forced to create a custom component?

**Comment by perak** [comment]
@xauxatz Hi, just added that functionality and will be available in v0.9.52 (I hope I'l uppload it in next 12-24 hours)

**Comment by xauxatz** [comment]
That's what I call good service!!

Thanks...

**Comment by perak** [comment]
:)

You can already add it into your input file, and it will work when I upload latest version:

`submit_button_title`, `cancel_button_title` and `close_button_title`

("close_button_title" is for button in read-only forms)

**Comment by perak** [comment]
v0.9.52 is uploaded now.
