### ISSUE TITLE
Where to specify font size for tables (dataview)

### ISSUE THREAD

**Issue by xauxatz** [perak/kitchen-site#145]
Hi - I don't see any way to easily do this. Any tips?

**Comment by perak** [comment]
@xauxatz 

1. create new file .css or .less in the same place where is your .json, for example `my_styles.less`

2. add following into your .json (inside application object)

```
"copy_files": [
  { "source": " my_styles.less", "dest": "CLIENT_STYLES_DIR/my_styles.less"}
]
```

and write anything into your .less file. (you can see this technique in multiple examples)
