### ISSUE TITLE
Subscription seems not to be auto-inserted

### ISSUE THREAD

**Issue by xauxatz** [perak/kitchen-site#150]
Hi -
I am logging all activities in a collection. From within a client page I need to insert a new activity and write the count of all activities to the console.
I've created a query for the collection as well that I use for this.
However, the subscription is not auto-created in the controller.js file as expected.
Perhaps it is because I am just referring to the query within helper code?

**Comment by perak** [comment]
@xauxatz meteor kitchen will create publication/subscription only if you have query defined in application.queries. Just making search from within helper will not auto-create pub nor sub.

**Comment by xauxatz** [comment]
The query is also defined inside application.queries but it isn't 
created in the client side controller.js...

**Comment by perak** [comment]
@xauxatz kitchen will generate subscription inside controller if you reffer query from page (or any of page's components). If your query inside application.queries is named "foo", then in your page (or any component) set `"query": "foo" `

**Comment by xauxatz** [comment]
I have a collection named "contactPersonSearches" and an associated 
query called "contactPersonSearchesQuery"

Kitchen creates a "contact_person_searches.js" file with a publish of 
"contact_person_searches_query".  (I don't know why the underlines are 
inserted)
The publish returns "ContactPersonSearches.find({},{}) as it should.

Now, within a form that is a component of a page, I specify under 
"Submit code":

                 this.ContactPersonSearches.insert( {
                   companyName: values.company,
                   domainName: values.domain,
                   titles: values.titles,
                   timeStamp: new Date().valueOf()  });

However, in the associated controller, no subscription of the query is 
auto-inserted.

**Comment by perak** [comment]
Do you need to subscribe? (it's insert form). Anyway, you need to specify `"query": "contactPersonSearchesQuery"` kitchen will then generate subscription.

Btw, `createdAt` is automatically set server side in before insert hook, so you maybe don't need timeStamp field. Also, your insert cáe is simple - if you define fields in collection (or in form), code that inserts data into colle tion will be automatically created.

**Comment by perak** [comment]
@xauxatz is this issue resolved? (please close it, or let me know if I can close)

**Comment by xauxatz** [comment]
Yes, fixed... Thanks
