### ISSUE TITLE
Error in auto-generated code

### ISSUE THREAD

**Issue by xauxatz** [perak/kitchen-site#153]
Hi -

I have a form that is linked to a query in the Kitchen GUI (query name): findpersonsquerygetdata.
This gives me the following line in validateForm:

 Findpersonsquery.update({ _id: t.data.findpersonsquerygetdata._id }, { $set: values }, function(e) { if(e) errorAction(e); else submitAction(); });

Now, the app reports an error from the above line occasionally on my local environment. If I then restart the app, the error goes away.
But if I deplay the app on meteor.com (meteor deploy ...), the error is there all the time.

The error is that t.data.findpersonsquerygetdata is undefined which is really strange.

What could be the reason?

**Comment by perak** [comment]
@xauxatz strange. Is controller properly subscribed to that query? (do you have `Meteor.subscribe("findpersonsquerygetdata");` in controller `isReady` function?).

Does your query requires parameters (and maybe those params are not set?). Please show me publish and subscribe code for that query.

**Comment by xauxatz** [comment]
Yes, isReady in the controller has this:
		var subs = [
			Meteor.subscribe("findpersonsquerygetdata")
		];

The data() function has this:
		return {
			params: this.params || {},
			findpersonsquerygetdata: Findpersonsquery.findOne({}, {})
		};

(Could it be due to the "findOne"?)

Here's the publish code:
Meteor.publish("findpersonsquerygetdata", function() {
	return Findpersonsquery.find({}, {});
});

**Comment by perak** [comment]
How this happened? Meteor Kitchen should produce `findOne` both server and client-side (if `"find_one": true` is set in query definition).

Anyway, this code should work. Maybe your `Findpersonsquery` is empty?

**Comment by perak** [comment]
(btw, just an andvice, it would be more readable if you name your collection `find_persons_query` - kitchen will produce `FindPersonsQuery`, especially your query: `findpersonsquerygetdata` is hard-to-read :) )

**Comment by xauxatz** [comment]
Thanks, and I finally figured it out by now.

First time I run the app, the collection for the form is empty. Updating 
it will not work then, since there is no prior data to update.

I had the form set to "insert" at that time. Later I switched to 
"update" for the form and since there was data in the collection, it 
worked well.

Then at a point I reset the mongo database, and of course the collection 
was now empty and updating the form would not work...

**Comment by perak** [comment]
In that case, you need `upsert` form (insert if empty, otherwise update). That is not supported by kitchen (yet). Do you need that? Or... is data in your form fixed? (in that case, you can insert data inside `server.startup` if collection is empty - or insert some default data, that user can modify - and create just update form).

However, is this issue fixed now and can be closed?

**Comment by xauxatz** [comment]
Yes, I think I can manage it on my own without you implementing "upsert" :-)

Thanks, you can close it

**Comment by perak** [comment]
:+1:

**Comment by xauxatz** [comment]
Hi Perak

I could actually well use the "upsert" form option now as my code is 
becoming quite messy, trying to handle this situation.

Thanks.,..




On 14-Oct-15 11:28, Petar Korponaić wrote:
>
> In that case, you need |upsert| form (insert if empty, otherwise 
> update). That is not supported by kitchen (yet). Do you need that? 
> Or... is data in your form fixed? (in that case, you can insert data 
> inside |server.startup| if collection is empty - or insert some 
> default data, that user can modify - and create just update form).
>
> However, is this issue fixed now and can be closed?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/perak/kitchen-site/issues/153#issuecomment-147988735>.
>

-- 
*Claus Skaaning*
Adm. direktør / CEO

*Sales on Tap*
<http://www.sales-on-tap.com> Th. Staunings Vej 48
<http://maps.google.com/maps?q=Th.+Staunings+Vej+48%2CAalborg+DK-9210%2CDenmark&hl=en> 
Aalborg DK-9210 Denmark
		*Mobile:* +45 20690771
*Email:* cs@sales-on-tap.com <mailto:cs@sales-on-tap.com>
*Professional Profile <http://dk.linkedin.com/pub/claus-skaaning/0/53/503>*
