### ISSUE TITLE
LinkedIn login doesn't seem to work

### ISSUE THREAD

**Issue by xauxatz** [perak/kitchen-site#156]
When I checked "Login with LinkedIn" under application and re-deployed, I got "Service Service not configured not configured" when I push the "Sign in with LinkedIn" button...

**Comment by perak** [comment]
@xauxatz 

1. did you deploy with `metoer deploy YOUR_APP_URL --settings path_to_settings.json` and in the settings.json you properly entered linkedin access tokens?

2. does your application url matches the one configured in linked in OAuth settings (at linked in site) ?

**Comment by xauxatz** [comment]
Thanks - that helped a lot. I can now log in with LinkedIn!
My application is reading various person and company pages in LinkedIn:
- www.linkedin.com/in/donaldduck
- www.linkedin.com/company/microsoft

I do this just using http.get but the app is returning empty results, probably because I'm not authenticating the http.get calls correctly in relation to LinkedIn.

I know this is outside the scope of Meteorkitchen but can anyone here provide me with a pointer for where to look to figure out how to authenticate these calls...?

**Comment by perak** [comment]
@xauxatz I don't think it's possible to send http request which authenticates "just like that" (authentication is btw two-way, multi step process).

I didn't play with LinkedIn, but the same as another apps - it should have API which allows retrieving data by sending OAuth public keys or similar.

Try this: https://developer.linkedin.com/docs/rest-api

**Comment by xauxatz** [comment]
Thanks - I will dig further.

I can see that I need an access token to make authenticated calls on 
behalf of a user.

I think the access token should be returned through the login process - 
do you know if it could be this code which is written to the console 
after LinkedIn login:

/_oauth/linkedin?close&code=AQTBveuUR7P0Y-icr9XBv099Y............

**Comment by perak** [comment]
It should be written into users collection, see `Users.findOne({}).services`

**Comment by perak** [comment]
P.S. user.services is not published to client, you need to read that server-side of from mongo shell

**Comment by perak** [comment]
@xauxatz can we close this issue?

BTW did you find OAuth token - if you did, please write here - maybe useful to someone else too).

**Comment by xauxatz** [comment]
Yes, you can close it now.

I found the token. I can see you use the pauli:linkedin package. I put a 
breakpoint in 
.meteor/local/build/programs/server/packages/pauli_linkedin.js and the 
access token is correctly retried from LinkedIn.

user.services.linkedin.accessToken is what I need to proceed.

Thanks again.

**Comment by perak** [comment]
:+1:
