### ISSUE TITLE
Meteor.userId() or this.userId - none of them work

### ISSUE THREAD

**Issue by xauxatz** [perak/kitchen-site#159]
Hi -
I have a query that is defined with this filter:

{
	"ownerID": "this.userId"
}

In the controller, I then get this code:

	data: function() {
		return {
			params: this.params || {},
			find_persons_data_query: FindPersonsSearchCriteria.findOne({ownerID:this.userId}, {})
		};
	},

this.userId is undefined. If I replace it with Meteor.userId() I get an error that I am not allowed to use this in a publish function, such as:

Meteor.publish("find_persons_data_query", function() {
	return FindPersonsSearchCriteria.find({ownerID:Meteor.userId()}, {});
});

How do I resolve this?
How can I get access to the userId within this method?

**Comment by perak** [comment]
You are not the first who ask this. Currently you cannot do this, but you can limit your collection to be readable only to owner (this is good enough in situations where user never need to see other users docs - only own docs).

In json, in your colection set: `"roles_allowed_to_read": ["owner"]`

Functionality as you requested by specifying Meteor.userId() or this.userId will be added into next version, hopefully in next 24-36 hours.

**Comment by perak** [comment]
Limiting documents to "owner" role is shown in multiple examples, eg. "invoices" example

**Comment by perak** [comment]
@xauxatz Ooops - ti's possible!

You need to define param in your query:
```
{
  "name": "my_query",
  "collection": "my_collection",
  "filter": {
    "ownerID": ":theUserId"
  }
}
```

And in place where you are using your query (page, component) : 

```
"query_name": "my_query",
"query_params": [
  { "name": "theUserId", "value": "Meteor.userId()" }
]
```

That's it :)

**Comment by perak** [comment]
Other possibility is to limit collection to be readable only to owner - this is good solution only if user need to see only own documents and never need to see other users documents.

In your collection definition do something like this:
```
{
  "name": "my_collection",
  "roles_allowed_to_read": ["owner"]
}
```
*Note: "owner" is special built-in role*

That's it :)

**Comment by xauxatz** [comment]
I wasn't able to get the below functionality to work. I've searched the 
source code and it did not look like "theUserId" was ever assigned to 
"Meteor.userId()" anywhere...
But the other method pointed out by you (set collection to be readable 
only by owner) worked well - thanks!

**Comment by perak** [comment]
@xauxatz just tested first solution, ant it worked. Parameter `theUserId` is set in controller, in subscription and in data function:

```
...
  isReady: function() {
    var theUserId = Meteor.UserId();

    var subs = [
      Meteor.subscribe("my_query", theUserId)
    ];
    var ready = true;
    _.each(subs, function(sub) {
      if(!sub.ready())
        ready = false;
    });
    return ready;
  },

  data: function() {
    var theUserId = Meteor.UserId();

    return {
      params: this.params || {},
      my_query: MyCollection.find({ownerId: theUserId}, {sort:{createdAt:1}})
    };
    /*DATA_FUNCTION*/
  },
...
```

And server side, publication looks like this:

```
Meteor.publish("my_query", function(theUserId) {
	return MyCollection.find({ownerId: theUserId}, {sort:{createdAt:1}});
});

```

It must be you made some typos or something.

Anyway, second method is even better if security matters - if data owned by user is private and never shared to other users. In first method, any user can open browser console and do `Meteor.subscribe("my_query", ANY_OTHER_USER_ID)` and data will be published from server.
