### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present...

### ISSUE THREAD

**Issue by xauxatz** [perak/kitchen-site#160]
Hi -

My app works well locally. However when I deploy to meteor.com, I sometimes get the error below.
It seems to be an error occurring when moving from one page to another within the app, so should not occur. Any ideas?

GET https://ddp--5508-contacts2.meteor.com/sockjs/info?cb=2aml6711yp y._start @ 41425c64956d3e54099a47c0ff0a50860ded82ed.js?meteor_js_resource=true:41(anonymous function) @ 41425c64956d3e54099a47c0ff0a50860ded82ed.js?meteor_js_resource=true:41
contact_person_results_page:1 XMLHttpRequest cannot load https://ddp--5508-contacts2.meteor.com/sockjs/info?cb=2aml6711yp. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://contacts2.meteor.com' is therefore not allowed access. The response had HTTP status code 503.

**Comment by perak** [comment]
@xauxatz are you doing any ajax (or any other) http requests from controller?

**Comment by xauxatz** [comment]
Yes, but they are all accessed through Meteor.call and running on the 
server side.

**Comment by perak** [comment]
I think this is out of "kitchen" scope - question for http://forums.meteor.com

**Comment by perak** [comment]
I stil think you are somehow doing request from client (not from server). Are you sure request is defined inside /server in Meteor.method ?

**Comment by xauxatz** [comment]
You were most likely right. I wrapped the http.get's in Meteor.isServer 
and the problem went away. At least for now...

**Comment by perak** [comment]
OK. Let's close this issue
