### ISSUE TITLE
DataView - delete button not visible

### ISSUE THREAD

**Issue by cyclops24** [perak/kitchen-site#162]
Hi,

I used meteor-kitchen in 2 project, in both of them delete button not visible on any of my collection. Please give me some instruction or step by step guide to active delete button on my DataView if it needs spacial steps.

Thanks for your attention

**Comment by perak** [comment]
@cyclops24 if you have "insert" in your dataview - then delete button is generated. No insert - no delete. Maybe that's not best solution (it would be better if I add some property like { "delete": true } ...

**Comment by perak** [comment]
(btw, which "frontend" are you using? Currently, only "bootstrap3" (default) is properly generated).

**Comment by cyclops24** [comment]
@perak spacial thanks for your attention. It's the key note that help me find the issue:
"No insert - no delete."
I used one form to create and set submit route to another page with DataView to show the result. I added menu link for insert page and didn't set insert route for my DataView.

I think it's a little confusing (no insert - no delete) and add new property like { "delete": true } would be better approach.

Thanks for your attention man.

**Comment by perak** [comment]
:+1:

**Comment by cyclops24** [comment]
@perak I now check [User Accounts example](http://generator-accounts.meteor.com).
Insert route set for admin/users but delete button not visible.
What do you think?

**Comment by perak** [comment]
@cyclops24 "Users" collection have special treatment by "kitchen", so user list is not a good example. 

BTW, are you dealing with users in your dataviews where you don't have "delete" button?

**Comment by cyclops24** [comment]
I have several collection and based on your help I add insert route and delete button issue fixed now but I also want to add delete button to user list. Because some of users send spam message and other illegal activity.
Is it possible with kitchen?

**Comment by perak** [comment]
My solution was to set user's role to "blocked" - and that user cannot login anymore. I think you cannot delete user from client-side, but you can server-side (in a method). However, this is not implemented by meteor-kitchen.

**Comment by cyclops24** [comment]
@perak  Thanks man. "blocked" roles also good but when too many blocked users available in user list it make user list dirty but worked man :wink:.
Thanks again
