### ISSUE TITLE
trying to internationalize a meteor-kitchen generated app (login, register, ...)

### ISSUE THREAD

**Issue by euqip** [perak/kitchen-site#166]
Hi Perak,

I use the tap:i18n module to translate templates texts.  the module is added to the modules to be loaded, and it works.
When coming to login, register and reset password templates, these are generated by the kitchen, without any possibility to translate.

I tryed to capture the Template.Login.rendered event to change the content, but without success, it was done in the login.js file.

May I suggest to adapt these forms (templates) to include i18n out of the kitchen by changing a little bit the templates.

Example: with login.html, (without tap:i18n module, the rendered form would stay as it is.)
```html
<template name="Login">
	<div class="container">
		<form id="login_form" class="account-form" role="form">
			<h2>
				{{_ "Please sign in"}}
			</h2>
			{{#if errorMessage}}
			<div class="alert alert-warning">
				{{errorMessage}}
			</div>
			{{/if}}
			<div id="login-with-password" style="padding-top: 10px;">
				<input id="login_email" type="text" class="form-control" placeholder="{{_ 'Email address'}}" required autofocus>
				<input id="login_password" type="password" class="form-control" placeholder="{{_ 'Password'}}" required>
				<button class="btn btn-lg btn-primary btn-block" type="submit" data-loading-text="{{_ 'Please wait...'}}">
					{{_ 'Sign in'}}
				</button>
				<p class="account-form-text-after" id="register-link">
					{{_ 'Not a member?'}}
					<a href="{{pathFor 'register'}}">
						{{_ 'Sign up here'}}
					</a>
				</p>
				<p class="account-form-text-after" id="forgot-password-link">
					{{_ 'Forgot password?'}}
					<a href="{{pathFor 'forgot_password'}}">
						{{_ 'Click here'}}
					</a>
				</p>
			</div>
		</form>
	</div>
</template>
```
Not yet found how to handle the error messages!

With same idea, is it possible to add in the 'both' directory, a new empty directory called 'i18n', where tap:i18n is able to collect the translations?

here is a french translation file for this form:
the file is to be called fr.i18n.json, placed in i18n directory, the content is:

```json
{
   "Forgot password?": "Mot de passe oublié?"
    ,"Sign in": "se connecter"
    ,"Not a member?": "pas encore membre?"
    ,"Sign up here": "s'inscrire ici"
    ,"Click here": "cliquer ici"
    ,"Please sign in": "Pour se connecter"
    ,"Email address": "adresse courriel"
    ,"Password": "Mot de passe"
    ,"Please wait...": "Veuillez patienter..."
    ,"modify": "Modifier"
}
```
I know, I can overwrite the existing templates in the building process, by adding these templates to the files to be copied.

Thanks for this pretty tool!
Hope it will help others.

**Comment by perak** [comment]
Hi @euqip 

Meteor-Kitchen screams for multilanguage support, but I'm currently busy with new GUI (will be published soon and will be open source). 

Now, before I integrate what you kindly created and shared with us (thank you!), and before I open the CLI source code (so you and other people can contribute directly), what you can do is little bit more elegant solution than using "copy_files" to manage custom page templates:

You can use page's `custom_template` property - create your `my_login.html` and `my_login.js` files and put them into same directory where is your .json (or in any subdirectory under) and then 

instead this:
```
{
  "name": "login",
  "template": "login"
  ...
} 
```

do this:
```
{
  "name": "login",
  "custom_template": "my_login"
  ...
} 
```

Now, meteor-kitchen will use your templates instead default `login.html` and `login.js`.

BTW, original templates are stored in `~/.meteor-kitchen/templates/ui/bootstrap3/pages/`, and I suggest you to use

Instead this:
```
<template name="Login">
  ...
</template>
```

Do this:
```
<template name="TEMPLATE_NAME">
  ...
</template>
```

In that case your templates will be more reusable - if your page is named "sign_in", your template will be named `<template name="SignIn">` (special string `TEMPLATE_NAME` is replaced with actual template name).

I hope this helps.

Thanks for your contribution, I hope I'll be able to implement / add it into official version soon (but that's not a promise :).

**Comment by euqip** [comment]
Thanks Perak, for quick answer.
I'l try your suggestions.
