### ISSUE TITLE
Dataview auto-generated code blocks clicks

### ISSUE THREAD

**Issue by xauxatz** [perak/kitchen-site#167]
Dataviews seem to auto-generate this code:

	"click td": function(e, t) {
		e.preventDefault();
		/**/
		return false;
	},

This is unfortunate as I have embedded HTML links in the dataview that the user should be able to click on. The above blocks these clicks.

Is there a good workaround?  I don't see any way to handle it in the Kitchen GUI.

**Comment by xauxatz** [comment]
I figured it out, so ignore this one.
I can create an overriding "click td a" in an extra JS file that handles the click on the link. It works perfectly well.

**Comment by perak** [comment]
@xauxatz excuse me for too late answer. Glad you solve it! :+1:
