### ISSUE TITLE
How can we add bootstrap3 templates that are not in bootswatch?

### ISSUE THREAD

**Issue by a4xrbj1** [perak/kitchen-site#170]
I have a bootstrap3 related question, how can we add other templates than the ones as bootswatch into the kitchen?

As I'm missing the Project Polymer cards (see https://elements.polymer-project.org/elements/paper-card?view=demo:demo/index.html&active=paper-card) in the standard bootstrap 3 elements I wanted to include eg this wonderful template: http://demos.creative-tim.com/hipster-as-f-cards

Also, is it possible to add bootstrap4 (not possible but planned in the future)?

**Comment by perak** [comment]
@a4xrbj1 see directory `~/.meteor-kitchen/templates/ui/bootstrap3/themes/`, there each theme is contained in subdirectory. Good example is `flat-ui` which is not from bootswatch. What you need is to create `theme.import.less` file which includes your theme's stylesheets. Meteor Kitchen will copy all files found in your theme directory into your project (fonts and images will be automatically copied into `your_app/public/` etc.).

If your theme directory is named "my_cool_theme", and is located in `~/.meteor-kitchen/templates/ui/bootstrap3/themes/my_cool_theme/` then you can use it in your input .json file by setting: `"theme": "my_cool_theme"` (the same name as your theme directory).

I am not sure is it possible using GUI (btw, current kitchen-GUI is very limited - woring on the new one).

that's it.

**Comment by a4xrbj1** [comment]
Thank you Petar. I'm not so keen to change manually, thought it was possible through the GUI. But your detailed answer shows the steps to achieve it (I guess that includes bootstrap4 through the same method)

**Comment by perak** [comment]
The same method will not help you to add bootstrap4. We need to modify / rewrite component templates (files found in `~/.meteor-kitchen/templates/ui/bootstrap3/` should be modified or rewritten and moved to `~/.meteor-kitchen/templates/ui/bootstrap4/`).

**Comment by a4xrbj1** [comment]
I can only use one theme at a time, right? Like I wrote I have found one free template that has the card elements but I guess it will not have all the other elements the Bootstrap:paper has for example. It would be nice like in Semantic-UI to define a theme per element itself (as long as there is that theme available for that specific element). Is that possible in MK or Bootstrap3?
