### ISSUE TITLE
Materialize: updateTextFields on template rendered

### ISSUE THREAD

**Issue by KoenLav** [perak/kitchen-site#171]
Materialize initializes before the template is completely rendered. After Materialize is initialized the input fields will be populated with data, but the Materialize labels will cover them.

Fix:
Call 'Materialize.updateTextFields();' in the rendered function of every create, update and details template.

However I think this issue might need to be fixed within the Materialize package itself (should probably just call doMaterialize in the rendered callback), your thoughts?

**Comment by perak** [comment]
@KoenLav feel free to add it by yourself in this repository and then pull request: https://github.com/perak/kitchen-templates

**Comment by KoenLav** [comment]
@perak will do.

**Comment by perak** [comment]
:+1:

**Comment by perak** [comment]
@KoenLav by the way: I didn't explained in README.md how to work with templates / how to test:

- fork "kitchen-templates" repo
- install latest version of meteor-kitchen
- remove `~/.meteor-kitchen/templates/` directory
- clone your "kitchen-templates" repository (into `~/.meteor-kitchen`)
- then you'll get `~/.meteor-kitchen/kitchen-templates/` - rename it to `~/.meteor-kitchen/templates/`

When you got something, push the code and gi'me pull request.

**Comment by KoenLav** [comment]
Noted!
