### ISSUE TITLE
Materialize: navbar active should be added on li instead of a

### ISSUE THREAD

**Issue by KoenLav** [perak/kitchen-site#176]
The active class in the navbar should be added on the li element instead of the a element for Materialize.

**Comment by perak** [comment]
@KoenLav thanks! 

Materialize templates are kind and welcome contribution by @kadirerdogan (thanks to him!), and I didn't touch that code. 

If you're willing to help and contribute, I'll prepare repository for you and will try to write some instructions on how to modify "official" kitchen templates. The best I can do is to add you to contributors list in http://www.meteorkitchen.com/contribute page.

Please let me know are you interested. Every help is welcome! Thank you!

**Comment by KoenLav** [comment]
Interested, hit me up ;)

**Comment by perak** [comment]
@KoenLav here we go:

https://github.com/perak/kitchen-templates

I just wrote README.md

Please let me know if I can help.

Thanks!

**Comment by kadirerdogan** [comment]
Good README :+1:

**Comment by perak** [comment]
@kadirerdogan at last I found enough time to make it :) Feel free to update it if you find mising parts.

**Comment by kadirerdogan** [comment]
Both semantic and materialize has some missing parts.

As i remember urgent ones are Datetime picker for semantic and yes/no modal panel of materialize (for delete etc.) not returning the answer. I'll try to fix materialize part since you told me that you are working on semantic already :)

@KoenLav i can give you some hints if you need help about working on the templates. We can use gitter chat for the boring details :)

**Comment by perak** [comment]
@kadirerdogan I'm using semantic for the new kitchen-gui (new gui source and app will be published soon). So, please play only with materialize (or bootstrap).

**Comment by KoenLav** [comment]
@perak thanks!

@kadirerdogan thanks, will let you know if I need any help. Will you be working on the Materialize templates a lot? If so we might want to share a repository.

**Comment by kadirerdogan** [comment]
@KoenLav i am not working on it a lot for now. I'll try to keep up with your pull requests
