### ISSUE TITLE
deployment error on example-admin

### ISSUE THREAD

**Issue by manaty** [perak/kitchen-site#177]
when starting the example-admin app,  i get the following error:

While processing files with less (for target web.browser):
client/styles/styles/styles.less:1: Unknown import: /client/styles/framework/bootstrap3/custom.bootstrap.less

**Comment by perak** [comment]
Hey @manaty this issue is answered multiple times, please search issues (also closed ones).

But, one of users didn't solved it (most recent one), so please see can you solve it and let me know. I got permanent solution but I'll upload it tomorrow (~36 hours from now).

**Comment by manaty** [comment]
Hi @perak  

Sorry for that, i searched but didnt see the the other answers.
I solved it by replacing the import absolute path by a relative one.
