### ISSUE TITLE
Verify email page not created

### ISSUE THREAD

**Issue by xauxatz** [perak/kitchen-site#188]
Hi -

I've checked "send_verification_email" in the application GUI, and the email is also correctly sent.
However, the page "http://contacts3.meteor.com/verify_email/R9amjj8FbUaVQr27aKtf2EIiorkyVehtKGMTFGbXAyg" does not exist.

Also, it seems like the "verify_email" page is not created in the source code.

**Comment by perak** [comment]
Not documented but exists in `example-admin` example, you need to define that page:

```
{ "name": "verify_email", "template": "verify_email", "route_params": ["verifyEmailToken"] }
```

(put it where are your login, register, etc. pages, or see "example-admin").

**Comment by xauxatz** [comment]
Thanks, that works!

**Comment by perak** [comment]
:+1:
