### ISSUE TITLE
Tree-view uses bootbox, is it a package or ?

### ISSUE THREAD

**Issue by euqip** [perak/kitchen-site#190]
Hi Perak,

I tried to implement a treeview with a little collection, in an application derived from the minimal model.
I just added the collection, a query to this collection and a new page containing a treeview component using my query.
The js generated file from CLI uses a reference to bootboxDialog that is not defined.

Is the bootbox a simple package to load in meteor or is the bootboxjs library?  I found only one bootbox package that did'nt work.

Could you please give more info about this?

Thanks

**Comment by perak** [comment]
@euqip bootbox is added automatically only if you have form in your application. That's wrong and I'll change it.

To add bootbox manually:

1. add this package: `mizzao:bootboxjs`

2. maybe you'll need function `/client/lib/form_utils.js` (you'll find this file if you generate `example-dataview` or something using form). Useful function is:

```
bootboxDialog = function(template, data, options) {
	var tmpl = null;
	if(_.isString(template)) {
		tmpl = Template[template];
	} else {
		tmpl = template;
	}
	var div = document.createElement("div");
	Blaze.renderWithData(tmpl, data, div);

	options.message = div;
	bootbox.dialog(options);
};
```

Hope it helps.

**Comment by euqip** [comment]
Hi Perak,

I copied the code here above and it worked better.  After having copied the whole file from dataview sample, it worked even better with creations, deletions ans updates.
I can now look further.

And close this issue as the answer is included

**Comment by perak** [comment]
:+1:
