### ISSUE TITLE
Documentation for pre-defined variables in components custom templates

### ISSUE THREAD

**Issue by ChinoMing** [perak/kitchen-site#198]
Is there any documentation around pre-defined variables that can be used in components custom templates, e.g. TEMPLATE_NAME, COMPONENT_TITLE, QUERY_NAME, etc...

Trying to figure out upload example files (https://github.com/perak/kitchen-examples/blob/master/example-upload/files/gallery.html).

**Comment by perak** [comment]
@ChinoMing 

`TEMPLATE_NAME` can be used in pages and components, and will be replaced with current template name. That allows you to use the same component in multiple pages (you will not have duplicate temlpate names).

`APP_TITLE` application title
`COMPONENT_TITLE` component title
`COMPONENT_TITLE_ICON_CLASS` in some components, if this is set generatro will add icon before component title, for example `fa fa-heart`
`COMPONENT_CLASS` class will be added to main component container
`QUERY_NAME` main query name for this component (as set in `query_name` property). That's the same as publication/subscription name. Variable is set in template's data context in page's controller.
`QUERY_VAR` The same as QUERY_NAME but deprecated - will be removed.
`COLLECTION_VARIABLE` - Component's main collection global variable e.g. if you have `Posts = new Meteor.collection("posts");` defined, this variable will be `Posts`.
`COMPONENT_ID` unique ID for this component (usually used as html `id` attribute).
`PAGE_TITLE` - page title
`PAGE_TITLE_ICON_CLASS` - icon with this css class will be added just before page title
`PAGE_TEXT` - text (or html) will be inserted into page's content area
`FOOTER_TEXT` - text to be added into footer (usually used in layout templates)

**Comment by ChinoMing** [comment]
This is great.  Thanks!
