### ISSUE TITLE
Is there a way to preserve Mongo DB state while updating JSON file?

### ISSUE THREAD

**Issue by ChinoMing** [perak/kitchen-site#200]
I am wondering if there is a way to preserve Mongo DB state while updating a JSON file.  

For example, I've just generated meteor code for [example-admin](https://github.com/perak/kitchen-examples/tree/master/example-admin) using `meteor-kitchen example-admin.json temp1`.  I register a user and then use mongo shell to `db.users.update({ _id: "YOUR_USER_ID" }, { $set: { roles: ["admin"] } })` to provide the user with an admin role.

When I make changes to the JSON file, e.g. change the name of the application, and `meteor-kitchen example-admin.json temp1`, the changes are not reflected in the folder temp1.  When doing `meteor-kitchen example-admin.json temp2` the changes are reflected in the generated code ok.  I'd hope to preserve the user with admin role in the collection in _temp1_ rather than having to do the mongo shell update for every change I make to the JSON file. 

Is there a way to update the JSON file and have it reflected in a folder _temp1_ rather than having to use a new folder _temp2_?

**Comment by perak** [comment]
@ChinoMing of course. I am wondering how you do that? Maybe your next execution of meteor-kitchen is from wrong directory. Since your output path is relative (temp1) be careful what is your current dir when executing command again (or just specify full path as output dir).

BTW, what OS (amd version) are you using?

**Comment by ChinoMing** [comment]
@perak Windows 7

**Comment by perak** [comment]
:+1:
