### ISSUE TITLE
Unable to generate correct files in \client\view folder

### ISSUE THREAD

**Issue by ChinoMing** [perak/kitchen-site#202]
Just tried generating code from example-invoices (https://github.com/perak/kitchen-examples/tree/master/example-invoices) on my local machine (Win7) and it doesn't seem to be generating the expected files in \client\view.  Other examples seem to be generating fine.  I've tried generating the example-invoice code on meteorkitchen.com and it generates the expected files in the view folder.  Are there any logs to troubleshoot why my local version is not generating the files?

Only log I see is from the cmd line:
```
Creating directory structure...
Creating router...
Creating collection "customers"...
```

**Comment by perak** [comment]
@ChinoMing does it just stop after `Creating collection "customers"...` ? (no `generator finished` message?)

**Comment by ChinoMing** [comment]
Yup that's all.  After that its back to the command prompt.

**Comment by ChinoMing** [comment]
Just in case, I've also re-installed meteorkitchen, but still same result.

**Comment by perak** [comment]
Hummm... it crashes. :)

Give me steps how to reproduce. What exact command you executed?

**Comment by ChinoMing** [comment]
c:\>meteor-kitchen example-invoices.json test

**Comment by ChinoMing** [comment]
The workaround for this appears to be to just re-run ```meteor-kitchen example-invoices.json test``` again and it will pick up where it left off and create the rest of the files.
