### ISSUE TITLE
Conditional routing in meteorkitchen

### ISSUE THREAD

**Issue by xauxatz** [perak/kitchen-site#205]
Hi - I hope I can get a tip on the best/prettiest way to implement this.
I have a dataview showing a collection.
It is linked up a details page using "Details route".
However, the dataview can display data of different types. And depending on the type of the element, I would like to go to different details pages.
I am able to set a route parameter "type" so I get a dynamically created page link:
collection.details/id=xyz&type=standard

I guess there are two solutions:
1) Go to the same details page for all types. Dynamically change the layout of this page based on the type parameter.
2) Go to different details pages based on the type parameter.

I cannot see that I am easily able to do either of the above.
Any advice on the best way forward would be much appreciated.

**Comment by xauxatz** [comment]
I guess if I could somehow override the OnBeforeAction hook for routes, then I could create my own routing to subpages of details. But that doesn't seem to be possible.

**Comment by julienrott** [comment]
Hi,
What about using a custom template using a template helper ?
In the template
```html
{{#if displayStandard}}
  <div id="standard">
    Standard display
  </div>
{{/if}}
```

**Comment by xauxatz** [comment]
julienrott, thanks - but if I do that it doesn't really play together with Meteorkitchen anymore, it seems.
I was thinking of an alternative solution, actually - where I could override the click event on the dataview and then handle the routing on my own to the correct dataview.details<type> subpage.
That seems like a solution that plays relatively well together with Meteorkitchen.

**Comment by julienrott** [comment]
Custom templates are a Meteorkitchen feature, what do you mean with "it doesn't really play together with Meteorkitchen anymore" ?
If you mean the save/cancel/back buttons or the automatic form generation, I think it is possible to reuse or inject the Meteorkitchen templates in the custom template.

**Comment by xauxatz** [comment]
Sorry, it is probably due to the fact that I don't have much experience with these. Thanks in any case, I'll look into it and see what's the best option

**Comment by perak** [comment]
@xauxatz you can use page's `controller_before_action`. Add code to execute before route renders:

```
"controller_before_action": "switch(this.params.type) { case: \"standard\": Router.go(\"somewhere\", { id: this.params.id, type: this.params.type); break; default: this.next(); }"
```

This will result in onBeforeAction in your controller:

```
...
onBeforeAction: function() {
  switch(this.params.type) {
    case: "standard": Router.go("somewhere", { id: this.params.id, type: this.params.type }); break;
    case: "cool_type": Router.go("whatever" .......... ; break;
    default: this.next();
  }
}
...
```

**Comment by xauxatz** [comment]
This would be an exceptionally nice way to do it, except that it doesn't 
seem to work.

Any code I put inside "controller_before_action" does not end up in the 
finalized code after meteorkitchen processing :-(

Will it be fixed in the next release?

**Comment by xauxatz** [comment]
Hmmmm, it seems to work now ... Very strange.
I'll look into it and report back.

**Comment by xauxatz** [comment]
I now checked whether this would work, but unfortunately it does not.

The below code is called prior to displaying the dataview.

I need to call some code when a row in the dataview is clicked to 
control the routing to the "details" page.

Your suggestion below doesn't seem to be able to do that.

**Comment by perak** [comment]
@xauxatz that code should be in your details route, not in the route where is dataview.

**Comment by perak** [comment]
So, when item is clicked, details route is called and this code executes, redirecting user to another routes depending on value of 'type'

**Comment by xauxatz** [comment]
Very very nice. It works!

Many thanks. Meteorkitchen makes me feel like I have superpowers!

**Comment by perak** [comment]
:D :+1:

**Comment by perak** [comment]
Glad it works! Let's close this issue then.

**Comment by perak** [comment]
@xauxatz one more way (I think simpler one) added into v0.9.56, see this issue: https://github.com/perak/kitchen-site/issues/163

**Comment by perak** [comment]
Now you can add custom code on table row click.

Here is how to add custom code:

In **dataview** component, there is new `on_item_clicked_code`:
```
"on_item_clicked_code": "alert(\"You clicked to item with ID: \", this._id);\n console.log(this._id);"
```
