### ISSUE TITLE
Getting multiple fields in Joins

### ISSUE THREAD

**Issue by innocube** [perak/kitchen-site#207]
Hi, 

I have googled and not found what I was looking for:
I would like to bring multiple fields out of joins. When I choose one, I would like to fill multiple fields in a form. How can I do that? I could see single field example, but not multiple ones.

Any help would be greatly appreciated.
Thank you.

**Comment by perak** [comment]
@innocube I'm not sure I understand your issue... show me that "single field example".

**Comment by innocube** [comment]
Perak,

In your Join Example,

        {
            "name": "companies",
            "fields": [
                {
                    "name": "name",
                    "title": "Company name"
                }
            ]
        },
        {
            "name": "employees",
            "fields": [
                {
                    "name": "name",
                    "title": "Employee name"
                },
                {
                    "name": "companyId",
                    "join_collection": "companies",
                    "join_container": "company",
                    "join_fields": ["name"]
                }
            ]
        }

You are getting single field, "name" from company collection. There must be a way to get let's say company address as well as name. I was wondering how to do that.

Thank you in advance for your help!

**Comment by innocube** [comment]
Let me show you another example. Let's say I want to choose an item from the following:
items - sku, description, price
In my joins, I would like to get price along with what I selected, sku automatically.

**Comment by perak** [comment]
@innocube in example you copied, see `join_fields` array: this is where you define which fields you want from companies collection:

```
"join_fields": ["name", "address", "phone"]
```

**Comment by innocube** [comment]
Perak,

Yes, that's right. And when I select, let's say, just a name among several, how can I populate corresponding address and phone information in my code using meteor-kitchen?

**Comment by perak** [comment]
Hum... you are selecting it using <select> ? Maybe to add "select change" event. There is no automatic way provided by kitchen.

**Comment by innocube** [comment]
Perak,

Thank you for your responses!

					{
						"name": "itemId",
						"title": "Item",
						"required": true,
						"input": "select",
						"lookup_query_name": "item_list",
						"lookup_field": "description",
						"lookup_key": "_id",
						"show_in_dataview": false,
						"show_in_read_only_form": false,
						"exportable": false,

						"join_collection": "items",
						"join_fields": ["description", "price"],
						"join_container": "item"
					},
					{
						"name": "item.description",
						"title": "Item",
						"show_in_insert_form": false,
						"show_in_update_form": false,
						"exportable": true
					},
					{
						"name": "item.price",
						"title": "Price",
						"type": "float",
						"show_in_insert_form": false,
						"show_in_update_form": false,
						"exportable": true
					},

By using this, now I could successfully display the linked price information (item.price) as I select item.description. However I have learned that there is no way that I could reference that item.price in before_insert_code. Do you have any idea?

**Comment by perak** [comment]
@innocube data is joined performing `transform` http://docs.meteor.com/#/full/mongo_collection

In collection `before.*` and `after.*` hooks you got raw data from database (not modified with transform) and that's why you cannot access joined data from there.

However, you can still do `var item = Items.findOne({ _id: doc.itemId });` in your hooks.

**Comment by innocube** [comment]
Perak,
That was exactly what I was looking for!
Thank you so much, my life-saver!

**Comment by perak** [comment]
:+1:

Let's close issue if it is solved.
