### ISSUE TITLE
Default sort order for data_view

### ISSUE THREAD

**Issue by puddicombe** [perak/kitchen-site#208]
Hi Petar,

Is it possible to set a data_view to render the collection in a default order?  I've tried adding an $orderby clause in the underlying query but I can't get the syntax to be accepted through the GUI.

Many thanks,
James

**Comment by perak** [comment]
@puddicombe you can set sort order in your query, set `options` like this:

```
 {
    "name": "customers",
    "collection": "customers",
    "filter": {},
    "options": { \"sort\": { \"name\": 1 } }
}
```
*instead `1` you can set `-1` for descending order*

**Comment by puddicombe** [comment]
Great - thanks!  And best wishes for your newborn!

Cheers,
JAmes
ᐧ

On 6 January 2016 at 11:19, Petar Korponaić <notifications@github.com>
wrote:

> @puddicombe <https://github.com/puddicombe> you can set sort order in
> your query, set options like this:
>
>  {
>     "name": "customers",
>     "collection": "customers",
>     "filter": {},
>     "options": { \"sort\": { \"name\": 1 } }
> }
>
> *instead 1 you can set -1 for descending order*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/perak/kitchen-site/issues/208#issuecomment-169301200>.
>



-- 
James Puddicombe
Director
M: 07787 556007
W: www.voodoo.co.uk <http://www.voodoo.co.uk/?source=email>

<http://uk.linkedin.com/in/puddicombe/>
<http://www.voodoo.co.uk?source=email>
