### ISSUE TITLE
Bootstrap Dropdown menu not auto closing on click outside element !

### ISSUE THREAD

**Issue by quangmach** [perak/kitchen-site#209]
Dear,

I got the problem with Bootstrap Dropdown menu not auto closing (Collapse) on click outside element ! But I just google and figure out the fix fo that by add these code below to end of 2 files in 
meteorkitchen\templates\ui\bootstrap3\layouts

1. layout_container_accounts.js
2. layout_container_simple.js

```
Template.layout.events({ 
    "click": function(event) { /* Fix Bootstrap Dropdown Menu Collapse on click outside Menu*/
        var clickover = $(event.target).closest(".dropdown-toggle").length;
		var opened = $(".navbar-collapse").hasClass("in");
        if (opened === true && !clickover) {
            $('.navbar-collapse').collapse('hide');
        }
    },
    
    "keyup": function(event) {
	    if (event.keyCode === 27) { /* Bootstrap Dropdown Menu Collapse on ESC pressed*/
	        var opened = $(".navbar-collapse").hasClass("in");
	        if (opened === true) {
	            $('.navbar-collapse').collapse('hide');
	        }
	    }
    }
});
```

Please have a review and added it to the CLI package in the future to fix it.

Thank you.

**Comment by perak** [comment]
@quangmach added to `v0.9.55`, will be uploaded later today.

**Comment by perak** [comment]
@quangmach fixed. Can we close this issue now?
