### ISSUE TITLE
Bringing only relavant data 

### ISSUE THREAD

**Issue by innocube** [perak/kitchen-site#212]
I am a novice to Meteor.
I have CATEGORY and PRODUCTS collection.
When user selects a CATEGORY, I would like to bring only valid PRODUCTS list.

How can I do this with meteor-kitchen?
Your hint or any help will be greatly appreciated.
Thank you!

**Comment by innocube** [comment]
If I can have query of PRODUCTS based on CATEGORY field, it would be simple.
But so far, I had no luck.

**Comment by quangmach** [comment]
I'm recently in trouble with that too. But seems like there is no support for that dependent data in meteor-kitchen yet.

**Comment by innocube** [comment]
@quangmach Really?
There must be a way. Hum..

**Comment by perak** [comment]
@innocube there is two ways (maybe more). Now I'm typing from mobile phone, so I'll tel you a principle without code, later I can write example.

1. using url params

2. using session variable

---

## using url params

in your page's `route_params` define param `itemId?` (ending with question marke means it's not mandatory). For dataview with master dataset define `details_route` to be this page route (the same page) and `details_route_params` this.__id`. So when use clicks on the master data item, will be redirected to thesame url but with item id in the url.

Now, in your details query, filter by `this.params.itemId`. That's it.

## using session variable

master on click event set `Session.set("itemId", clicked item id)`, and in details dataset query filter by Session.get("itemId")

**Comment by innocube** [comment]
@perak Wow.. So I have expected, there are ways to do although I am not sure if I can just do in meteor-kitchen. If you could show me a little bit of code, it would be much helpful for a novice in meteor like me.

Thank you so much!

**Comment by innocube** [comment]
Let me explain a little more:

I have CATEGORY selection and PRODUCT selection on one page.
When user select a category, PRODUCT needs to load corresponding choices.

**Comment by innocube** [comment]
@perak 
I am getting CATEGORY ID when a client selects one. However I am still struggling how to retrieve PRODUCT LIST according to this CATEGRORY ID.

Since meteor-kitchen generated code is composed of XXcontroller.js, XX.html, and XX.js, I am not sure how to set to bring relevant data only according to client's previous selection on CATEGORY.

If you could  show me a code example, I would really appreciate it.
Thank you again for your good work!

**Comment by quangmach** [comment]
@innocube This works for me but my case is everytime I change select input, it re-subscribe and publish with id filter on server side as I have lots of upper items to store in client database. This one I write for case of subscribing all and filter on client side upon change on select input.
I use Session as google, haven't test it yet so please try and feedback to me.

change selectinput_name to your one and copy this one to Page->Component-> Events where select input located (For my case is Insert form)
```
"change select[name='selectinput_name']": function (e,t){
var cat_id = $(e.target).val();
Session.set("cat_id", cat_id); 
console.log(Session.get("cat_id"));
},
```

This one goes to Helpers section. Change helpers_name to your one. (I take cat_id example for your category id)
```
"helpers_name": function(){
    var cat_id = Session.get("cat_id");
    return Product.find({category_id: cat_id}, {});
},
```

This one goes to Template rendered code section (Set cat_id = 0 to make select input not display all Product list items)
```
if(!Session.get("cat_id")) Session.set("cat_id","0");
```

**Comment by perak** [comment]
@quangmach thanks, your solution is OK, more correct one is filtering server side, and filtering should be done in the controller. If data is filtered in a controller then you can access filtered data in all events and helpers:

You need to define your product **query** like this:
```
{
  "name": "product",
  "filter": { "categoryId": ":categoryId" }
} 
```

In page where you use "product" query, I believe you need to subscribe both to category and product, so your page or component looks something like this:
```
{
  "name": "your_page_name",
  "query_name": "your_page_main_query_name",
  "query_params: [],

  "related_queries": [

    {
      "name": "category",
      "params": []
    },

    {
      "name": "product",
      "params": [
        { "name": "categoryId", "value": "Session.get(\"cat_id\")" }
      ]
    }

  ]
}
```

Now, your form's event should look like @quangmach suggested:

```
{
  ...
  "events_code": "\"change select[name='selectinput_name']\": function (e,t) { Session.set(\"cat_id\", $(e.target).val()); }"
  ...
}
```

Resulting code should be:

in controller:
```
...
  Meteor.Subscribe("product", Session.get("cat_id"));
...
  product = Product.find({ categoryId: Session.get("cat_id") });
```

in server/publish:
```
...
  "product": function(categoryId) {
    return Product.find({ categoryId: categoryId });
  }
...
```

in your_page.js
```
Template.your_page_name.events({
  ...
  "change select[name='selectinput_name']": function (e, t) {
    Session.set("cat_id", $(e.target).val()); 
  },
  ...
});
```

And that should work as expected.

**Comment by innocube** [comment]
@quangmach
It is working perfectly fine now!
So I just needed to return in helper class.
I got it.
Thank you so much!

**Comment by quangmach** [comment]
@innocube Good to see that works for you. However, like @perak said, mine one just grab all the database and filter on client side, so it is not so good if you have lots of items. It is better to filter on server side then publish -> client subscribed to it.

**Comment by innocube** [comment]
@perak Thank you for letting me know a proper way to publish & subscribe according to previous selection!

Now, I am wondering is there anyway that I can limit or expand accessibility of data set according to the level of user. For instance, for admin & manager, I would like to display everything, but for user, I would like to limit items only specific to that user. How can I do that?

**Comment by perak** [comment]
Just set `"roles_allowed_to_read": ["owner", "manager"] ` in a collection. So only owner user (user who created document) and user with "manager" role will have access to it.

**Comment by innocube** [comment]
@perak 
My question was a little bit different. What I want is on a page according to user level I would like to limit or allow contents, not limiting the page access.
Thank you!
