### ISSUE TITLE
Data Input in Meteor-Kitchen

### ISSUE THREAD

**Issue by innocube** [perak/kitchen-site#214]
I have two things:

I would like to automatically generate ItemNumber without showing on the Insert page.
But if I use "show_in_insert_form" set to false, it doesn't generate the number. How can I still generate number without showing on the page?

The other one: I have price field coming from already created collections (joins). This time I would like to show joined field on the page and let user edit if needed. However the value is not shown when I activate to show the price on the page. If I set not to show the price on the page, I am getting correct price in my document. How can I show and still fill the field with the value?

**Comment by perak** [comment]
For the first problem, you can use ` "input": "hidden"`, but I think you don't need thatfield in a form at all. Youst remove it frominsert form, and generate number in `before_insert_code` (that executes server side).

Second problem: you need to use real price field in this collection (not joined one) and use helper in `default` value of the field. `"default": "myHelper"`, and then define helper in `helpers` code or something like that.

**Comment by innocube** [comment]
@perak 
Thank you so much!
I managed to fix both issues as you have suggested.
