### ISSUE TITLE
CLIENT_LIB_DIR points to client dir and CLIENT_LIB_DIR/ points to client/lib

### ISSUE THREAD

**Issue by kjetilge** [perak/kitchen-site#215]
CLIENT_LIB_DIR points to client dir and CLIENT_LIB_DIR/ points to client/lib. I find this a little confusing.

**Comment by perak** [comment]
@kjetilge watching code and I don't see nothing wrong... how to reproduce that?

`CLIENT_LIB_DIR` always points to `client/lib` (or I am missing something...)

**Comment by quangmach** [comment]
I think he meant ````CLIENT_LIB_DIR```` and ````CLIENT_LIB_DIR/```` with and without slash

**Comment by perak** [comment]
humm... if desination is set to simple "CLIENT_LIB_DIR/" (with trailing slash), then resulting string will be "client/lib//". Is it the issue? Best I can do is to remove double slash-es after replace.

**Comment by kjetilge** [comment]
"CLIENT_LIB_DIR/" looks like a path-string, not a variable or name. I believe that when specifying CLIENT_LIB_DIR as a destination folder many people expects their files to end up in the lib folder of the client folder. If this is not achievable at  present it would help a lot to just refer to "CLIENT_LIB_DIR/" in the documentation.

**Comment by perak** [comment]
@kjetilge still cannot reprodu e this issue. `CLIENT_LIB_DIR/some_file.xxx` goes into `client/lib/some_file.xxx`.

Give me your example to reproduce issue (btw, what OS you are using?)

**Comment by kjetilge** [comment]
Here is a sample file with trailing "/" on "CLIENT_LIB_DIR/". Without the trailing "/" the file is copied to "server" folder but with the trailing slash it is copied to "server/lib".
I am using OSX 10.10.5

![screen-dump](https://cloud.githubusercontent.com/assets/1749884/12394865/b8357832-bdfe-11e5-89ea-566600d0edc2.png)

[TestApp2.json.zip](https://github.com/perak/kitchen-site/files/94560/TestApp2.json.zip)

**Comment by perak** [comment]
@kjetilge ah... now I understand. Actually, correct way is to set full path: `SERVER_LIB_DIR/email_config.js` (not just directory name) but this also should work... I'll fix it in v0.9.57

Thanks for bug-catch!

**Comment by kjetilge** [comment]
I see. Thanks!

**Comment by perak** [comment]
@kjetilge fixed in v0.9.57 (not published yet).

**Comment by perak** [comment]
Done.
