### ISSUE TITLE
Meteor kitchen GUI very slow right now....

### ISSUE THREAD

**Issue by xauxatz** [perak/kitchen-site#222]
It takes 10-15 minutes per save. Is there anything that can be done?
Or any way to work around it?

**Comment by perak** [comment]
Meteor's free hosting sucks.

**Comment by xauxatz** [comment]
Yeah, I thought that might be the answer :-)

Would you consider putting it on a Digitalocean droplet? Perhaps a small 
one can run it.

I'd personally be happy to pay a bit to keep it running a bit faster. 
I'm sure others would feel the same.

**Comment by perak** [comment]
@xauxatz yeah, its very bad last few weeks. I was planning to move it to a new server when I finish a new GUI, but this is really bad - sometimes I cannot login.

I'll do it this week.

BTW, donation is always welcome, so if you are willing to donate - I added PayPal option too: http://www.meteorkitchen.com/donate

I don't have "Donate button" option in my PayPal account - looks like it doesn't work in my country (Serbia).

Thanks! :+1:

**Comment by perak** [comment]
BTW, here sneak peek to a new GUI:

![screen shot 2015-12-30 at 12 20 39 am](https://cloud.githubusercontent.com/assets/5630814/12419955/968dc5f2-beb9-11e5-8168-877f3f54e871.png)
![screen shot 2015-12-30 at 12 23 30 am](https://cloud.githubusercontent.com/assets/5630814/12419956/9692474e-beb9-11e5-816b-26cdad764c8b.png)
![screen shot 2015-12-30 at 12 25 16 am](https://cloud.githubusercontent.com/assets/5630814/12419957/9699f93a-beb9-11e5-9680-083894c088e0.png)
<img width="1434" alt="screen shot 2016-01-15 at 11 24 21 pm" src="https://cloud.githubusercontent.com/assets/5630814/12419968/affaad3e-beb9-11e5-85e2-9336b49e73df.png">

And work on more visual application designer is in progress...

**Comment by kjetilge** [comment]
Generate the meteor-kitchen app and work locally. I run it on port 4000 and my app under development on 3000.

**Comment by perak** [comment]
@kjetilge :+1:

**Comment by xauxatz** [comment]
Very nice!  Btw. I followed the advice of Kjetil and built a local app 
of meteor-kitchen.

**Comment by perak** [comment]
OK, great. 

BTW, I just setup new server and now trying to dump database from meteorkitchen.com - it's so slow - I got timeout 10 times and still trying... :o

**Comment by perak** [comment]
@xauxatz @kjetilge moved to a new server. DNS propagation in progress...

**Comment by perak** [comment]
@xauxatz I think we can close this issue now.
