### ISSUE TITLE
1.3-modules-beta.5 : TypeError: Cannot set property 'getPropertyValue' of undefined

### ISSUE THREAD

**Issue by ljack** [perak/kitchen-site#228]
Trying meteor-kitchen with 1.3-modules-beta.5 
https://github.com/meteor/meteor/issues/6075

**Comment by perak** [comment]
Must be loading order issue (that's changed in 1.3), or file `lib/object_utils.js` is not loaded at all?

**Comment by ljack** [comment]
object_utils.js:
console.log("hello ",this);
this.getPropertyValue = function(propertyName, obj) {
	return propertyName.split('.').reduce(function(o, i) { return o[i]; }, obj);	
};
build log:
I20160125-12:14:48.051(0)? hello  undefined   
=> Exited with code: 8
W20160125-12:14:48.054(0)? (STDERR)           
W20160125-12:14:48.054(0)? (STDERR) /home/ubuntu/.meteor/packages/meteor-tool/.1.1.12-modules.5.a45895++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245

**Comment by perak** [comment]
What happens if `this.getPropertyValue` is defined without `this.` ? Actually, I put `this.` to global functions because js to coffee converter - that way, function is converted to `@getPropertyValue` (it's global), but without `this.` it's just `getPropertyValue` in coffee.

**Comment by ljack** [comment]
I did it like this: https://github.com/airbnb/javascript#7.1 Use function declarations instead of function expressions. And it seems to "compile", let's see if it actually works ;)

**Comment by ljack** [comment]
Same fix applies to all the collections files. this.Collection needs to be typed const Collection = new ...

So this works:
```
const Customers = new Mongo.Collection("customers");

Customers.userCanInsert = function(userId, doc) {
	return true;
}

Customers.userCanUpdate = function(userId, doc) {
	return userId && doc.ownerId == userId;
}

Customers.userCanRemove = function(userId, doc) {
	return userId && doc.ownerId == userId;
}
```

**Comment by ljack** [comment]
Seems https://github.com/meteor/meteor/blob/release-1.3/packages/modules/README.md is something to be read to get this working.

**Comment by ljack** [comment]
I basically got the meteor-kitchen generated version to run by removing "ecmascript" package. Which is mixed in the modules/import/export stuff. However the result was the same, application started ok (with the "this.Invoices" etc in place as generated by kitchen), but resulted with the iron router info screen..

**Comment by perak** [comment]
@ljack great, thank you for research. I'll join you tomorrow on this issue, must be solved before 1.3 release...

**Comment by perak** [comment]
(iron-router should be replaced with flow-routerin near future...)

**Comment by ljack** [comment]
https://github.com/meteor/meteor/issues/6072 might be related also.

**Comment by ljack** [comment]
Re visit this issue when next beta is released . Watching https://github.com/meteor/meteor/releases
