### ISSUE TITLE
How to specify nested lookup?

### ISSUE THREAD

**Issue by bartuelen** [perak/kitchen-site#233]
I am using joins and lookup to retrieve a "parent" document from a "child" document and display these fields in a dataview. That works fine using MeteorKitchen.
Tried different approaches, but did not manage yet using MK to retrieve some "parent - parent" document using a kind of nested lookup using underlying queries / related queries.

Got 3 collections: Artists, Albums and Songs with a straightforward hierarchical relationship between them.
So from bottom up:
- Songs has an albumId joining to _id in Albums.
- Albums has an artistId joining to _id in Artists.

Displaying a Song (=child) I would like to display the Album title (=parent) and also the Artist name (=parent's parent) of the Album.

The Album title is no problem. It is from the "child" to the "parent". But the Artist name I did not get displayed from "child" to "parent's - parent" using MK.

Is there a way in MK to specify how to retrieve "parent - parent" data and show it in a dataview?
Has someone an example?

I noticed a solution mentioned earlier on Github "Relations between collections #46" from Februari 2015 how to retrieve anything you want to display in a dataview. I implemented that solution and the "parent - parent" data shows up correctly.

Though this solutions is a litle bit outside of MeteorKitchen, is it anyhow possible to specify above nested lookup plainly using MK?

**Comment by ljack** [comment]
On your query add options and in there add transform. In transform you can almost anything to the collection contens ;)

example
```
{
	"transform": "function(email) { Subscriptions.find({ _id: email.subscriptionId }).map(function(sub) { email.subscription = sub; }); Rules.find( {_id: email.subscription.rule}).map( function(rule) { email.subscription.ruleDoc = rule;}); return email; }",
	"sort": [
		[
			"date",
			"desc"
		]
	]
}
```

**Comment by perak** [comment]
@ljack thanks! @bartuelen this is correct answer.

**Comment by bartuelen** [comment]
Didn't thought about that solution, but your right, I'll implement it as suggested. Just put it in the query! **@ljack** Thanx.

**Comment by bartuelen** [comment]
based on the suggested solution, here is the code I put into the query:

{
	"transform": "function(doc) {var alb = Albums.findOne({ _id: doc.albumId });doc.albumName = alb.name;doc.albumArtistId = alb.artistId;doc.albumPhoto = alb.photo;doc.albumPhotoUrl = alb.url;var art = Artists.findOne( { _id: doc.albumArtistId } );doc.artistName = art.name;return doc;}"
}

Works!

**Comment by perak** [comment]
Great! :+1:

By the way, take a note that "transform" is not reactive - means: if `album.name` or `artist.name` is changed, it will not be instantly (reactively) reflected to transformed doc's `albumName` and `artistName`.
