### ISSUE TITLE
How to display image using MK ?

### ISSUE THREAD

**Issue by bartuelen** [perak/kitchen-site#235]
I am struggling how to show an image using Meteor Kitchen.
See the by MK generated code below (only a part is shown here).
This code will not show the image( i.e. {{photo}} ).

```
<template name="ArtistDetailPageAlbumsByArtistPageAlbumsByArtistDataviewTableItems">
	<tr id="dataview-table-items-row">
		<td>
			{{name}}
		</td>
		<td>
			{{photo}}
		</td>
		<td class="td-icon">
			<span id="edit-button" class="fa fa-pencil {{editButtonClass}}" title="Edit">
			</span>
		</td>
		<td class="td-icon">
			<span id="delete-button" class="fa fa-trash-o {{deleteButtonClass}}" title="Delete">
			</span>
		</td>
	</tr>
</template>
```

Manually replacing the {{photo}} line with the following code does show the album photo.

```
<template name="ArtistDetailPageAlbumsByArtistPageAlbumsByArtistDataviewTableItems">
	<tr id="dataview-table-items-row">
		<td>
			{{name}}
		</td>
		<td>
			{{#with container_album_photo}}
				{{#if isImage}}
					<a href="{{url}}" target="_blank"><img src="{{url}}" width="20%"></a>
				{{/if}}
			{{/with}}
		</td>
		<td class="td-icon">
			<span id="edit-button" class="fa fa-pencil {{editButtonClass}}" title="Edit">
			</span>
		</td>
		<td class="td-icon">
			<span id="delete-button" class="fa fa-trash-o {{deleteButtonClass}}" title="Delete">
			</span>
		</td>
	</tr>
</template>
```

I 'd rather not prefer to manually replace code outside MK or using references to external templates (i.e. files/....) for such a straightforward situation.
Is there any possibility to add somewhere in Meteor Kitchen this replacement code?
For the photo field in the dataview I tried different properties like combination of "Input", "Input template" and/or "Display helper", but none resulted in the code that displays the photo.

Any suggestions?

**Comment by ljack** [comment]
Hmm. I had another example somewhere, but I've misplaced the json for the app ;) 

Maybe https://github.com/perak/kitchen-examples/blob/master/example-photosharing/example-photosharing.json could help you? 

Github page https://github.com/perak/kitchen-examples/tree/master/example-photosharing

Youtube video too https://youtu.be/7zWBhtE72o4?t=265 . Nice work Petar ;)

**Comment by bartuelen** [comment]
**@ljack** Thanks for your many tips. They emphasize the direction I was looking for and I've studied these examples exhaustively. But the solutions I am looking refers to or focusses on a single field, i.e. the "Image" to be displayed.
The photosharing example I allready incorporated it in another MK generated application. Indeed very nice work!

**Comment by ljack** [comment]
Ah,
  Then maybe display_helper? What's stored in "photo" field? Url ? Or is it uploaded to mongo?

**Comment by perak** [comment]
@ljack Beautiful!

**Comment by bartuelen** [comment]
**@ljack** Implemented your coded for images and for audio. Works great!

For the Album cover images here are the collections I use:
```
			{
				"name": "album_photos",
				"type": "file_collection",
				"storage_adapters": [
					"filesystem"
				]
			},
			{
				"name": "albums",
				"type": "collection",
				"fields": [
					{
						"name": "name",
						"title": "Album",
						"type": "string",
						"required": true
					},
					{
						"name": "artistId",
						"title": "Artist ID",
						"type": "string",
						"required": true,
						"join_collection": "artists",
						"join_container": "artist_container",
						"show_in_dataview": false,
						"show_in_insert_form": false,
						"show_in_update_form": false,
						"show_in_read_only_form": false
					},
					{
						"name": "photo",
						"title": "Photo",
						"type": "string",
						"input": "file",
						"file_collection": "album_photos",
						"file_container": "container_album_photo",
						"show_in_dataview": false,
						"show_in_read_only_form": false
					},
					{
						"name": "container_album_photo",
						"title": "Album photo",
						"type": "string",
						"input": "read-only",
						"display_helper": "displayAlbumPhoto",
						"show_in_insert_form": false,
						"show_in_update_form": false
					}
				]
			}

```

The display helper for the image inserted into the "application" --> "client_startup_code" property:

```
Template.registerHelper("displayAlbumPhoto", function (file) {
  var img="";
  var url = file.url();
  img = "<img src='"+url+"'/>";
  return new Handlebars.SafeString(img);
});
```


For the Songs audio files the collections are:

```
			{
				"name": "song_files",
				"type": "file_collection",
				"storage_adapters": [
					"filesystem"
				]
			},
			{
				"name": "songs",
				"type": "collection",
				"fields": [
					{
						"name": "name",
						"title": "Song",
						"type": "string",
						"required": true
					},
					{
						"name": "albumId",
						"title": "Album ID",
						"type": "string",
						"required": true,
						"join_collection": "albums",
						"join_container": "album_container",
						"show_in_dataview": false,
						"show_in_insert_form": false,
						"show_in_update_form": false,
						"show_in_read_only_form": false
					},
					{
						"name": "trackNumber",
						"title": "Track Number",
						"type": "integer",
						"default": "0"
					},
					{
						"name": "song",
						"title": "Song file",
						"type": "string",
						"input": "file",
						"file_collection": "song_files",
						"file_container": "container_song_files",
						"show_in_dataview": false,
						"show_in_read_only_form": false
					},
					{
						"name": "artistId",
						"title": "Artist ID",
						"type": "string",
						"join_collection": "artists",
						"join_container": "artist_container",
						"show_in_dataview": false,
						"show_in_insert_form": false,
						"show_in_update_form": false,
						"show_in_read_only_form": false
					},
					{
						"name": "container_song_files",
						"title": "Audioplayer",
						"type": "string",
						"input": "read-only",
						"display_helper": "displayAudioPlayer",
						"show_in_insert_form": false,
						"show_in_update_form": false
					}
				]
			}
```

Below the display helper for the audio also added to the "application" --> "client_startup_code" property:

```
Template.registerHelper("displayAudioPlayer", function (file) {
  var audio="";
  var url = file.url();
  audio = "<audio src='"+url+"' controls=\"controls\"></audio>";
  return new Handlebars.SafeString(audio);
});
```


Both render nicely on the generated dataviews and forms!

**@ljack** Thanks for the solution!

**Comment by bartuelen** [comment]
... and not to forget a screenshot of the results with album cover image (The Doors - 13) and audioplayer for each song (now playing: Light My Fire).

![image](https://cloud.githubusercontent.com/assets/7057929/12873529/b088fe8a-cdbf-11e5-98b2-2928b153b659.png)

**Comment by perak** [comment]
@bartuelen wow! Congratulations! Time for champagne! :) :+1: :beers:

**Comment by perak** [comment]
Did you built all with "kitchen" or you generated app and then finished it by coding manually?

**Comment by perak** [comment]
(amd to coment on music: good choice!)

**Comment by bartuelen** [comment]
Try to keep everything as much as possible in MK. Rather not prefer external coding.
For this app I think I will manage. Need to build in restricted delete of parent (Album) when still any child (Songs) around and some playlists functionality.
Exception will be a special manual coded playlist based Audioplayer. There are many javascript / HTML5 based audioplayers available, so got to pick one and squeeze it in manually.
The moment it is finished I intend to put it all on Github.

**Comment by perak** [comment]
@bartuelen restrict delete: you can throw exception in `before_delete_code` (in collection's `before.delete` hook) if there is still any child).

**Comment by bartuelen** [comment]
I will try that comin' days. Thanks for the tip!

**Comment by thoncs** [comment]
I'm doing something similar and using this as an example.  I'm using MK from the command line. 

My relevant collections are structured the same and my template helper is identical to @bartuelen's 'displayAlbumPhoto'.  However, photos are not accessible. They _are_ getting written to Mongo.

This does not work:
`http://localhost:3000/cfs/files/exercise_files/cNAmt8QaP5MiXuxSv/golif-drawing.jpg?token=eyJhdXRoVG9rZW4iOiJkVWktM3V6M1BFdUpud3BIUkttV3BSU2JxN0hrazVFa2wxVEduZENTYVRMIn0%3D/`

**But this does:** 
`http://localhost:3000/cfs/files/exercise_files/cNAmt8QaP5MiXuxSv/?file_name=golif-drawing.jpg?token=eyJhdXRoVG9rZW4iOiJkVWktM3V6M1BFdUpud3BIUkttV3BSU2JxN0hrazVFa2wxVEduZENTYVRMIn0%3D/`

Note that I'm _manually typing_ the query string `?file_name=` into the address bar to access the photo.

Anyone know what I'm looking at? Any help would be appreciated.

**Comment by thoncs** [comment]
Well, after messing with it for 2 days, I've fixed it 1/2 hour after asking for help. I had to adjust the `"client_startup_code"` registerHelper to include quotes on the url:

`"client_startup_code": "Template.registerHelper('displayPhoto', function (file) {var img=''; var url = file.url(); img = '<img src=\"'+url+'\" class=\"img-responsive\"/>'; return new Handlebars.SafeString(img);});",`
