### ISSUE TITLE
Please give an example about isUserInRoles helper

### ISSUE THREAD

**Issue by cyclops24** [perak/kitchen-site#236]
Hi @perak ,
Can you give me an example about isUserInRoles helper in role package please?
I can't used this helper in my blaze template man.

Thanks regards.

**Comment by perak** [comment]
@cyclops24 `isUserInRoles` expects array for "roles" argument. If user document is in data context then you can simply do: `{{#if userIsInRoles user._id, user.roles}}`. If user docukent is not in the data context, then provide it with helper.

**Comment by perak** [comment]
@cyclops24 Oops, sorry that was wrong answer! You need to provide array of roles via helper (not user.roles).

**Comment by perak** [comment]
`theHelper: function() { return ["admin", "user", "guest"] }` and then use it: `{{#if isUserInRoles theHelper}}`

**Comment by cyclops24** [comment]
Thanks @perak it's worked.
