### ISSUE TITLE
when hosting , fiber module issing error

### ISSUE THREAD

**Issue by harinanda** [perak/kitchen-site#238]
when i try to host website generated by meteor-kichen, fibers module missing error. or give instructuion for ubuntu for any site with meteor
 .

**Comment by perak** [comment]
@harinanda I didn't experienced that. www.meteorkitchen.com is hosted on ubuntu. I'm using `mup` to deploy app to my VPS.

What exact error do you have, and how you deployed it/installed it?

**Comment by perak** [comment]
@harinanda any news related to this issue?

**Comment by harinanda** [comment]
Yes.,seems to issue my  nods.js version . BTW I like meteoe-kitchen.it
needs GUI code formating tool
Regards
Hari
