### ISSUE TITLE
Placing a button after a field in a form

### ISSUE THREAD

**Issue by xauxatz** [perak/kitchen-site#239]
Hi -
I'm trying to do what it says in the subject.
I defined a custom_component to be the button.
I then specified that it should be placed in connection with .field-x1 (which is the field in the form)
And I specified "after" as position.
But the button shows up below the field, unfortunately.
What could be wrong?

**Comment by perak** [comment]
"after" means your html is positioned after specified html tag (in markup). Where do you want it to appear? At the right side of the field? In that case you need to play with css.

**Comment by xauxatz** [comment]
Ok, thanks
