### ISSUE TITLE
libgcc_s_dw2-1.dll and libstdc++-6.dll libgww missing on Windows 10 x64

### ISSUE THREAD

**Issue by KoenLav** [perak/kitchen-site#240]
These files were missing on my install of Windows 10 x64.

You can get them from:

https://sourceforge.net/projects/mingw/

(Install in C:\MinGW, search for the filenames, move them to .meteor-kitchen\bin).

Or download this ZIP (I took the files out for you): https://dl.dropboxusercontent.com/u/896413/lib_dll.zip

@perak I think this could be fixed by statically linking these libraries to the Windows build.

**Comment by perak** [comment]
@KoenLav thank you. I usualy don't test mk under windows, I just execute it when compiled successfully ( :) ), I'll staticaly link the libs in next version. :+1:

**Comment by KoenLav** [comment]
Thanks!

**Comment by dearamy** [comment]
Very helpful

**Comment by perak** [comment]
@KoenLav @dearamy should be fixed now. I statically compiled and deployed kitchen 0.9.61 for windows. Just install it again and please let me know. :) :+1:

**Comment by jmblanc** [comment]
I have also the problem with Win10 and v0.9.67

**Comment by perak** [comment]
@jmblanc I changed build chain, looks like I dynamycaly linked libs again. Will fix it in next version.
