### ISSUE TITLE
Multiple subscribes

### ISSUE THREAD

**Issue by xauxatz** [perak/kitchen-site#246]
Hi -

What is the best way to handle it when you need multiple subscribes on a specific page / component?
It is only possible to specify a single query but often I need more than one to fully handle the logic of a component.

**Comment by perak** [comment]
See "queries" array. It allows you to subscribeto multple queries.

**Comment by xauxatz** [comment]
Nice! Thanks.

**Comment by perak** [comment]
@xauxatz I edited original comment.
