### ISSUE TITLE
Which one in future? react or blaze or both of them?

### ISSUE THREAD

**Issue by cyclops24** [perak/kitchen-site#248]
Hi @perak I see in kitchen site that you working on react version of meteor-kitchen.
In future kitchen version project only can use react or it's optional??

For example we can choose from blaze or react output as new setting or blaze version discontinued??

**Comment by perak** [comment]
You'll have option to choose between "blaze" or "react".

**Comment by perak** [comment]
So, answer is: both of them.

**Comment by cyclops24** [comment]
Thanks @perak. So kitchen will be backward compatible? yes?

**Comment by perak** [comment]
Of course. Default (without command line switch `--react`) is blaze, nothing will change for you.

**Comment by perak** [comment]
Input file structure remains as is (with few newly added properties useful in React apps).

**Comment by cyclops24** [comment]
Thanks @perak.
When you want to release this new version??

**Comment by perak** [comment]
@cyclops24 I'll try to publish experimental version (0.9.48) ~24 hours after now, but that's not a promise. If not - then 10 days after now (I'm going to vacation). :)

**Comment by cyclops24** [comment]
Thanks @perak , have a good vacation man :+1:
