### ISSUE TITLE
Query filter by date range

### ISSUE THREAD

**Issue by chiacy** [perak/kitchen-site#252]
Hi! 

I am trying to build a query filter by date, assuming that I want to display records after the following service date, i.e. 2016-03-01, I set the filter as 
filters: [{"service_date": {"$gt": "2016-03-01"}}],

But the result is always empty even there are records after 2016-03-01 service_date

I have tried using ISODate function following the Mongo manual, it does not work.

Just wonder how this can be done

**Comment by perak** [comment]
Did you tried `"$gt": "new Date('...')" ?

**Comment by chiacy** [comment]
Cannot remember but I will try later in the evening.

Thanks for the tips

**Comment by chiacy** [comment]
too bad, does not seems to work

**Comment by perak** [comment]
@chiacy fixed and will be available in next version v0.9.58 (next week).

**Comment by chiacy** [comment]
thanks !!
