### ISSUE TITLE
Redirect user after login

### ISSUE THREAD

**Issue by markmitton** [perak/kitchen-site#264]
Hi

I am very new to Meteor and meteor-kitchen. I want to redirect my user to a page based on some fields in the user object after login. If it is the first time the user logs in then they will not have a field set and I will redirect them to their profile page to set this/these fields. 

I have tried the following:

Router.onBeforeAction(function () {
  if( (Meteor.user().entityID === undefined) ||
      (Meteor.user().entityID === null)) {
    this.render('user_settings.profile');
  } else {
    this.next();
  }
});

and 

Accounts.onLogin(function (info) {
    console.log('user logged in > \n', info.user);
    if( (Meteor.user().entityID === undefined) ||
        (Meteor.user().entityID === null)) {
        console.log('unknown');
        Router.go('user_settings/profile');
    }
});

Can anyone help please?

**Comment by Maqhosha** [comment]
Hi look for this method in your router.js and change inside the firstGrantedRoute() method . this worked for me    

Router.ensureNotLogged = function() {
	if(Meteor.userId() && (!Meteor.user() || !Meteor.user().roles)) {
		this.render('loading');
		return;
	}

	if(Meteor.userId()) {
		var redirectRoute = firstGrantedRoute("user_settings.profile");
		this.redirect(redirectRoute);
	}
	else {
		this.next();
	}
};

**Comment by markmitton** [comment]
Thanks Maqhosha

I will try this out. Just a question, when you directly modify the code that kitchen generates, you obviously have no backward synchronisation of what you have modified to the kitchen gui or input file. Do you just modify kitchen's output each time you generate or how do you manage this?

**Comment by Maqhosha** [comment]
yes obviously if you modify the code directly there will be no synchronisation, you will have to modify it again if you run the Jason file again.

**Comment by perak** [comment]
Dirty fix is to modify `~/.meteor-kitchen/templates/code/router_client_accounts.js` but that will be overwritten when you install next version of MK

**Comment by markmitton** [comment]
Thanks, I can live with it either way.
