### ISSUE TITLE
React: : template directory not found semantic-ui

### ISSUE THREAD

**Issue by ljack** [perak/kitchen-site#267]
ljack1:~/workspace (master) $ meteor-kitchen --version
0.9.58
....
Error: template directory not found "/home/ubuntu/.meteor-kitchen/templates/react/ui/semantic-ui/".
....

**Comment by ljack** [comment]
ljack1:~/.meteor-kitchen/templates/react/ui $ ls
bootstrap3/

Ok ;)

**Comment by perak** [comment]
@ljack not implemented yet...
