### ISSUE TITLE
My collection references non-existing role

### ISSUE THREAD

**Issue by kjetilge** [perak/kitchen-site#268]
I have:
```
"roles": [
  "admin, user"
],
```
And in videos:
```
"roles_allowed_to_read": [
  "user"
],
```
Still I get
```
Collection "videos" references non-existing role "user". Please add this role to application.roles array.
```
kitchen version: 0.9.57, osx: 10.11.4
Suggestions ?

**Comment by perak** [comment]
You are missing quotes in roles: ["admin", "user"] instead ["admin, user"]

**Comment by kjetilge** [comment]
Thanks. That did it. The reason it happened is because i used comma separated list in GUI in-stead of line-shift separated. It would perhaps be more intuitive if both methods worked (or the help pop-up explained it)

**Comment by perak** [comment]
I agree. Old gui is not intuitive at all... working on a brand new one.
