### ISSUE TITLE
meteor-kitchen can't start because libgcc_s_dw2-1.dll is missing

### ISSUE THREAD

**Issue by kevin0858** [perak/kitchen-site#272]
when i try to use meteor-kitchen on Window 7, it didn't work because libgcc_s_dw2-1.dll is missing.
when i use meteor-kitchen v0.9.54, it works perfectly.
however, when i use meteor-kitchen version over 0.9.54, it's fail to work becacuse libgcc_s_dw2-1.dll is missing.
how can i use meteor-kitchen last version on Window 7?

**Comment by perak** [comment]
@kevin0858 see #240 maybe it helps. After version 0.9.54 dlls are dynamically linked instead statically. I'll fix it in next version. Btw, latest version for windows is not current 0.9.61 (it's few versions older no meteor 1.3 and React support in it), I hope I'll be able to compile latest windows .exe later today or tomorrow.

**Comment by perak** [comment]
@kevin0858 should be fixed now. Please net me know. :) :+1:

**Comment by perak** [comment]
(just install meteor-kitchen again)

**Comment by kevin0858** [comment]
@perak Thank you. it works perfectly on Windows 7. :)

**Comment by perak** [comment]
@kevin0858 Great! :+1: 

OK, Closing this issue...

**Comment by zeroprg** [comment]
Still have the same issue ? ;-(
