### ISSUE TITLE
Server Files 

### ISSUE THREAD

**Issue by jmblanc** [perak/kitchen-site#288]
Is it possible to add or modify specific files for the server ?
 I succeed to do it for client. In case of  the server.
the file main.js was replaced, when I regenerate the whole site.

Thank you for your help.

**Comment by perak** [comment]
If you want to change something in server.js, then copy it into directory where is your .json input file, and into .json add `"copy_files": [ { "source": "server.js", "dest": "SERVER_DIR" }]`, now your version of server.js will overwrite what kitchen generates.

(P.S. you cannot do it from GUI - you can do it only if you are using CLI).

**Comment by perak** [comment]
BTW, `SERVER_DIR` is special string, leave it as is (don't write real path here - because this way, you don't need to edit .json if you move output directory).

**Comment by jmblanc** [comment]
ok, thanks 
this is working, and I am using CLI.
Maybe another thing, i don't understand the example plugin, and I failed to generate files, because exemple1 is not present. Is it possible to have more explanations.
