### ISSUE TITLE
why form0-input-number \error wiil ome ?

### ISSUE THREAD

**Issue by harinanda** [perak/kitchen-site#289]
when i gave json file , it gave error like this at end : 

Creating component "insert_form"...

Field source element "#form-input-number" not found.

**Comment by adnoh** [comment]
To help all will need json file or at least form declaration snipped you've used

**Comment by perak** [comment]
Are you trying to build react app? If so, form componemt for react is not implemented yed. Will be added in next version (in next few days)

**Comment by harinanda** [comment]
No..react..i am able to find probldm with type.
Thank your support..need to bring more tutorials..
