### ISSUE TITLE
User Theme Selection

### ISSUE THREAD

**Issue by rgstephens** [perak/kitchen-site#290]
I'd like to allow the user to select among the list of bootswatch themes. The examples I've seen involve using jQuery to change the `<link ..` to reference the associated css file.

Since Kitchen merges the css files, I'm wondering if there is a way to disable this merge to dynamically update the Theme or is there another approach?

**Comment by perak** [comment]
Hi @rgstephens good question - I don't know how you can do that - I didn't try to play with it.

Problem is not that meteor-kitchen merges css files: problem is that meteor merges css files. 

So, if you add multiple themes into application, each theme will be automatically merged into single css file (and that will guide to nowhere).

Maybe you should just generate application without theme (with naked bootstrap3) and then using external css files from CDN, and as you said, dynamically changing `<link ... ` tag... I don't know, try to play with it and please let me know if you succeed.

:+1:

**Comment by rgstephens** [comment]
@perak - Thanks for the pointers. I'll give this a try and report back.

**Comment by rgstephens** [comment]
I implemented user selectable bootswatch themes following the approach suggested by @perak and posted the code [here](http://flnkr.com/2016/04/user-selectable-theme-with-meteor-kitchen/). I'd like to get the item_list from a session variable as I raised in this [issue](https://github.com/perak/kitchen-site/issues/292) but it's otherwise done.

Gotta love this Meteor Kitchen!

**Comment by perak** [comment]
@rgstephens congratulations!

And thank you! 👍
