### ISSUE TITLE
[Enhancement] File upload to kitchen GUI for things like custom_data_code

### ISSUE THREAD

**Issue by adnoh** [perak/kitchen-site#291]
Hello Perak,
the phantastic Web GUI for Meteor Kitchen is missing something - a way to upload "Input Files" for settings like _custom_data_code_ or _custom_template_. As soon as u have a need to define a own component or similar you can't do it on the web anymore because it won't build.
I mostly use it for generating an APK on the fly and have a quick prototype to test with.
Maybe a quick win would be to accept URLs instead of absolute file locations for specifying the input.
A workaround is to "stringyfy" the files and write it in the json file inline - but the whole escaping is a pain in the a... 
thanks a lot for all the work, already done.

**Comment by perak** [comment]
@adnoh New GUI is comming soon (did you saw the video?) with features you just described (amd many more)

**Comment by perak** [comment]
http://youtu.be/NBtFs1c4qhQ

**Comment by adnoh** [comment]
:) Like Christmas - Look what Santa Perak has in his Bag - it is just amazing! Thank you for sharing this!
I Close the Issue looking forward and beeing excited about the new version

**Comment by perak** [comment]
Santa Perak! :D :D :D
