### ISSUE TITLE
could you help me to add an item functionality to the example of invoices?

### ISSUE THREAD

**Issue by hulaigann** [perak/kitchen-site#294]
in such way that when selecting  a new item from a selection field  in the invoice detail , the description and price of the invoice detail fields could be  filled automatically  with their corresponding values of the  item collection. Thanks

**Comment by perak** [comment]
@hulaigann hey, sorry for late answer. Did you solved the problem?

**Comment by hulaigann** [comment]
Hi Petar.
I found a way  of doing it.  Basically writing all the code  into the
events_code label  of the definition's page . So the user can  populates
automatically  the fields associated to the item (price and description) of
the invoice detail form when he selects the item from the combo .

"events_code": "'change select[name=itemId]': function(e, t) {
  var prodId = $(e.target).val();

  p = Items.findOne(prodId);
  $('input.form-control[name=description]').val(p.description);
  $('input.form-control[name=price]').val(p.price);

}"
I don't know if there is an  easier  or shortest way to do that. In such
case please make me know. I will apreciate a lot.
I take this opportunity to congratulate you on this great work, and offer
my assistance on those things that can bring you.
(Sorry for my english , my native language is spanish)

2016-04-27 12:47 GMT-06:00 Petar Korponaić <notifications@github.com>:

**Comment by perak** [comment]
@hulaigann currently there is not better way, but it will be soon. Working on a new GUI and improving CLI... just a little bit more patience :)

GUI Preview video here: https://www.youtube.com/watch?v=NBtFs1c4qhQ

:+1:

P.S. my English is far from perfect too :)
