### ISSUE TITLE
File not found during generation

### ISSUE THREAD

**Issue by jmblanc** [perak/kitchen-site#295]
Hello
I am using the widows zip to generate files. it seems that section.html and section.js are missing in blaze\ui\materialize\components\. I have copied from the directory templates\blaze\ui\bootstrap3\components.

and the generation finished correctly. 

I just want to point out that situation.

Thanks for your work

**Comment by perak** [comment]
@jmblanc thank you!

**Comment by perak** [comment]
@jmblanc (but we need to change css classes from bootstrap's "container", "row", "col-lg-12" to corresponding materialize classes. I'm super-busy with other things, can you do it? (to find out which classes to put here)

**Comment by jmblanc** [comment]
I can, but I am not familiar with bootstrap and materalize, and at that time i did not understand what you mean. maybe in a few days, that can be better.

**Comment by jmblanc** [comment]
ok, i was thinking, this was concerning several files, but only is modified
, just need to chandeg : "col-lg-12" to "col s12". (maybe "col m12" can be chosen, but this applis only on large screen).

[components.zip](https://github.com/perak/kitchen-site/files/243085/components.zip)

**Comment by perak** [comment]
@jmblanc thank you! :+1:

I added it to template and will be available in next version.

<img width="1552" alt="screen shot 2016-04-29 at 9 29 02 pm" src="https://cloud.githubusercontent.com/assets/5630814/14927348/814d43c4-0e51-11e6-975d-d07c48f3bb78.png">
