### ISSUE TITLE
When updating emailadresse - verified information is lost

### ISSUE THREAD

**Issue by adnoh** [perak/kitchen-site#297]
When updating a User Emailadress it calls the Server Method **updateUserAccount** in which you set:

```
if(userOptions.email) {
            var email = userOptions.email;
            delete userOptions.email;
            userOptions.emails = [{ address: email }];
}
```

which leads in not being able to login anymore. You should initiate a new verification Process or at least keep the "emails[0].verified"
A good time would be in **Users.before.update**

**Comment by perak** [comment]
@adnoh Great! Thanks! Fixed and will be available in next version.

**Comment by xauxatz** [comment]
I have struggled with this problem for half a day now and as far as I can see it is still not fixed.
Is there a workaround, anyone?

**Comment by perak** [comment]
@xauxatz Fixed now, but will be deployed in the next version. As a quick fix you can:

Edit your `~/.meteor-kitchen/templates/blaze/code/server_accounts.js` or `~/.meteor-kitchen/templates/react/code/server_accounts.js` and simply remove problematic part of the code:

```
		if(userOptions.email) {
			var email = userOptions.email;
			delete userOptions.email;
			userOptions.emails = [{ address: email }];
		}

```

Or, if you still want user to be able to change e-mail, you can do:

```
		if(userOptions.email) {
			var email = userOptions.email;
			delete userOptions.email;
			var userData = Users.findOne(this.userId);
                        var emailChanged = false;
                        if(userData.emails && !userData.emails.find(function(mail) { return mail.address == email; })) {
				userOptions.emails = [{ address: email }];
			}
		}
```

**Comment by xauxatz** [comment]
Great, many thanks!!
