### ISSUE TITLE
Issue while deploying to android phone

### ISSUE THREAD

**Issue by ferozearif** [perak/kitchen-site#298]
Hi Petar,

I used meteor-kitchen to build a simple application. After building and testing the application on my laptop, I tried to deploy the application to my android phone (Galaxy Note 3). The application gets created on the phone but when I run it, I get an iron router error (e.g events defined for a template not in existence). I did some googling and found that Iron router has some issues with Cordova and that perhaps was the reason I faced that issue. However I was not able to find a solution to the issue. Have you come across this issue? Can you suggest a solution? Kindly let me know.

Warm regards
Feroze
![screenshot_2016-05-11-12-45-19](https://cloud.githubusercontent.com/assets/4336965/15170391/c80c169e-1777-11e6-83eb-97403be1d9bc.png)

**Comment by perak** [comment]
@ferozearif I didn't have any troubles with iron router running on android (doing it on everyday basis). Can be something with your code. Is your app fully auto generated, or you added changes to the code? Also, try to cleam build the app - into new directory.

**Comment by ferozearif** [comment]
Thank you for the response Petar. I did make changes to the code. Since you
are saying that you are using this on a daily basis then the problem could
indeed be due to my changes :( . I will try to build the app in a clean
directory and see if that works on Android.

I'll get back to you if I face any issues. Thanks again for the response.

Warm regards
Feroze

**Comment by perak** [comment]
@ferozearif just curious, any news on this issue?

**Comment by ferozearif** [comment]
No problems Petar.

There was an error in the code. I had events defined for a template that
didn't exist. Once I fixed that issue, the app started working properly.

Thanks for checking in. I should've updated you. My apologies for not doing
so.

Warm regards
Feroze

**Comment by perak** [comment]
No problem, glad you solved it. Thanks. 👍
