### ISSUE TITLE
Changing basic templates.

### ISSUE THREAD

**Issue by 2huk** [perak/kitchen-site#299]
Is there some way to modify basic registration/login/etc. templates by modifying .json file , not final .js/html files of final meteor app?

**Comment by perak** [comment]
@2huk  currently, best you can is to put your templates into meteor-kitchen install dir/templates/blaze(or react)/bootstrap(or semantic or materialize)/pages/ name files for example my_login.html and then in .json set `"template": "my_login" `

**Comment by 2huk** [comment]
@perak thanks for answer. I could do what i wanted by manualy changing templates. However i think its good idea to implement this basic pages fully using your code generator. Especially in examples to make them more demonstrative. Whatever you project is great help fo beginners like me. You're doing great work.
