### ISSUE TITLE
A Collecction with an "array of items" field

### ISSUE THREAD

**Issue by hulaigann** [perak/kitchen-site#300]
For instance a customers CRUD with an array of phone numbers or e-mails
Is it  possible with meteorkitchen?

**Comment by perak** [comment]
@hulaigann It's possible. I'm typing from phone now, so in short: see "field" object's "input": "crud". Field should be of type "array". Form will show small dataview in it with possibility to choose/insert/update item.

I'l try to help you more tomorrow (1AM here), please let me know if you succeed in meantime.

**Comment by adnoh** [comment]
@hulaigann have a look at https://github.com/adnoh/mkt-Crud.git for an example.
@perak - feel free to include as a example if you like

**Comment by perak** [comment]
@adnoh thank you!

**Comment by hulaigann** [comment]
Thank you very much.  It is really powerfull.

**Comment by hulaigann** [comment]
@adnoh Very illustrative your example. Thanks
