### ISSUE TITLE
Integer & Float fields always required

### ISSUE THREAD

**Issue by rgstephens** [perak/kitchen-site#302]
If you define an Integer or Float field with `required` set to `false` this setting is ignored. When doing a submit, an Integer or Float must be provided even if the required is set to false.

          { "name": "memberNum", "title": "Member Number", "required": false, "type": "integer", "show_in_dataview": "false", "exportable": true }

**Comment by perak** [comment]
@rgstephens good catch. I'l add it into next version (preparing to publish 0.9.63 in monday).

**Comment by perak** [comment]
@rgstephens Fixed. 

Will be published in next version (v0.9.63) ~24 hours after now.

**Comment by rgstephens** [comment]
Just tested in 0.9.63 and this is now fixed.  Closing.  Thanks!
