### ISSUE TITLE
tooltips have disapearred

### ISSUE THREAD

**Issue by prisonier2** [perak/kitchen-site#303]
Hi,

Yesterday I started to use meteor-kitchen and there was tooltips in the GUI editor. Today they have disapeared.

I see that last commit on this repo was on april so I don't know if it is related to this repo ?

**Comment by perak** [comment]
@prisonier2 thanks.

That's mistake made by me yesterday when I published latest version. Will fix it later today.

**Comment by prisonier2** [comment]
Ok thanks Petar.

Your tool is A W E S O M E !

**Comment by perak** [comment]
@prisonier2 thank you! BTW, new better gui is coming soon, stay tuned!

**Comment by prisonier2** [comment]
I guess this is why the sitemap looks broken ?

**Comment by perak** [comment]
@prisonier2 sitemap is broken for other reason, but that will not be fixed - moving to new GUI in ~1 weeks (I hope).

**Comment by perak** [comment]
@prisonier2 fixed.

**Comment by prisonier2** [comment]
@perak  Thanks ;)
