### ISSUE TITLE
Access to GUI 2.0 ?

### ISSUE THREAD

**Issue by l1br3** [perak/kitchen-site#310]
Hello,

Can we have access to a beta of the awesome new gui ?

**Comment by perak** [comment]
@l1br3 I'll invite few guys to test new GUI next week, and you'll be one of them. :+1:

**Comment by l1br3** [comment]
Can't wait for that ! :+1:

**Comment by jkalbfeld** [comment]
Would it be possible to have an invite as well? :)

BTW, @perak If you need hosting on a VM, let me know what your needs are and I can donate one to the cause and also can set it up behind cloudflare so you have HTTPS (TLS) and DDoS protection.

I am running meteor kitchen at https://appdesign.thoughtwave.com/ and have been using it for a new idea I am working on.  You have literally saved me hours of work and frustration!!!

**Comment by perak** [comment]
@jkalbfeld if you are available to chat now, pls send me private message in gitter (I just tried and cannot access private room in gitter app from mobile phone)

**Comment by perak** [comment]
@l1br3 @jkalbfeld PM me via gitter private channel.

**Comment by quahfamili** [comment]
I would like to try the beta version of the new GUI. Was working on meteor-react for sometimes.

**Comment by mttstt** [comment]
I would like to try the beta version of the new GUI. Thanks

**Comment by l1br3** [comment]
I close this issue as GUI 2.0 is now available
