### ISSUE TITLE
Dropdown menus no longer working

### ISSUE THREAD

**Issue by pwachara** [perak/kitchen-site#312]
Hi @perak.  The dropdown menus no longer work.  This includes the User Accounts Example in which one can no longer logout after registering and login in.

Thank you for your efforts on this site.

Philemon

**Comment by perak** [comment]
@pwachara thank you. Will be fixed ASAP

**Comment by perak** [comment]
@pwachara quick fix is to downgrade nemo64:bootstrap package from `3.3.5_3` to `3.3.5_2`.

Inside your project directory run:
```
meteor add nemo64:bootstrap@=3.3.5_2
```

Adding hardcoded version to meteor-kitchen and will upload latest version in few minutes.

**Comment by pwachara** [comment]
Thanks @perak. The quick fix worked like a charm!

**Comment by DoubleChok** [comment]
Worked for me too! Thanks Duke.

P.S. Always stay a version behind from last release. That's my rule (sometimes I break it) : ) :+1: +1:
