### ISSUE TITLE
It is possible to subscribe two o more publications into a form

### ISSUE THREAD

**Issue by hulaigann** [perak/kitchen-site#313]
I try to use the CRUD resouce into a form  that contains two fields that are each one an array of objects.
 First CRUD is ok, but second doesn't fill the selector with the query associated.
It is possible something like that?
	"pages": [
						{
							"name": "insert",
							"type": "page",
							"query_name": ["phonetypes","emailtypes"],
							
							"components": [
								{
									"name": "insert_form",
									"title": "New Customer",
									"query_name": "customer",
									"mode": "insert",
									"submit_route": "clients",
									"cancel_route": "clients",
									"type": "form"
								}
							]
						},......}

Thanks

**Comment by perak** [comment]
Add query name to containing page's "related_queries" array.

**Comment by hulaigann** [comment]
Excellent!!!
"related_queries":[{"name":"phonetypes"},{"name":"emailtypes"}],
		
Thanks
