### ISSUE TITLE
Handling routes + Filter using Number Format

### ISSUE THREAD

**Issue by Kunal1985** [perak/kitchen-site#315]
Hi,

I have created a route which has a parameter customerId, but this is of type **number** in the collection definition. Because of this the query will not return back any result. Kindly suggest how to handle this situation.

Created route as below
{
                "name": "customers",
		"route_params": ["customerId"],
                "components": [{
                    "name": "view",
                    "type": "data_view",
                    "title": "Customers",
                    "text_if_empty": "No customer available for now.",
                    "query_name": "all_customers",
                    "query_params": [],
                    "views": ["gallery"]
                }]
}
Created filter as below
{
            "name": "all_customers",
            "collection": "customers",
            "filter": {
				"customerId": ":customerId"
			},
            "options": {}
} 

Thanks & Regards,
Kunal Kishor Ugale

**Comment by perak** [comment]
use `#` sign instead `:` in parameter definition in your query

**Comment by perak** [comment]
#customerId instead :customerId

**Comment by Kunal1985** [comment]
I tried this and still no results.
