### ISSUE TITLE
How to configure/use Meteor server side methods using Meteor-Kitchen

### ISSUE THREAD

**Issue by Kunal1985** [perak/kitchen-site#316]
Hi,

I am currently trying to convert my current application using Meteor-Kitchen.
I have a lot of meteor **methods server side** which handle all the server side logic on button click events using Meteor.call("someMethod") from the client side.
I could not find any reference on how this can be achieved. Kindly suggest.

Thanks & Regards,
Kunal Kishor Ugale

**Comment by l1br3** [comment]
Hi @Kunal1985, simply add your methods in server/methods folder and then call them in the client with Meteor.call().

You can do it everywhere in your code, eg. in helpers, rendered code, before/after hooks, etc ...

**Comment by perak** [comment]
@Kunal1985 use `copy_files` member of kitchen application's object.

```
"copy_files": [
  { "source": "path_to_your_file/your_file_name_1.js", "dest": "SERVER_METHODS_DIR/your_file_name_1.js" },
  { "source": "path_to_your_file/your_filename_2.js", "dest": "SERVER_METHODS_DIR/your_file_name_2.js" },

]
```

New GUI for meteor-kitchen is not finished yet, but I plan to publish it in next few days - old GUI is almost unusable, so my logic is better "unfinished" than "unusable" :D

**Comment by tripflex** [comment]
@Kunal1985 you could also try adding them in the GUI under "Startup" in server tab... i did and it appears to work for me (for now), until @perak can integrate editing server methods

**Comment by Kunal1985** [comment]
Closing this as not using Meteor Kitchen anymore, thanks all for the support.
