### ISSUE TITLE
Top level menu doesn't work anymore after meteor update

### ISSUE THREAD

**Issue by xauxatz** [perak/kitchen-site#317]
Today I made the following meteor update:
iron:middleware-stack      upgraded from 1.0.11 to 1.1.0
iron:router                upgraded from 1.0.12 to 1.0.13
natestrauser:font-awesome  upgraded from 4.6.1 to 4.6.3
nemo64:bootstrap           upgraded from 3.3.5_2 to 3.3.5_3

And now the top level menu in the right side (user settings, logout, etc.) suddenly doesn't work anymore. I tested in both Chrome and Firefox - same results.
When I click on the menu, nothing happens.
Any ideas?

**Comment by perak** [comment]
Please see recently closed issue related to the same problem

**Comment by perak** [comment]
https://github.com/perak/kitchen-site/issues/312

**Comment by xauxatz** [comment]
Yep, that fixed it. Thanks a lot!

**Comment by l1br3** [comment]
@xauxatz You should close the issue

**Comment by xauxatz** [comment]
Sorry...

**Comment by l1br3** [comment]
@xauxatz ;) no worries that's the community power !
