### ISSUE TITLE
error libgcc_s_dw2-1.dll

### ISSUE THREAD

**Issue by servatj** [perak/kitchen-site#334]
when i try to use meteor-kitchen on Window 7, i'm using 0968 version, it's fail to work becacuse libgcc_s_dw2-1.dll is missing.

how can i use meteor-kitchen last version on Window 7?

**Comment by perak** [comment]
I dynamicaly linked libraries somehow instead staticaly. Will be fixed in the next version.

**Comment by servatj** [comment]
Ok thank you!

**Comment by perak** [comment]
@servatj Fixed - just install again. 

There is windows installer now: http://www.meteorkitchen.com/install/install_win.exe
