### ISSUE TITLE
Customize text in change_pass template

### ISSUE THREAD

**Issue by denisdpc** [perak/kitchen-site#335]
I'd like to know if is possible to customize texts that are generated in change_pass template or use some internationalization configuration.
I could adapt the texts manually in generated template, but this required that I make the same process  every time the project is updated.
Thanks !

**Comment by perak** [comment]
@denisdpc currently it is not possible, but you can copy generated register.js and register.html files into your source directory, and then use kit hen's copy_files to instruct kitchen to copy (and overwrite) original files with your copies. Then you can edit that files and they will replace original on each run. (that is possible only if you use kitchen from terminal, not from gui)
