### ISSUE TITLE
Meteor-kitchen on raspberry

### ISSUE THREAD

**Issue by mttstt** [perak/kitchen-site#337]
Can be compiled the program in order to use on raspberry ?

**Comment by mikkelking** [comment]
The processor is not supported by the standard Meteor builds, but have a look here

https://meteor-universal.tumblr.com/

On 9/10/2016 10:11 AM, mttstt wrote:

Can be compiled the program in order to use on raspberry ?

**Comment by mttstt** [comment]
Thanks for the reply but I knew this.
I installed "Meteor universal fork - Meteor 1.3.4" and it is working properly.
The problem is "meteor-kitchen" on raspberry with the following error:  "./meteor-kitchen: cannot execute binary file: Formato eseguibile non valido".

**Comment by mikkelking** [comment]
My apologies, and of course that makes sense, you wouldn't have had this 
problem unless you were already there :)

Petar will need to provide a build of the kitchen to support the 
architecture. I'm not sure how hard that is, we'll have to wait for him 
to answer

**Comment by perak** [comment]
@mttstt @mikkelking I already compiled meteor kitchen on ARM architecture before, but I didn't know anyone will ever need that :) That's why I didn't provided distribution for ARM.

I will try to compile it again (need to install toolchain again etc...).

Until then, I am curious, please let me know what are you doing with "kitchen" running on embedded computer?

**Comment by mttstt** [comment]
perak, it is just for fun. But I think if the executable was available there could be other users concerned. If some instructions were available I could try autonomously to recompile the program. Thank you

**Comment by mttstt** [comment]
I tried to create a meteor-kitchen site on windows environment with the latest version of meteor 1.4. Then I copied the site on raspberry but raspberry has an old version of Meteor (Meteor universal fork - Meteor 1.3.4). Having found many packages out of date on rasperry, the meteor project did not work!

**Comment by perak** [comment]
You can try to build the app with kitchen's `--meteor-release 1.3.4` option, but I guess you need that version of meteor installed under windows (not sure would meteor automatically download and install older version the same as it does under linux amd mac).

**Comment by mttstt** [comment]
I had tried before this solution but without success, as I am not able to find an old Windows version of  meteor. In any case I'm not sure it's the correct solution, because the Windows version of meteor-kitchen uses the latest versions of packages (such as mongo), while the meteor raspeberry version uses  older packages.

**Comment by perak** [comment]
@mttstt maybe you can downgrade app.

After it is built with latest meteor version, do following:

- Remove `.meteor/local` directory
- Remove `.meteor/versions` file
- Edit `.meteor/release` and enter desired version `1.3.4`
- Edit `.meteor/packages` file: remove version info from all packages, for example:

Original file:
```
meteor-base@1.0.4             # Packages every Meteor app needs to have
mobile-experience@1.0.4       # Packages for a great mobile UX
mongo@1.1.12                   # The database Meteor supports right now
blaze-html-templates@1.0.4    # Compile .html files into Meteor Blaze views
reactive-var@1.0.10            # Reactive variable for tracker
jquery@1.11.9                  # Helpful client-side library
tracker@1.1.0                 # Meteor's client-side reactive programming library
```
You need to remove `@` symbol and version number after it, so your file should look like this:

```
meteor-base             # Packages every Meteor app needs to have
mobile-experience       # Packages for a great mobile UX
mongo                   # The database Meteor supports right now
blaze-html-templates    # Compile .html files into Meteor Blaze views
reactive-var            # Reactive variable for tracker
jquery                  # Helpful client-side library
tracker                 # Meteor's client-side reactive programming library
```

Now, try to execute app on Raspberry (and let me know if it explodes :D ).

**Comment by perak** [comment]
(all paths/files are inside your application directory)

**Comment by perak** [comment]
One more thing... to save your time (as I believe meteor takes a time to start on Raspberry), you can test this "manual & forced downgrade" by running the app on your computer (with whatever version of meteor) - if it starts, then this should work on your device too (but you need to repeat removing & editing files and then run the app on your device).

**Comment by mttstt** [comment]
Thank you for your suggestion. I'm trying right now. I'll let you know.

**Comment by perak** [comment]
👍

**Comment by mttstt** [comment]
Only one error:

=> Running Meteor from a checkout -- overrides project version (Meteor 1.4.1.2
[[[[[ ~/newDom ]]]]]
=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While selecting package versions:
   error: Conflict: Constraint ecmascript@0.5.7 is not satisfied by ecmascript 0.4.6_1.
   Constraints on package "ecmascript":
   * ecmascript@=0.4.6_1 <- top level
   * ecmascript@0.5.7 <- shell-server 0.1.1
=> Your application has errors. Waiting for file change.

**Comment by perak** [comment]
@mttstt I'm just curious: did you solved that last error and executed app finally?

**Comment by mttstt** [comment]
I am working on it. I have a question : is "shell-server" package mandatory for the site created with meteor-kitchen ? It give me some problem, can I remove it ?

**Comment by mttstt** [comment]
With your instructions and without the package "shell-server", it works on Raspberry !
Thanks

**Comment by perak** [comment]
👯
