### ISSUE TITLE
Unable to Build project

### ISSUE THREAD

**Issue by pwachara** [perak/kitchen-site#343]
I am getting the error below.

Executing: build
You have run Meteor as root. Your permissions in your app directory will be
incorrect if you ever attempt to perform any Meteor tasks as your non-root
user. You probably didn't want this, but you can fix it by running the
following from the root of your project:
sudo chown -Rh .meteor/local

**Comment by perak** [comment]
@pwachara use latest meteor-kitchen with following switch: --unsafe-perm

That is actually new "feature" of meteor (not meteor-kitchen) - you are warned if meteor is called as root user.

**Comment by mttstt** [comment]
Now the kitchen-site is not working on windows:
`Executing: build
You have run Meteor as root. Your permissions in your app directory will be
incorrect if you ever attempt to perform any Meteor tasks as your non-root
user. You probably didn't want this, but you can fix it by running the
following from the root of your project:
sudo chown -Rh .meteor/local`

**Comment by pwachara** [comment]
Hi Perak.  I am unable to Build & Download which is what I normally do as I am using Windows.  The error persists and eventually exits with Code No. 255

**Comment by pwachara** [comment]
@perak I have attached the error file below.  Hopefully it will help you with faster resolution of the issue.

[meteor_kitchen_error.txt](https://github.com/perak/kitchen-site/files/601310/meteor_kitchen_error.txt)

Thanks for your effort so far.

**Comment by perak** [comment]
@pwachara sorry for late answer. Problem is that `--unsafe-perm` option is new in Meteor (along with Meteor's restriction for root user), so in order to build application you need latest version of meteor. I am not sure does Meteor for windows support this thing, but it should.

**Comment by perak** [comment]
This issue is not related to "meteor-kitchen" (it is related with "meteor" and OS file access permissions), so closing this issue.
