### ISSUE TITLE
Problem with meteor-kitchen on Windows

### ISSUE THREAD

**Issue by mttstt** [perak/kitchen-site#344]
The initial template "Minimal: with user account system" does not work anymore on Windows.
- Meteor V1.4.2
- Meteor-kitchen V0.9.71

Is this the problem? https://github.com/meteor/meteor/issues/7958

LOG:

_`Created a new Meteor app in './test2/'.

To run your new app:
  cd ./test2/
  meteor

If you are new to Meteor, try some of the learning resources here:
  https://www.meteor.com/learn

Changes to your project's package version selections:

autopublish  removed from your project
insecure     removed from your project

insecure: removed dependency
autopublish: removed dependency
 => Errors while adding packages:

While loading package momentjs:moment@2.15.2:
error: Command failed:
C:\Users\Sonia\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\bin\npm.cmd
rebuild --update-binary
node-pre-gyp ERR! Tried to download:
https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v46-win32-ia32.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.14 and
node@4.6.1 (node-v46 ABI) (falling back to source compile with node-gyp) 
Traceback (most recent call last):
File
"C:\Users\Sonia\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-gyp\gyp\gyp_main.py",
line 16, in <module>
sys.exit(gyp.script_main())
File
"C:\Users\Sonia\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-gyp\gyp\pylib\gyp\__init__.py",
line 545, in script_main
return main(sys.argv[1:])
File
"C:\Users\Sonia\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-gyp\gyp\pylib\gyp\__init__.py",
line 538, in main
return gyp_main(args)
File
"C:\Users\Sonia\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-gyp\gyp\pylib\gyp\__init__.py",
line 523, in gyp_main
generator.GenerateOutput(flat_list, targets, data, params)
File
"C:\Users\Sonia\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py",
line 2003, in GenerateOutput
sln_projects, project_objects, flat=msvs_version.FlatSolution())
File
"C:\Users\Sonia\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py",
line 1762, in _GatherSolutionFolders
return _DictsToFolders('', root, flat)
File
"C:\Users\Sonia\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py",
line 1715, in _DictsToFolders
for folder, contents in bucket.iteritems():
AttributeError: 'MSVSProject' object has no attribute 'iteritems'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit
(C:\Users\Sonia\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit
(internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command
"C:\\Users\\Sonia\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe"
"C:\\Users\\Sonia\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\node-gyp\\bin\\node-gyp.js"
"configure" "--fallback-to-build"
"--module=C:\\Users\\Sonia\\AppData\\Local\\.meteor\\packages\\momentjs_moment\\2.15.2\\npm\\node_modules\\.temp-jjxk4j\\node_modules\\fsevents\\lib\\binding\\Release\\node-v46-win32-ia32\\fse.node"
"--module_name=fse"
"--module_path=C:\\Users\\Sonia\\AppData\\Local\\.meteor\\packages\\momentjs_moment\\2.15.2\\npm\\node_modules\\.temp-jjxk4j\\node_modules\\fsevents\\lib\\binding\\Release\\node-v46-win32-ia32"
gyp ERR! cwd
C:\Users\Sonia\AppData\Local\.meteor\packages\momentjs_moment\2.15.2\npm\node_modules\.temp-jjxk4j\node_modules\fsevents
gyp ERR! node -v v4.6.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute
'C:\Users\Sonia\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\bin\node.exe
C:\Users\Sonia\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-gyp\bin\node-gyp.js
configure --fallback-to-build
--module=C:\Users\Sonia\AppData\Local\.meteor\packages\momentjs_moment\2.15.2\npm\node_modules\.temp-jjxk4j\node_modules\fsevents\lib\binding\Release\node-v46-win32-ia32\fse.node
--module_name=fse
--module_path=C:\Users\Sonia\AppData\Local\.meteor\packages\momentjs_moment\2.15.2\npm\node_modules\.temp-jjxk4j\node_modules\fsevents\lib\binding\Release\node-v46-win32-ia32'
(1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous>
(C:\Users\Sonia\AppData\Local\.meteor\packages\momentjs_moment\2.15.2\npm\node_modules\fsevents\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose
(internal/child_process.js:829:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit
(internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command
"C:\\Users\\Sonia\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe"
"C:\\Users\\Sonia\\AppData\\Local\\.meteor\\packages\\momentjs_moment\\2.15.2\\npm\\node_modules\\.temp-jjxk4j\\node_modules\\fsevents\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp"
"install" "--fallback-to-build"
node-pre-gyp ERR! cwd
C:\Users\Sonia\AppData\Local\.meteor\packages\momentjs_moment\2.15.2\npm\node_modules\.temp-jjxk4j\node_modules\fsevents
node-pre-gyp ERR! node -v v4.6.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.29
node-pre-gyp ERR! not ok 

npm ERR! Windows_NT 10.0.14393
npm ERR! argv
"C:\\Users\\Sonia\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe"
"C:\\Users\\Sonia\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js"
"rebuild" "--update-binary"
npm ERR! node v4.6.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! fsevents@1.0.14 install: `node-pre-gyp install
--fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fsevents@1.0.14 install script 'node-pre-gyp
install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm
installed.
npm ERR! If you do, this is most likely a problem with the fsevents
package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project
with:
npm ERR!     npm bugs fsevents
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fsevents
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
C:\Users\Sonia\AppData\Local\.meteor\packages\momentjs_moment\2.15.2\npm\node_modules\.temp-jjxk4j\npm-debug.log
node-pre-gyp ERR! Tried to download:
https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v46-win32-ia32.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.14 and
node@4.6.1 (node-v46 ABI) (falling back to source compile with node-gyp) 
Traceback (most recent call last):
File
"C:\Users\Sonia\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-gyp\gyp\gyp_main.py",
line 16, in <module>
sys.exit(gyp.script_main())
File
"C:\Users\Sonia\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-gyp\gyp\pylib\gyp\__init__.py",
line 545, in script_main
return main(sys.argv[1:])
File
"C:\Users\Sonia\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-gyp\gyp\pylib\gyp\__init__.py",
line 538, in main
return gyp_main(args)
File
"C:\Users\Sonia\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-gyp\gyp\pylib\gyp\__init__.py",
line 523, in gyp_main
generator.GenerateOutput(flat_list, targets, data, params)
File
"C:\Users\Sonia\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py",
line 2003, in GenerateOutput
sln_projects, project_objects, flat=msvs_version.FlatSolution())
File
"C:\Users\Sonia\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py",
line 1762, in _GatherSolutionFolders
return _DictsToFolders('', root, flat)
File
"C:\Users\Sonia\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py",
line 1715, in _DictsToFolders
for folder, contents in bucket.iteritems():
AttributeError: 'MSVSProject' object has no attribute 'iteritems'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit
(C:\Users\Sonia\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit
(internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command
"C:\\Users\\Sonia\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe"
"C:\\Users\\Sonia\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\node-gyp\\bin\\node-gyp.js"
"configure" "--fallback-to-build"
"--module=C:\\Users\\Sonia\\AppData\\Local\\.meteor\\packages\\momentjs_moment\\2.15.2\\npm\\node_modules\\.temp-jjxk4j\\node_modules\\fsevents\\lib\\binding\\Release\\node-v46-win32-ia32\\fse.node"
"--module_name=fse"
"--module_path=C:\\Users\\Sonia\\AppData\\Local\\.meteor\\packages\\momentjs_moment\\2.15.2\\npm\\node_modules\\.temp-jjxk4j\\node_modules\\fsevents\\lib\\binding\\Release\\node-v46-win32-ia32"
gyp ERR! cwd
C:\Users\Sonia\AppData\Local\.meteor\packages\momentjs_moment\2.15.2\npm\node_modules\.temp-jjxk4j\node_modules\fsevents
gyp ERR! node -v v4.6.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute
'C:\Users\Sonia\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\bin\node.exe
C:\Users\Sonia\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-gyp\bin\node-gyp.js
configure --fallback-to-build
--module=C:\Users\Sonia\AppData\Local\.meteor\packages\momentjs_moment\2.15.2\npm\node_modules\.temp-jjxk4j\node_modules\fsevents\lib\binding\Release\node-v46-win32-ia32\fse.node
--module_name=fse
--module_path=C:\Users\Sonia\AppData\Local\.meteor\packages\momentjs_moment\2.15.2\npm\node_modules\.temp-jjxk4j\node_modules\fsevents\lib\binding\Release\node-v46-win32-ia32'
(1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous>
(C:\Users\Sonia\AppData\Local\.meteor\packages\momentjs_moment\2.15.2\npm\node_modules\fsevents\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose
(internal/child_process.js:829:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit
(internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command
"C:\\Users\\Sonia\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe"
"C:\\Users\\Sonia\\AppData\\Local\\.meteor\\packages\\momentjs_moment\\2.15.2\\npm\\node_modules\\.temp-jjxk4j\\node_modules\\fsevents\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp"
"install" "--fallback-to-build"
node-pre-gyp ERR! cwd
C:\Users\Sonia\AppData\Local\.meteor\packages\momentjs_moment\2.15.2\npm\node_modules\.temp-jjxk4j\node_modules\fsevents
node-pre-gyp ERR! node -v v4.6.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.29
node-pre-gyp ERR! not ok 

npm ERR! Windows_NT 10.0.14393
npm ERR! argv
"C:\\Users\\Sonia\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe"
"C:\\Users\\Sonia\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js"
"rebuild" "--update-binary"
npm ERR! node v4.6.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! fsevents@1.0.14 install: `node-pre-gyp install
--fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fsevents@1.0.14 install script 'node-pre-gyp
install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm
installed.
npm ERR! If you do, this is most likely a problem with the fsevents
package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project
with:
npm ERR!     npm bugs fsevents
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fsevents
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
C:\Users\Sonia\AppData\Local\.meteor\packages\momentjs_moment\2.15.2\npm\node_modules\.temp-jjxk4j\npm-debug.log

*** Meteor Kitchen v0.9.71 ***

Source code generator for Meteor.js - www.meteorkitchen.com

Copyright (c) Petar Korponaić

<petar.korponaic@gmail.com>

Reading input file... 
Executing "meteor create ./test2/"...
Creating directory structure...
Checking installed packages...
Executing "meteor remove insecure autopublish"...
Checking installed packages...
Executing "meteor add accounts-password accounts-base http email spiderable ejson random iron:router fortawesome:fontawesome matb33:collection-hooks perak:user-roles copleykj:livestamp less nemo64:bootstrap@=3.3.5_2 reactive-dict momentjs:moment rajit:bootstrap3-datepicker mizzao:bootboxjs"...
Creating router...
Using theme "bootswatch-flatly"...
Copying theme files...
Creating stylesheet...
Creating layout...
Creating zone "free_zone"...
Creating zone "public_zone"...
Creating component "left_menu"...
Creating component "right_menu"...
Creating page "home_public"...
Creating component "home_jumbotron"...
Creating page "login"...
Creating page "register"...
Creating page "forgot_password"...
Creating page "reset_password"...
Creating zone "private_zone"...
Creating component "left_menu"...
Creating component "right_menu"...
Creating page "home_private"...
Creating page "user_settings"...
Creating component "side_menu"...
Creating page "profile"...
Creating component "edit_form"...
Creating page "change_pass"...
Creating page "logout"...
Copying files...
Calculating checksums...
Removing junk files...
Removing junk directories...

Generator finished._
`

**Comment by mttstt** [comment]
With the last version the issue is resolved.

**Comment by perak** [comment]
:+1:
