### ISSUE TITLE
Multiply user roles

### ISSUE THREAD

**Issue by silkroad-ch** [perak/kitchen-site#345]
Hi, Perak,

I will have four roles, admin, manager, owner and contractor. If I use current meteor account, when users register, they all go to user collection. Each user will have detail profile, it might be good idea to have a collection for each role. How can I achieve this in kitchen-site? I am thinking about having a role check box on the registration page, when user register it, based on the role they select, their data can then be inserted to a role collection.  If I have a registration form component, where should I put the mongo insert code ? do I need other code? Thanks.

**Comment by mikkelking** [comment]
@silkroad-ch Have a look at 
https://github.com/hharnisc/meteor-accounts-admin-ui-bootstrap-3

There is a demo app which manages roles, in line with the way it 
currently works. You should be able to integrate that code and packages 
into your project quite easily.

Mike
