### ISSUE TITLE
Multiple 'items' for a Collection

### ISSUE THREAD

**Issue by jvp** [perak/kitchen-site#348]
Is there a way to have multiple 'items' collections in one collection.

E.g. in the invoices example if one Invoice would have invoice_items (as in example) and invoice_text_items, where text_items would be some kind of simple text structure.

I've tried this kind of setup based no invoices example app but the invoice details page only renders the first 'items' collection.

-jvp

**Comment by jvp** [comment]
Anyone?

**Comment by perak** [comment]
@jvp are you trying to make two tabs in invoice details? (one tab showing items, another tab showing text_items?). Similar as in https://example-subpages.meteorfarm.com/cool_page/sub_page_b/sub_page_b_1

?

**Comment by jvp** [comment]
I'll try the two-tab solution.

Thanks.
