### ISSUE TITLE
Kitchen site does not work anymore?

### ISSUE THREAD

**Issue by mttstt** [perak/kitchen-site#349]
The site does not work anymore.
I am not able open anymore my application, when I click on the application name.
I have the following error:

Uncaught ReferenceError: merge is not defined(…)

**Comment by perak** [comment]
@mttstt Fixed. Deploying in few minutes...

**Comment by perak** [comment]
@mttstt Fixed.

**Comment by perak** [comment]
@mttstt please confirm if everything works normally now.

**Comment by mttstt** [comment]
Ok now it is working. Thanks
