### ISSUE TITLE
error on cli install

### ISSUE THREAD

**Issue by sembrador** [perak/kitchen-site#351]
Hi! several days ago I got this error trying to update cli mac & linux.

> curl http://www.meteorkitchen.com/install | /bin/sh
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   193  100   193    0     0    340      0 --:--:-- --:--:-- --:--:--   340
> /bin/sh: line 1: html: No such file or directory
> /bin/sh: line 2: syntax error near unexpected token `<'
> 'bin/sh: line 2: `<head><title>301 Moved Permanently</title></head>

I appreciate your help
Thanks

**Comment by perak** [comment]
Ooops, moved to https://www.meteorkitchen.com/install

**Comment by perak** [comment]
Fixed.

**Comment by the4tress** [comment]
I just did a fresh install and got a similar error:

```
[dev@dev ~]$ curl https://www.meteorkitchen.com/install | /bin/sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2151    0  2151    0     0   1482      0 --:--:--  0:00:01 --:--:--  1482
Installing "Meteor Kitchen" - Meteor application code generator
Detecting OS...
Detected OS: Linux
Downloading distribution...
curl: (3) <url> malformed
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>
Creating destination directory...
Unpacking...
tar (child): /tmp/install_linux.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

Changing line 39 to this worked as a temp fix:

`wget "$HOME_URL/install/$BUNDLE_FILENAME" -O "$TMP_DIR/$BUNDLE_FILENAME"  || exit $`

**Comment by perak** [comment]
@the4tress fixed now.
