### ISSUE TITLE
GUI : edit global_config/packages

### ISSUE THREAD

**Issue by jmblanc** [perak/kitchen-site#352]
Hi, 

ok the new Gui is really cool. Usually I was working on the JSON file. But at that time time, I plane to add a admin part to my site. The gui make it easier.

However you can not go down on pages dedicated to packages. Thus I change it in the JSON.

Thanks

**Comment by perak** [comment]
@jmblanc sorry, I don't understand. How do you mean "cannot go down on pages dedicated to packages"? ( maybe css issue? no scrollbar? )

**Comment by jmblanc** [comment]
sorry I was not clear, but scrollbar are missing. I've got more than 14 extra packages.

**Comment by perak** [comment]
Got it (must be you are using FF or Safari?). I will fix that asap.

**Comment by jmblanc** [comment]
I use Chrome on Linux.

**Comment by perak** [comment]
This old issue is fixed (long time ago) :) Closing...
