### ISSUE TITLE
Uncaught ReferenceError: collection is not defined

### ISSUE THREAD

**Issue by letoribo** [perak/kitchen-site#354]
i have defined collections in example-admin.json
"collections": [
		   {
				"name": "collection1"
			},
			{
				"name": "collection2"
			},
			{
				"name": "collection3"
			},
			{
				"name": "collection4"
			},
		],

in controller:

data: function() {
  var data = {
    params: this.params || {},
    admin_col3: collection3.find({}, {})
  };
  return data;
}

in Chrome console it gives:
Uncaught ReferenceError: collection3 is not defined

and in server console:
Exception from sub col3 id ZApmTiwL732kM
LZgn ReferenceError: collection3 is not defined

it is strange, 
show collections command in meteor mongo shows only collection4 

METEOR@1.4.2.3
Windows7

**Comment by perak** [comment]
@letoribo I cannot reproduce that. Can you please give me full .json ?

**Comment by letoribo** [comment]
{

	"application": {

		"title": "Example application",



		"theme": "bootswatch-paper",



		"roles": [ "admin", "user" ],

		"default_role": "user",

		"send_verification_email": true,



		"collections": [
		   {

				"name": "Tour"

			},
			{

				"name": "Operator"

			},
			{

				"name": "TourType"

			},
			{

				"name": "Accommodation"

			},

		],



		"queries": [

			{

				"name": "admin_users",

				"collection": "users",

				"filter": "{}"

			},

			{

				"name": "admin_user",

				"collection": "users",

				"filter": "{ \"_id\": \":userId\" }",

				"find_one": true

			},

			{

				"name": "users_null",

				"collection": "users",

				"filter": "{ \"_id\": null }",

				"find_one": true

			},

			{

				"name": "current_user_data",

				"collection": "users",

				"filter": "{ \"_id\": \"Meteor.userId()\" }",

				"find_one": true

			}

		],



		"public_zone": {

			"pages": [

				{

					"name": "home_public",

					"title": "",

					"components": [



					]

				},

				{ "name": "login", "template": "login" },

				{ "name": "register", "template": "register" },

				{ "name": "verify_email", "template": "verify_email", "route_params": ["verifyEmailToken"] },

				{ "name": "forgot_password", "template": "forgot_password" },

				{ "name": "reset_password", "template": "reset_password", "route_params": ["resetPasswordToken"] }

			],



			"components": [

				{

					"name": "left_menu",

					"type": "menu",

					"class": "nav navbar-nav",

					"dest_selector": "#menu",

					"items": [

						{ "title": "Home", "route": "home_public" }

					]

				},



				{

					"name": "right_menu",

					"type": "menu",

					"class": "nav navbar-nav navbar-right",

					"dest_selector": "#menu",

					"items": [

						{ "title": "Register", "route": "register" },

						{ "title": "Login", "route": "login" }

					]

				}

			]

		},



		"private_zone": {

			"pages": [

				{ "name": "home_private", "title": "Welcome {{userFullName}}!" },





				{

					"name": "admin",

					"roles": ["admin"],

					"pages": [

						{

							"name": "users",

							"components": [

								{

									"name": "view",

									"type": "data_view",

									"title": "Users",

									"text_if_empty": "No users yet",

									"query_name": "admin_users",

									"query_params": [],



									"fields": [

										{ "name": "profile.name", "title": "Name"},

										{ "name": "profile.email", "title": "E-mail"},

										{ "name": "roles", "title": "Role" }

									],



									"edit_route": "admin.users.edit",

									"edit_route_params": [

										{ "name": "userId", "value": "this._id" }

									],



									"details_route": "admin.users.details",

									"details_route_params": [

										{ "name": "userId", "value": "this._id" }

									]

								}

							],

							"pages": [

								{

									"name": "details",

									"route_params": ["userId"],

									"components": [

										{

											"name": "details_form",

											"type": "form",

											"mode": "read_only",

											"title": "User details",

											"query_name": "admin_user",

											"query_params": [],

											"fields": [

												{ "name": "profile.name", "title": "Name"},

												{ "name": "profile.email", "title": "E-mail", "type": "email" },

												{ "name": "roles", "title": "Role" }

											],

											"close_route": "admin.users",

											"back_route": "admin.users"

										}

									]

								},

								{

									"name": "edit",

									"route_params": ["userId"],

									"components": [

										{

											"name": "edit_form",

											"type": "form",

											"mode": "update",

											"title": "Edit user",

											"submit_route": "admin.users",

											"cancel_route": "admin.users",

											"query_name": "admin_user",

											"query_params": [],

											"fields": [

												{ "name": "profile.name", "title": "Name", "required": true },

												{ "name": "profile.email", "title": "E-mail", "type": "email", "input": "read-only" },

												{

													"name": "roles",

													"type": "array",

													"title": "Role",

													"input": "radio",

													"input_items": [

														{ "value": "user", "title": "User" },

														{ "value": "admin", "title": "Admin" },

														{ "value": "blocked", "title": "Blocked" }

													]

												}

											]

										}

									]

								}

							]

						}



					],



					"components": [

						{

							"name": "side_menu",

							"type": "menu",

							"class": "nav nav-stacked nav-pills",

							"items": [

								{ "title": "Users", "route": "admin.users" }

							]

						}

					]

				},



				{

					"name": "user_settings",

					"roles": ["user", "admin"],

					"pages": [

						{

							"name": "profile",

							"components": [

								{

									"name": "edit_form",

									"type": "form",

									"mode": "update",

									"title": "Edit your profile",

									"submit_route": "user_settings.profile",

									"query_name": "current_user_data",

									"query_params": [],

									"fields": [

										{ "name": "profile.name", "title": "Name", "required": true },

										{ "name": "profile.facebook", "title": "Facebook URL" },

										{ "name": "profile.google", "title": "Google+ URL" },

										{ "name": "profile.twitter", "title": "Twitter ID" },

										{ "name": "profile.website", "title": "Website URL" }

									]

								}

							]

						},



						{ "name": "change_pass", "template": "change_pass" }

					],



					"components": [

						{

							"name": "side_menu",

							"type": "menu",

							"class": "nav nav-stacked nav-pills",

							"items": [

								{ "title": "Profile", "route": "user_settings.profile" },

								{ "title": "Change password", "route": "user_settings.change_pass" }

							]

						}

					]

				},



				{ "name": "logout", "template": "logout" }

			],



			"components": [

				{

					"name": "left_menu",

					"type": "menu",

					"class": "nav navbar-nav",

					"dest_selector": "#menu",

					"items": [

						{ "title": "Home", "route": "home_private", "icon_class": "fa fa-home" }

					]

				},

				{

					"name": "right_menu",

					"type": "menu",

					"class": "nav navbar-nav navbar-right",

					"dest_selector": "#menu",

					"items": [

						{ "title": "Admin", "route": "admin", "icon_class": "fa fa-wrench" },



						{

							"title": "{{userEmail}}",

							"items": [

								{ "title": "Settings", "route": "user_settings" },

								{ "title": "Logout", "route": "logout" }

							],

							"icon_class": "fa fa-cog"

						}

					]

				}

			]

		}

	}

}

**Comment by perak** [comment]
@letoribo that's it - please write collection names **lowercase** ewerywhere in the .json and that will work 

(but this is still a bug - kitchen should deal with this).

**Comment by letoribo** [comment]
still not work.
i have absolutely identic routes and pages with the same functionality.
only difference is in the collection TourType is defined,
 but collection Accomodation - is not.
can i give you access to a bitbucket repo?

**Comment by perak** [comment]
Sure, let' me see

**Comment by letoribo** [comment]
what is your bitbucket nickname?

**Comment by perak** [comment]
`perak`

**Comment by letoribo** [comment]
please paste this in console:
Meteor.call("makeMeAdmin", Meteor.userId());
in admin tab the first sidetab is working. the second is not.

**Comment by perak** [comment]
You have typo double/single `m`: `Accomodation` and `Accommodation`

**Comment by letoribo** [comment]
it is because of my bad English.
i corrected all occurrences of a typo, but the error persists.

Uncaught ReferenceError: Accomodation is not defined
    at ctor.data (accomodation_type_controller.js:33)

**Comment by perak** [comment]
@letoribo works for me, see screenshot

<img width="1439" alt="screen shot 2016-12-22 at 11 19 24 pm" src="https://cloud.githubusercontent.com/assets/5630814/21442272/2be45fec-c89d-11e6-8711-3101fd717946.png">

**Comment by letoribo** [comment]
good news!
please see
http://admin-react.herokuapp.com/
i added you to this repo to
thank you much!

**Comment by letoribo** [comment]
sorry.
https://admin-react.herokuapp.com/

it's not accessible via http, only https works.

**Comment by perak** [comment]
Great. BTW, register doesn't work.

**Comment by letoribo** [comment]
use yuchistyakov@gmail.com
password: asdfasdf
