### ISSUE TITLE
camelCase forced to snake_case in GUI 2.0

### ISSUE THREAD

**Issue by l1br3** [perak/kitchen-site#356]
Hi, in GUI 1.0 I was able to give field name in camelCase, now everytime I create a new field, it becomes sanke_cased which is very problematic as I must edit the source every time. 

[You can see it here](http://hpics.li/3856e52)

Thanks

**Comment by perak** [comment]
@l1br3 thanks. bug is already reported, will be fixed in next update.

**Comment by l1br3** [comment]
thanks

**Comment by perak** [comment]
@l1br3 fixed

**Comment by l1br3** [comment]
:+1:
