### ISSUE TITLE
How to handle large data sets with dataview component

### ISSUE THREAD

**Issue by anthonymanzo** [perak/kitchen-site#357]
Hi,
Possibly not an issue, but trying to create a subscription to a search, instead of an entire collection with the dataview component.
Right now, on the dataview all records are subscribed to in a collection I have (People, about 2000 records).
How can I keep the client from having to subscribe to the entire collection and still be able to do a search on the entire collection?
Should I just do a custom component?
Any help appreciated.
Thanks.

**Comment by perak** [comment]
@anthonymanzo this is old problem reported multiple times - meteor kitchen doesn't generate "paged" publication / subscription automatically. I plan to refactor generated code anyways (as code is little bit outdated because meteor changes over time).

But, I got idea how to make quick hack for this, maybe I'll be able to publish next update in Monday.

**Comment by anthonymanzo** [comment]
Hi Perak,
Thanks for the response.  What if I just wanted to only perform a query if there was a search done.  I tried this, but a blaze conditional in the data view is preventing the search input from being displayed if no records are returned.
-Tony


On Jan 5, 2017, at 2:54 PM, Petar Korponaić <notifications@github.com<mailto:notifications@github.com>> wrote:


@anthonymanzo<https://github.com/anthonymanzo> this is old problem reported multiple times - meteor kitchen doesn't generate "paged" publication / subscription automatically. I plan to refactor generated code anyways (as code is little bit outdated because meteor changes over time).

But, I got idea how to make quick hack for this, maybe I'll be able to publish next update in Monday.

**Comment by perak** [comment]
@anthonymanzo I already fixed this, but I was not able to publish latest version because other things I am adding are not finished yet. I promissed monday, but most likelly it will be friday. Sorry :)

**Comment by perak** [comment]
@anthonymanzo version 0.9.74 is deployed now. 

Here is how you can set server-side filtering:

**1. in your query, set filter like this:**

```
{ "name": ":searchExp" }
```
<img width="1437" alt="screen shot 2017-01-12 at 11 18 15 pm" src="https://cloud.githubusercontent.com/assets/5630814/21910704/7321fc58-d91d-11e6-9e49-ffdbcfbcfc37.png">

**2. In your DataView, in DataSource tab, set value for searchExp like this:**

```
new RegExp(Session.get('searchString'), 'i')
```
<img width="1438" alt="screen shot 2017-01-12 at 11 20 16 pm" src="https://cloud.githubusercontent.com/assets/5630814/21910757/ba0f01d8-d91d-11e6-88f6-9f864e2ce991.png">

**3. In your DataView, in Actions tab, in onRendered hook set "searchString" session variable**
Tracker will fire when search string is changed. 
```
this.autorun(function() {
	var searchString = pageSession.get("SEARCH_STRING_SESSION_VAR") || null;
	Session.set("searchString", searchString);
});
```
*Note: it's better if you use unique session key name for each dataview instead "searchString".*

<img width="1439" alt="screen shot 2017-01-12 at 11 25 05 pm" src="https://cloud.githubusercontent.com/assets/5630814/21910912/715cf7e6-d91e-11e6-9375-021721bb5f37.png">

That's it :)

*P.S. this is less-or-more a hack - I will make paged loading of data and server-side filtering by default in (near) future.*

**Comment by anthonymanzo** [comment]
Hi

This is great, but I have another problem (which I didn't mention) that prevents me from using the GUI - my code that escaped for things like mongo searches causes errors in the IDE.

I've attached a copy of my kitchen.json (but without all the dependent files) to show you what I'm talking about.

Basically, it works through the cli but not the gui...  If this is another patch off can I use the cli, or is that not updated with the latest code?

I also have a question about providing details on s3 file collections (bucket, access keys, etc) that I'll open on a separate thread.

I'm really looking forward to being able to use your gui to share this project, it has quite a bit of common features in it that I've been working on - REST authentication, stacked roles, typeahead and hopefully soon s3 assets.

Your project is a great asset to meteor, thanks again.?

Tony


________________________________

**Comment by perak** [comment]
@anthonymanzo I am curious to solve your problem, and I need your kitchen.json, but I cannot find it... where is attached?

**Comment by anthonymanzo** [comment]
Hi,
Here it is, sorry:

**Comment by perak** [comment]
@anthonymanzo still no attachment. Can you send me directly via e-mail: petar.korponaic@gmail.com ?

**Comment by xauxatz** [comment]
What is the status on pagination in dataviews?

**Comment by perak** [comment]
Pagination is added long time ago. Closing this issue.
