### ISSUE TITLE
C3 interaction

### ISSUE THREAD

**Issue by The-Edge-Malaysia** [perak/kitchen-site#358]
Hi!

I would like to have something like below:

user mouseover the data grid td, I can get the td key, and would like to focus the corresponding C3 pie chart slice, or vice versa.

I read C3 doc on chart.focus(slice1) where slice1 is the key/id, but I can't seems to call chart.focus from within meteor kitchen. is there a way?

**Comment by perak** [comment]
@The-Edge-Malaysia hi! Sorry for late answer. Where do you want to call `chart.focus`? From Template.events or... ?

**Comment by The-Edge-Malaysia** [comment]
I have a data view component which shares the same data as a c3 pie chart.

when I mouse over the data-view td, i would like to highlight the corresponding portion of the c3 pie chart, attached is the screenshot of the portion that I have mentioned.

Assuming that user mouse over the TD with the source named Edge, the corresponding pie slice representing Edge should be highlighted, i.e. focus.

wonder if this can be done

Thanks in advance

<img width="748" alt="screen shot 2017-01-13 at 12 10 14 pm" src="https://cloud.githubusercontent.com/assets/20800366/21918183/a6997bb2-d989-11e6-9cf1-8205b278d34f.png">

**Comment by perak** [comment]
@The-Edge-Malaysia how about this:

<img width="1438" alt="screen shot 2017-01-13 at 2 34 43 pm" src="https://cloud.githubusercontent.com/assets/5630814/21931760/80aa9ada-d99d-11e6-9b41-3f36ea88a2e5.png">

event arguments `e` and `t` are event and template. You can use event to access which element is under the mouse, e.g. `e.currentTarget` and use template to access any element inside this template e.g. `t.$("jQuery-selector-here")` or simply `$("jQuery-selector-here")` to access entire DOM (not only current template).

**Comment by The-Edge-Malaysia** [comment]
Thanks! Appreciate, will test out soonest.

Because the chart is SVG based, I was not able find the element
representing the relevant pie slice earlier.

Sure I Will try again, thanks!

**Comment by perak** [comment]
@The-Edge-Malaysia ah, now I understand... you need to access `chart` variable in order to call `focus`? OK, let me see...

**Comment by The-Edge-Malaysia** [comment]
Yes, correct. Thanks for helping

**Comment by perak** [comment]
@The-Edge-Malaysia OK, I got the solution:

I updated `perak:c3` package - now it exposes global variable `c3charts`.

**First** you need to update to latest `perak:c3` (v1.0.7). You can `meteor remove perak:c3` and `meteor add perak:c3` or simply clean build the application with meteor-kitchen.

**Second** your chart must have an id. In a template, in place where you inserted chart add id= attribute like this:

```
{{> c3 data=myChartData id="myChartId"}}
```

And now you can access it:

```
var chart = c3charts["myChartId"];
// now you can use API:
chart.focus(...
```

That's it. :)

**Comment by The-Edge-Malaysia** [comment]
hi!

Wonder if the Perak:C3 is bundled with updated C3 package? I was not able to do a stack bar, result is always as shown below. Wonder if theres anything I need to do further?

I noticed that the earlier perak:c3 was bundling with earlier version of C3 which has the stack bar bug.
code:

    var db = TypeByViewsCollection.find(
      {},
      {}).fetch();
		var group=_.pluck(db, "type");
    _.each(db, function(g) {
      cols.push([g.type, g.l50, g.l100,g.l500,g.l1000,g.l2000, g.l5000, g.l10000, g.l15000, g.l20000, g.l50000, g.g50000]);
    });
    cols=_.sortBy(cols, 'total').reverse();
    return {
      data: {
        columns: cols,
        type: 'bar',
				groups: [
					group
				]
      }, ......
<img width="224" alt="screen shot 2017-01-16 at 4 03 13 pm" src="https://cloud.githubusercontent.com/assets/20800366/21975102/a660e85a-dc05-11e6-9257-2250c005e1aa.png">
