### ISSUE TITLE
Missing field "custom_template" in GUI 2.0

### ISSUE THREAD

**Issue by l1br3** [perak/kitchen-site#359]
Hi, before I was able to specify a custom component but now with gui 2.0 I'm only allowed to create the component in the GUI but I prefer to use the old way and have my IDE hilighting my code :)

**Comment by perak** [comment]
Sorry, that will not work. The best I can is to allow specifying custom_template to be URL (not local path). In that case you'll need to serve your files via any http server (or use online IDE which exposes files via url).

**Comment by l1br3** [comment]
It actually works as I've got it in the JSON

**Comment by l1br3** [comment]
I precise that I'm running last version of kitchen CLI
