### ISSUE TITLE
Missing field "custom_data_code" in GUI 2.0

### ISSUE THREAD

**Issue by l1br3** [perak/kitchen-site#360]
I'm not able to edit the "custom_data_code" field wich give me the ability to transform data before serving it to the client.

It actually works as my app is still correctly generated but I'm not able to edit it.

**Comment by perak** [comment]
Are you talking about *Editing not implemented :(* in property editor? Yes, unfortunately editing is not implemented yet, but will be soon (got it as "red" marked item in my Trello).

**Comment by l1br3** [comment]
Yes sorry it was not clear but I'm speaking about that.
I'm going to manually edit the JSON as I need it for yesterday morning ;)

**Comment by perak** [comment]
<img width="730" alt="screen shot 2017-01-10 at 11 22 01 pm" src="https://cloud.githubusercontent.com/assets/5630814/21827383/a609a5be-d78b-11e6-917c-56c08b4f75da.png">

**Comment by perak** [comment]
Developers are first to buy time-machine ;)

**Comment by l1br3** [comment]
The very next thing lol.
If you want my advise, I think you should add it in the "code" tab, it won't be really enjoyable to edit it in the side bar ;)

**Comment by perak** [comment]
Sure thanks... all multi-line inputs are outside property editor

**Comment by l1br3** [comment]
GUI 2.0 is very very nice ! Many thanks for your work

**Comment by perak** [comment]
Thanks! Glad you like it. Will be even better - working on it 🚀

**Comment by perak** [comment]
(we are working on it :) )

**Comment by l1br3** [comment]
:+1: :+1: :+1: :+1:

**Comment by perak** [comment]
In next update (I hope in friday) se screenshot:

![screen shot 2017-01-10 at 11 28 57 pm](https://cloud.githubusercontent.com/assets/5630814/21827626/ccfe4cd2-d78c-11e6-82e7-0242ae474b24.png)

**Comment by l1br3** [comment]
Wow this would be awesome ! Does all the history is stored ?

**Comment by perak** [comment]
Last 100 edits, but maybe I'll increase - measuring memory usage.
