### ISSUE TITLE
Ironrouter 1.1.0 breaks it

### ISSUE THREAD

**Issue by thierrysikora** [perak/kitchen-site#362]
Hi, seems that meteor-kitchen doesn't work with the latest update of ironrouter (1.1.0) 
workaround :
meteor remove iron:router
meteor add iron:router@=1.0.13
Could you fix this?
Thanks

**Comment by perak** [comment]
@thierrysikora thanks, working on this...

**Comment by perak** [comment]
@thierrysikora looks like bug in iron-router: https://github.com/iron-meteor/iron-router/issues/1561

**Comment by perak** [comment]
I fixed iron-router version to 1.0.13 for now, and I will deploy latest version of meteor-kitchen in few hours.

Until then, quick fix is:
In following files:
`~/.meteor-kitchen/templates/blaze/code/app_simple.json`
`~/.meteor-kitchen/templates/blaze/code/app_accounts.json`

Add `@=1.0.13` to `iron:router` see screenshot:

<img width="1440" alt="screen shot 2017-01-15 at 9 52 36 pm" src="https://cloud.githubusercontent.com/assets/5630814/21966081/06a1beea-db6d-11e6-8e76-fc181c05894b.png">

**Comment by perak** [comment]
@thierrysikora please update kitchen-cli to latest `0.9.75`

**Comment by mttstt** [comment]
the last version 0.9.75 is not more compatibile with windows. Now I have the following error:

C:\Users\matte\Documents\GitHub\Domoticasite>meteor-kitchen domoticasite.json dir

*** Meteor Kitchen v0.9.75 ***
Source code generator for Meteor.js - www.meteorkitchen.com
Copyright (c) Petar Korponai─ç
<petar.korponaic@gmail.com>

Reading input file...
Executing "meteor create dir\"...
Impossibile trovare il percorso specificato.

Error: output directory not found "dir\".

**Comment by perak** [comment]
@mttstt are you sure that's not bug in your json? 

What happens if you exec:
```
meteor-kitchen --example-minimal dir
```
?

**Comment by mttstt** [comment]
I solved: there was a problem with meteor, I re-install it and now is working.
Thanks for support
