### ISSUE TITLE
User default role generated code

### ISSUE THREAD

**Issue by The-Edge-Malaysia** [perak/kitchen-site#364]
Hi!

I have generated my app with meteor kitchen then followed by manual coding to add/tweak functionalities.

and i realised that the default user role is wrong.

if I regenerate from meteor kitchen again, there are lots of manual work to get it working as of current build.

thus, would like to ask where is the code when user first registered, or first login via google that default the user role and save to user collection.

**Comment by perak** [comment]
@The-Edge-Malaysia in your application, please see `/server/server.js` function. There is `user.roles = [];`, you can add default role, e.g. `user.roles = ["user"];`

**Comment by The-Edge-Malaysia** [comment]
Thanks!

I keep looking at client side, haha
