### ISSUE TITLE
[question] www.meteorkitchen.com/login with github-account

### ISSUE THREAD

**Issue by jvp** [perak/kitchen-site#366]
I used to login into www.meteorkitchen.com with github account. That option seems to removed.

How can I access my projects in www.meteorkitchen.com now?

br. jvp

**Comment by perak** [comment]
@jvp I can transfer your old projects to your new user account. Please create one and give me your username. (I can do it ~5 hours after now, wjen I reach my computer).

**Comment by jvp** [comment]
Created account with username **jvp**.

Thanks.

**Comment by jvp** [comment]
Any progress on this yet?

**Comment by perak** [comment]
@jvp sorry, somehow I forgot... I'll do it just now (in few minutes)

**Comment by perak** [comment]
@jvp done. Please try and let me know.

**Comment by jvp** [comment]
ty
