### ISSUE TITLE
GUI vertical scroll issue 

### ISSUE THREAD

**Issue by thierrysikora** [perak/kitchen-site#367]
Hi,

I have a vertical scroll issue in the GUI (i guess with what you call codemirror) : when reaching the bottom of the page the top menu-bar disappears and there is no way to get it back.
<img width="754" alt="screen shot 2017-02-11 at 10 37 26" src="https://cloud.githubusercontent.com/assets/2978817/22852861/4e868fe0-f046-11e6-92d9-499378d2ea55.png">
Thx

**Comment by perak** [comment]
@thierrysikora which browser are you using?

**Comment by thierrysikora** [comment]
Chrome 56 on OSX - But same on windows

**Comment by perak** [comment]
@thierrysikora OK, I see... will be fixed in next version, I hope ~36 hours after now.

**Comment by perak** [comment]
This is fixed, so I'm closing this issue.
