### ISSUE TITLE
favicon.ico not loading, where to put tag

### ISSUE THREAD

**Issue by anthonymanzo** [perak/kitchen-site#370]
Hi, 
I want to use our orgs favicon, but I don't know where I can include the :
`<link rel="shortcut icon" href="favicon.ico">`
Also, without putting in the above code, I've used the "copy_files" kitchen json and moved the favicon.ico to the PUBLIC_DIR and PUBLIC_IMAGES_DIR, this didn't' work either.
Any ideas?
Thanks
Tony

**Comment by perak** [comment]
Copy to PUBLIC_DIR should work. BTW you can make <head><link rel=... ></head> anywhere - in any html file, meteor will automagically merge all head tags into one.

**Comment by perak** [comment]
`<head><link rel=...></head>` in any html file
