### ISSUE TITLE
mergeObjects function not defined

### ISSUE THREAD

**Issue by xauxatz** [perak/kitchen-site#372]
Hi - I've recently updated to the new meteorkitchen, and my code is now generated like this:

"submit": function(e, t) {
function submitAction(result, msg) {
   ...
   Router.go("company_info_results_page", mergeObjects(Router.currentRouteParams(), {}));
}

rather than this:

"submit": function(e, t) {
function submitAction(result, msg) {
   ...
   Router.go("company_info_results_page", {}));
}

What could have caused this change? An updated router package?
In any case, it gives an error that "mergeObjects" is undefined - even though the jsprim package is correctly installed.

**Comment by perak** [comment]
@xauxatz that was an issue, but should be solved. What is your meteor kitchen version? BTW, that function is from `/both/lib/object_utils.js`. It was renamed from `merge` to merge objects. 

Quick fix will be to add somewhere (visible to both server and client, e.g. into `/both/` something like `this.mergeObjects = merge;`

**Comment by xauxatz** [comment]
Meteor-kitchen is 0.9.78.
I placed a file with "this.mergeObjects=merge;" under /both/ but now it complains that "merge" is not defined :-(

**Comment by perak** [comment]
@xauxatz must be something wrong at your side - I got `mergeObjects` function in the code. 

Please check your `~/.meteor-kitchen/templates/blaze/code/object_utils.js`.

You can try to remove meteor kitchen installation and install again.

BTW, what OS are you using?

**Comment by xauxatz** [comment]
It is rather embarrassing. You were correct that something was messed up 
on my side.
Due to an error in the copied files - the object_utils, etc. did not get 
correctly generated.
Now it works - thanks and sorry for wasting your time.
