### ISSUE TITLE
Edit Meteor Kitchen file dynamically real-time during runtime on-the-fly

### ISSUE THREAD

**Issue by ihealthdavid** [perak/kitchen-site#373]
**Feature request**: Edit Meteor Kitchen file dynamically real-time during runtime on-the-fly
Basically, having all the UI ready on the front-end, and taking the application json from MongoDB.

**Background**:
I'm sure others have thought of this, but I couldn't find the discussion. As a prototyping tool, this would be the best scenario, even with any limitations. Further, I would like to use this on Cordova, especially since Cordova build times are long.

For Cordova, swapping the JS code execution would be useful for parts of the application, especially with hardware devices, as insecure it may be.

**Comment by ihealthdavid** [comment]
Similar request, though I'm not sure I support their approach on the implementation: https://github.com/perak/kitchen-cli/issues/18

**Comment by ihealthdavid** [comment]
I see @perak @adimasduvitra also wanted this feature back in Jul '15. Nice name: hot-kitchen
https://forums.meteor.com/t/meteor-kitchen-code-generator-for-meteor/914/43

**Comment by perak** [comment]
Hi @ihealthdavid will be added soon because I need it too: kitchen-gui will be able to host your application (your app will run and exposed to appname.meteorfarm.com - of course, only if you turn that "on") then when you hit "save" in the GUI, app will be updated instantly.

I am currently working on GUI and better React code generator, but until I deploy new version, you can make simple npm module which does that... Gi'me few moments, I'll write example code here:

**Comment by perak** [comment]
@ihealthdavid written from "head" (not tested), try and let me know:

```
const commandLineArgs = require("command-line-args");
const fs = require("fs");
const exec = require('child_process').exec;

const optionDefinitions = [
  { name: "input", alias: "i", type: String },
  { name: "output", alias: "o", type: String }
];

const args = commandLineArgs(optionDefinitions);

var runKitchen = function() {
	exec("meteor-kitchen " + args.input + " " + args.output, function(error, stdout, stderr) {
		if(error) {
			console.error(`exec error: ${error}`);
		}

		console.log(`stdout: ${stdout}`);
		console.log(`stderr: ${stderr}`);

	});
	observeChanges();
};

var observeChanges = function() {
	fs.watchFile(args.input, (curr, prev) => {
		if(curr.mtime != prev.mtime) {
			runKitchen();
		}
	});
};

observeChanges();
```

Usage:
```
hot-kitchen -i your_json_file.json -o your_output_dir
```

When you edit .json, kitchen should re-run automatically (hot code push :) ).

**Comment by perak** [comment]
@ihealthdavid

Added `-l` or `--live` option to meteor-kitchen CLI
