### ISSUE TITLE
Button title changes to "Please wait..."

### ISSUE THREAD

**Issue by xauxatz** [perak/kitchen-site#380]
In the meteorkitchen.json project, button names change to "Please wait..." when pushed.
How can I get the same behavior in my own project?

**Comment by perak** [comment]
Do you mean in your project built with meteor kitchen, or in your project built "manually"? 

That's done via bootstrap's `$(...).button("loading")` and `$(...).button("reset")` and button must have `data-loading-text="Loading..."` attribute. http://getbootstrap.com/javascript/#buttons-stateful
