### ISSUE TITLE
Missing dependency "Users" in collection

### ISSUE THREAD

**Issue by mukulhase** [perak/kitchen-site#382]
![screenshot from 2017-07-25 09-49-27](https://user-images.githubusercontent.com/9693405/28555629-b8275f70-711e-11e7-8e19-b2b107ee0a37.png)

**Comment by perak** [comment]
@mukulhase thanks for reporting issue, will be fixed in next release. :+1:

**Comment by perak** [comment]
@mukulhase fixed in `v0.9.88` (not deployed yet).

**Comment by perak** [comment]
@mukulhase just deployed `v0.9.88` :+1:
