### ISSUE TITLE
Help with setting MK query

### ISSUE THREAD

**Issue by Luq16** [perak/kitchen-site#384]
I am new to Meteor. I have been trying to publish and subscribe to a collection where it only return the current user image. I followed the MK upload example. When ever I set the query to this.userId or Meteor.userId(). It doesnt display anything. Thank you.
 See my queries bellow 
{
				"name": "gallary",
				"collection": "gallery",
				"filter": "{}",
				"options": "{}"
			},
			{
				"name": "gallary_empty",
				"collection": "gallery",
				"find_one": true,
				"filter": "{\"_id\":null}",
				"options": "{}"
			},
			{
				"name": "gallery_user",
				"collection": "gallery",
                                "find_one": true,
				"filter": "{\"_id\":\"this.userId\"}",
				"options": "{}"
			},
			{
				"name": "gallery_current_user",
				"collection": "gallery",
				"find_one": true,
				"filter": "{\"_id\":\"Meteor.userId()\"}",
				"options": "{}"
			}
		],

	{
					"name": "profile_page",
					"type": "page",
					"components": [
						{
							"name": "add_file",
							"type": "custom_component",
							"query_name": "gallery_user",
							"html": "<template name=\"TEMPLATE_NAME\">\n\t<h2>\n\t\tCOMPONENT_TITLE\n\t\t<button type=\"button\" class=\"btn btn-success pull-right new-file\">\n\t\t\t<span class=\"fa fa-plus\">\n\t\t\t</span>\n\t\t\tAdd file\n\t\t</button>\n\t</h2>\n\n\t<p>\n\t\tThis example application is built with <a href=\"http://www.meteorkitchen.com\">Meteor Kitchen</a> - source code generator for Meteor.js.\n\t\tSource code is <a href=\"https://github.com/perak/kitchen-examples/tree/master/example-upload\" target=\"_blank\">here</a>\n\t</p>\n\n\t<hr />\n\n\t{{#if QUERY_NAME}}\n\t\t<div class=\"row\">\n\t\t\t{{#each QUERY_NAME}}\n\t\t\t\t<div class=\"col-xs-12 col-sm-4 col-md-3\" style=\"padding: 10px;\">\n\t\t\t\t\t<h4>\n\t\t\t\t\t\t<a href=\"#\" class=\"delete-file pull-right\"><span class=\"fa fa-close\"></span></a>\n\t\t\t\t\t\t{{title}}\n\t\t\t\t\t</h4>\n\t\t\t\t\t{{#with file}}\n\t\t\t\t\t\t{{#if isImage}}\n\t\t\t\t\t\t\t<a href=\"{{url}}\" target=\"_blank\"><img src=\"{{url}}\" width=\"100%\"></a>\n\t\t\t\t\t\t{{/if}}\n\n\t\t\t\t\t\t{{#if isAudio}}\n\t\t\t\t\t\t\t<audio src=\"{{url}}\" width=\"100%\" controls=\"controls\"></audio>\n\t\t\t\t\t\t{{/if}}\n\n\t\t\t\t\t\t{{#if isVideo}}\n\t\t\t\t\t\t\t<video src=\"{{url}}\" width=\"100%\" controls=\"controls\"></video>\n\t\t\t\t\t\t{{/if}}\n\t\t\t\t\t{{/with}}\n\t\t\t\t</div>\n\t\t\t{{/each}}\n\t\t</div>\n\t{{else}}\n\t\t<div class=\"alert alert-info\">Gallery is empty :(</div>\n\t{{/if}}\n\n</template>\n\n",
							"js": "Template.TEMPLATE_NAME.events({\n\t\"click .new-file\": function(e, t) {\n\t\tRouter.go(\"home_private.insert\");\n\t},\n\n\t\"click .delete-file\": function(e, t) {\n\t\te.preventDefault();\n\t\tvar self = this;\n\t\tbootbox.dialog({\n\t\t\tmessage: \"Delete item?\",\n\t\t\ttitle: \"Delete\",\n\t\t\tanimate: false,\n\t\t\tbuttons: {\n\t\t\t\tsuccess: {\n\t\t\t\t\tlabel: \"Yes\",\n\t\t\t\t\tclassName: \"btn-success\",\n\t\t\t\t\tcallback: function() {\n\t\t\t\t\t\tCOLLECTION_VAR.remove({ _id: self._id });\n\t\t\t\t\t}\n\t\t\t\t},\n\t\t\t\tdanger: {\n\t\t\t\t\tlabel: \"No\",\n\t\t\t\t\tclassName: \"btn-default\"\n\t\t\t\t}\n\t\t\t}\n\t\t});\n\t\treturn false;\n\t}\n});\n\nTemplate.TEMPLATE_NAME.helpers({\n});\n\n",
							"jsx": "export class TEMPLATE_NAME extends Component {\n\n\tconstructor() {\n\t\tsuper();\n\t}\n\n\tcomponentWillMount() {\n\t\t/*TEMPLATE_CREATED_CODE*/\n\t}\n\n\tcomponentWillUnmount() {\n\t\t/*TEMPLATE_DESTROYED_CODE*/\n\t}\n\n\tcomponentDidMount() {\n\t\t/*TEMPLATE_RENDERED_CODE*/\n\n\t\tMeteor.defer(function() {\n\t\t\tglobalOnRendered();\n\t\t});\n\t}\n\n\trender() {\n\t\treturn (\n\t\t);\n\t}\n});",
							"gasoline": {
								"type": "gasoline",
								"templates": [
									{
										"name": "TEMPLATE_NAME",
										"type": "template"
									}
								]
							},
							"object_type": "custom_component"
						}
					],
					"pages": [
						{
							"name": "inset",
							"type": "page",
							"components": [
								{
									"name": "insert_file",
									"type": "form",
									"title": "insert_file",
									"query_name": "gallary_empty",
									"mode": "insert",
									"submit_route": "profile_page.inset",
									"cancel_route": "profile_page.inset",
									"object_type": "form"
								}
							]
						}
					]
				}
			]
		},

**Comment by perak** [comment]
Hi @Luq16

In your "gallery" collection, what is the field that keeps user's id? `_id` is primary key in gallery collection, so when you filter `_id: this.userId` resultset is naturally empty because there is no _id in gallery that matches user's id.

**Comment by Luq16** [comment]
Dear Perak,
Thank you for you quick response. I really appreciate it.
Now, in my gallery collection I have "ownerId" which matches user's id.
When I set *ownerId:this.userId* it still says gallery is empty. Thank you.
Luq16

**Comment by perak** [comment]
Hi @Luq16

Can you please copy and paste your input file again? But this time enclose it into triple backticks (three backticks, paste code, again three backticks). Thanks.

**Comment by perak** [comment]
Or, if you are using gui, simply give me url to input file.

**Comment by Luq16** [comment]
below is the link:

https://www.meteorkitchen.com/app_details/about/f2LSEBoC3h5JwBuF4

**Comment by Luq16** [comment]
below is the link:

https://www.meteorkitchen.com/app_details/about/f2LSEBoC3h5JwBuF4

Thanks.

**Comment by perak** [comment]
@Luq16 correct filter is:

```
{
  "ownerId": "Meteor.userId()"
}
```

Meteor kitchen will properly convert this server side (in publication) to `this.userId` and at the client it remains `Meteor.userId()`.

**Comment by perak** [comment]
By the way, I added this to the documentation (will be published with next version `0.9.84`).

**Comment by Luq16** [comment]
Thank you.
