### ISSUE TITLE
Custom Component - Uncaught ReferenceError: ReferencesPublicPageThumb is not defined

### ISSUE THREAD

**Issue by milanromic** [perak/kitchen-site#388]
In free_zone I inserted custom_component (as a second component) on page `references_public` and named it `thumb`. Generator generates (inside pages render):

`
<ReferencesPublicPageReferencesView data={this.props.data} routeParams={this.props.routeParams} />
<ReferencesPublicPageThumb data={this.props.data} routeParams={this.props.routeParams} />
`

but the second component got declaration like this:
`export class thumbs extends Component { ... }`

insted of this:
`export class ReferencesPublicPageThumb extends Component { ... }`

If I change it manually in generated code, works perfectly

**Comment by milanromic** [comment]
Also, `line feed` needs to be added before/after component declaration. This is useful after code has generated, to got good indent style.

Btw, I added third component and got `}export class some_custom_component extends Component { ... }`

**Comment by perak** [comment]
Fixed.
