### ISSUE TITLE
Bug: Duplicate code generated when using collection2 with react

### ISSUE THREAD

**Issue by mukulhase** [perak/kitchen-site#391]
![image](https://user-images.githubusercontent.com/9693405/31448266-a5f8e572-aec1-11e7-8fdc-74b416672c14.png)
Code generator generates it twice.
![image](https://user-images.githubusercontent.com/9693405/31448342-d62657f2-aec1-11e7-991c-997a4e97dd26.png)
Application here:
```
meteor-kitchen https://www.meteorkitchen.com/api/getapp/json/yAJ5chM2TA5wDBat2 listswith
```

**Comment by perak** [comment]
@mukulhase I know this is old issue, but it's solved now. Closing it.
