### ISSUE TITLE
DataView pagination

### ISSUE THREAD

**Issue by perak** [perak/kitchen-site#4]
DataView component should support pagination or "continous scroll" for large datasets

**Comment by baysao** [comment]
+1

**Comment by sfrobins** [comment]
+1

**Comment by perak** [comment]
Searching for best way to accomplish this...

Actually, what we need is to move search/filter to the server (into publish function), and subscribe passing skip & limit based on current page stored in Session (or similar).

Does someone implemented it by modifying code generated from current (non-paged) dataview and is ready to share some code? That will speed up things. TNX :)

**Comment by xauxatz** [comment]
+1

**Comment by ljack** [comment]
Found this https://www.discovermeteor.com/blog/smarter-publish-subscribe-with-smartquery/  when working with similar issue. Haven't had the time to try it yet, but propably will try it.

**Comment by KarimJedda** [comment]
is there any workaround?

**Comment by KarimJedda** [comment]
Ok guys I managed to do it:

server/pizza.js
Meteor.publish("get_pizza", function() {
	return Pizza.find({}, {});
});

client/home_controller.js
at the top of the file : Session.setDefault('pizzaCursor', 0);
and then in the data function:

data: function() {
		return {
			params: this.params || {},
			get_pizza: Pizza.find({}, {limit:20,skip:Session.get('pizzaCursor')})
		};
		/*DATA_FUNCTION*/
	},

This will allow to filter from the frontend by doing Session.set('pizzaCursor', 20); or Session.set('pizzaCursor', 40); etc.. 

The only issue now, is when I build a query on the kitchen site, and i put "skip":"Session.get..", this is copied into the server/pizza.js part. Is there any way to bypass it? I hope I'm clear

**Comment by perak** [comment]
@KarimJedda thanks! Unfortunately - there is no way to avoid it on server. But, I'll add this feature to kitchen (I'll add "paged" true/false property) and generated code will "know" what to do. But, don't expect it soon - I'm under workload these days.

**Comment by KarimJedda** [comment]
If you can quickly indicate how I could do it I'd be glad to help ;) 
Either way, I'll post a git repository with the default code for paginating stuff.
Thanks Perak

**Comment by quangmach** [comment]
+1 for pagination, really need it for my project but couldn't integrate other paging packages

**Comment by paplet** [comment]
+1

**Comment by rgstephens** [comment]
Thanks @KarimJedda, good approach

**Comment by xauxatz** [comment]
Any news on this item? I still need it....

**Comment by koernigo** [comment]
A couple of years have passed since this post was started. I don't believe this has been added to Kitchen, is that correct?  It would be very useful, since the current DataView component really only works for datasets that have a few hundred records max.  Thanks!

**Comment by perak** [comment]
Hi @koernigo 

Unfortunately, we still didn't added pagination. Reason for that is: we planned to completelly rewrite DataView and Form components so we didn't want to spend time on improving old ones. But, we didn't do it yet.

Pagination is what we really need too (we are adding pagination manually to all apps and that's pain in the ... fingers, I know).

Now watching this 4 year old (!) issue, I think it's time to add pagination and make our lives easier, so I put this as a top priority in our Trello board.

**Comment by perak** [comment]
@koernigo (not to mention others after several years :) ), pagination is added to DataView component and will be available in next version 0.9.100

**Comment by koernigo** [comment]
@perak Better late than never :-)

**Comment by perak** [comment]
@koernigo after almost exactly 4 years, pagination is finally added to DataView.

You need `meteor-kitchen` version `0.9.100`, then set DataView's `page_size` property (number of documents per page), default is `0` which means "no paging".

**Important** 

For existing applications generated with meteor-kitchen pre `0.9.100`, after you rebuild application with latest meteor-kitchen and with `page_size` set, you will need to update following packages in order paging to work properly:

Blaze applications:

```
meteor update perak:user-roles
```

React applications:

```
meteor npm update meteor-user-roles
```

That's it!

Screenshot:
<img width="1500" alt="screen shot 2018-06-18 at 11 58 09 am" src="https://user-images.githubusercontent.com/5630814/41533962-f7e5ff6e-72fc-11e8-8bc1-dd5d1e524cc0.png">

*OK... UI is not super-fancy, but will be improved in the future. Main issue was to generate proper publications and subscriptions without breaking backward compatibility*

Enjoy! 😃

**Comment by perak** [comment]
Closing this issue now! 🕺

**Comment by koernigo** [comment]
@prek Wow, looks like you had a busy weekend! Thanks much. Will try this out ASAP.

**Comment by koernigo** [comment]
@perak This works great, thank you!  My wish list for extensions would include to able do define page size interactively in the UI , go to first page and last page, show total number of pages etc.  But I don't want to be too greedy...;-)

**Comment by perak** [comment]
There is a lot of space for improvements here. I got more, for example:

- It would be nice to have "infinite scroll" instead pager (or better: choose between "scroll" or "pager").
- After insert (or update), if newly inserted (or updated) record is not positioned to current page then user doesn't see the record and have feeling that data is not written and that something is wrong.

Best I can is to promise that paging UI will be improved in the future...
