### ISSUE TITLE
consider supporting nested objects?

### ISSUE THREAD

**Issue by sfrobins** [perak/kitchen-site#40]
for instance:
{
  fname: 'Stewart',
  lname: 'Robinson',
  addr1: '124 H Street',
  addr2: '#81',
  city: 'Murray',
  state: 'UT',
  postalCode: '84107',
  contact:  { type: 'im', client: 'skype', user: 'sfrobins' }
}

I can find no way to get meteor kitchen to accept the contact object as a member of the parent JSON object.

**Comment by perak** [comment]
Yes you can, example collection definition:

```
{
  "name": "myCollection",
  "fields": [
    { "name": "fname", "title", "First name" },
    { "name": "lname", "title", "Last name" },
    { "name": "contact.type", "title", "Type" },
    { "name": "contact.client", "title", "Client" },
    { "name": "contact.user", "title", "Username" }
  ]
}
```

Let me know if it helps.

**Comment by sfrobins** [comment]
It works...  Thank you!  I tried that about a month ago and came to the conclusion that it did not work.  My bad...
