### ISSUE TITLE
Template_rendered_code	

### ISSUE THREAD

**Issue by mttstt** [perak/kitchen-site#400]
The field "Template_rendered_code" is not present in "form" and "data-views" GUI.

**Comment by perak** [comment]
@mttstt 

![screen shot 2017-11-30 at 10 04 31 am](https://user-images.githubusercontent.com/5630814/33422420-f2abf376-d5b5-11e7-861a-6532bd36cd73.png)

**Comment by mttstt** [comment]
Thanks :-)
