### ISSUE TITLE
Router.currentRouteParams validate JSON.stringify before calling JSON.parse

### ISSUE THREAD

**Issue by tripflex** [perak/kitchen-site#401]
Currently in the `Router.currentRouteParams` function, `JSON.parse` is being called without any validation on what is returned from `JSON.stringify`, thus, causing JS error preventing page from loading if value returned from `JSON.stringify` is undefined.  

Here's the current function which has the bug in it:
```js
Router.currentRouteParams = function() {
    var route = Router ? Router.current() : null;
    if(!route) {
        return {};
    }

    var params = {};
    for(var key in route.params) {
        params[key] = JSON.parse(JSON.stringify(route.params[key]));
    }

    return params;
};
```

This is what I had to modify the generated files with to fix this problem:

```js
Router.currentRouteParams = function() {
	var route = Router ? Router.current() : null;
	if(!route) {
		return {};
	}

	var params = {};
	for(var key in route.params) {

	    var stringify = JSON.stringify( route.params[key] );

	    if( stringify ){
            params[key] = JSON.parse( stringify );
        }
	}

	return params;
};
```

Please can you fix this ASAP, this is a show stopper for me

**Comment by perak** [comment]
Fixed long time ago, closing.
