### ISSUE TITLE
React generation needs router

### ISSUE THREAD

**Issue by PolywickStudio** [perak/kitchen-site#406]
W20171217-03:42:13.357(8)? (STDERR) ReferenceError: Router is not defined
W20171217-03:42:13.358(8)? (STDERR)     at router.js (server/controllers/router.js:1:1)
W20171217-03:42:13.359(8)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:343:9)
W20171217-03:42:13.359(8)? (STDERR)     at require (packages\modules-runtime.js:238:16)

**Comment by perak** [comment]
@PolywickStudio React generation creates router. Messages you have must be due some other errors in code. Did you generated blaze and then into same directory tried to generate react? If so, please generate into new empty dir.

Or, try to give ne steps to reproduce this issue.

BTW, what is your “meteor-kitchen —version”, “meteor —version” and which OS are you using?
