### ISSUE TITLE
Using a custom input to store data into collection.

### ISSUE THREAD

**Issue by paradoxewan** [perak/kitchen-site#407]
Hi there, i would like to use something like lukemadera:autoform-googleplace to use an autocomplete field with a collection. Are there any tutorials for doing such a thing?

Thanks

**Comment by perak** [comment]
@paradoxewan no related tutorials, but... since latest version of Meteor Kitchen, you can modify generted code and next execution of meteor-kitchen will not overwrite your manual modifications. So, you can add/remove/fine-tune entire app manually without loosing power of generator.

**Comment by perak** [comment]
(See release notes for v0.9.92 here: https://www.meteorkitchen.com/news )
