### ISSUE TITLE
GUI: pages should be foldable/collapsable in app builder

### ISSUE THREAD

**Issue by robmoggach** [perak/kitchen-site#42]
lots of scrolling required when you have lots of pages

I'd much rather see this:

    home_public
    login

than this:

    home_public
        components (1)
        query
        close_route_params (0)
        back_route_params (0)
        menus (0)
        pages (0)
        queries (0)
    login
        query
        components (0)
        close_route_params (0)
        back_route_params (0)
        menus (0)
        pages (0)
        queries (0)

**Comment by perak** [comment]
I agree

**Comment by perak** [comment]
Fixed :)
