### ISSUE TITLE
Hidden_fields stops insert from happening

### ISSUE THREAD

**Issue by maco144** [perak/kitchen-site#423]
Whenever I add a hidden fields to a form insert I am unable to submit the form. When I remove it the form works fine. 

The collection:
`			{
				"name": "props",
				"fields": [
					{ "name": "wager_size", "title": "Bet Size", "type": "integer", "min": 1, "required": true},
					{ "name": "roster_depth", "title": "Squad Size", "type": "integer", "min": 5, "required": true},
					{ "name": "end_date", "title": "Finishing Date", "type": "date", "format": "MM-DD-YYYY", "input": "datepicker", "required": true},
					{ 
					"name": "match_type", 
					"title": "Match Type", 
					"show_in_dataview": false,
					"show_in_insert_form": false,
					"show_in_update_form": false,
					"show_in_read_only_form": false
					}
				]
			}`

The insert form code:
`"components": [
{
"name": "makeprops",
"type": "form",
"mode": "insert",
"title": "Set Wager",
											
"query_name": "props_empty",
"query_params": [],

"submit_route": "match_private.match_roster",
"route_params": [],
"cancel_route": "match_private",
"hidden_fields": { "name": "match_type", "value": "propbet"}
										}
									]`

I have tried it with hidden_fields and hidden_field as well as using an array if using hidden_fields. When I use hidden_fields as an array the form doesnt submit and using both hidden_field it doesnt add the hidden field to the collection. I'd love to know how to get this to work!

**Comment by perak** [comment]
![f4cc7c03-c47d-4d39-9255-b22f7b1427fb](https://user-images.githubusercontent.com/5630814/47315897-17ca7880-d646-11e8-8d23-4c555ca2e4ab.png)

Sorry for low quality screenshot, I’m trying to answer but I’m on mobile phone

**Comment by maco144** [comment]
I believe my formatting is correct and fieldName and fieldValue are swapped for appropriate values. I cannot figure out why when I use hidden_fields as an array the form will not submit and if I use hidden_fields or hidden_field within my form component the form will submit but the hidden_fields name & value will not be set in the collection.

**Comment by perak** [comment]
@maco144 that “form do not submit” how it looks like? Do you have any error message?

**Comment by maco144** [comment]
No error from what I can tell. The form just wont submit, it stays there with the information filled out, and nothing happens to the mongo db either. I have tried with and without the collection field being defined, using multiple hidden fields, and other attempts. I cannot figure out why it doesn't work. I am using your example-invoices.json as reference and I dont see any difference in the code structure.

**Comment by perak** [comment]
Browser's console doesn't show any error?

**Comment by maco144** [comment]
@perak Thanks for your help I found out I was having an issue with a variable being undefined when being passed as "value". Issue solved, thanks again!
