### ISSUE TITLE
`home_private` on kitchen-site does not show introductory info

### ISSUE THREAD

**Issue by robmoggach** [perak/kitchen-site#48]
Unless a user installs the software before registering or logs out, there is no readily accessible documentation about how to install or upgrade the main package. The private site should mostly add to the base content instead of replacing it - it makes it seem like the site has changed unless you realize you're logged in and that changes the content on the Home link.

**Comment by perak** [comment]
Hum... in short: I don't understand :o

**Comment by robmoggach** [comment]
When i go to meteorkitchen.com anonymously I see Home and Getting Started with information about the package. When I login Home shows a link to my applications and getting started is gone.

**Comment by perak** [comment]
OK, now I understand. Will be fixed in next version (actually, I will add only "getting started", home will stay as is).

**Comment by perak** [comment]
Fixed :)
