### ISSUE TITLE
field type time input

### ISSUE THREAD

**Issue by AirJordan6811** [perak/kitchen-site#49]
What input type choose to edit time fields ?

**Comment by perak** [comment]
Try this:

```json
{
  "name": "the_time",
  "title": "The Time",
  "input": "text", 
  "type": "time",
  "format": "hh:mm:ss",
  "default": "now"
}
```

**Comment by AirJordan6811** [comment]
Thx @perak for quick and professional response! Where can I set the time to the European format. AM or PM must not be set with. 24 hour format must be displayed? The datepicker does not respond to the "language" setting "de" also

**Comment by perak** [comment]
It uses moment.js, so use format compatible with that. For european 24h format use:

"format": "H:mm:ss"

(or "HH:mm:ss")

**Comment by perak** [comment]
For dates, try setting global moment format in your server startup:

```
moment.locale('de');
```

I didn't tried that, let me know if it works please :)

**Comment by AirJordan6811** [comment]
The display in 24-hour format worked. But the moment.locale function does not work. In the server.js I registered it after Meteor.settings function.

**Comment by AirJordan6811** [comment]
Perhaps it´s not correct?
![momentjs](https://cloud.githubusercontent.com/assets/10909551/6351555/c23d4c66-bc3c-11e4-974e-aba052c95aa8.jpg)

**Comment by perak** [comment]
It is correct, problem is other thing - bootstrap datepicker package - it looks like it doesn't include localization code. Actually, this code is required somewhere in package:

```
;(function($){
	$.fn.datepicker.dates['de'] = {
		days: ["Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag", "Sonntag"],
		daysShort: ["Son", "Mon", "Die", "Mit", "Don", "Fre", "Sam", "Son"],
		daysMin: ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa", "So"],
		months: ["Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember"],
		monthsShort: ["Jan", "Feb", "Mär", "Apr", "Mai", "Jun", "Jul", "Aug", "Sep", "Okt", "Nov", "Dez"],
		today: "Heute",
		clear: "Löschen",
		weekStart: 1,
		format: "dd.mm.yyyy"
	};
}(jQuery));
```

But that will not fix your problem, generator doesn't generate "language" setting in datepicker's initialization code, you can find it in forms Template.rendered code and it should include "language" property:

```
		$(this).datepicker({
			autoclose: true,
			todayHighlight: true,
			todayBtn: true,
			forceParse: false,
			keyboardNavigation: false,
			format: format,
			language: "de-DE"
		});
```

Multilanguage support in "Meteor Kitchen" is already "on the radar", but don't expect it soon because I am too busy with my job...

**Comment by AirJordan6811** [comment]
I have made the change as suggested by you, but unfortunately without success. The calendar is still with English names for the days. I have also previously completely deleted the app directory and let the generator run through again.
![calendar](https://cloud.githubusercontent.com/assets/10909551/6353194/26167e78-bc48-11e4-8539-567ea4754428.jpg)

**Comment by perak** [comment]
So, you added this code somewhere, for example in `client/lib` directory:

```
    $.fn.datepicker.dates['de'] = {
        days: ["Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag", "Sonntag"],
...
```

And changed manually, in code generated by meteor-kitchen:

```
       $(this).datepicker({
            autoclose: true,
            todayHighlight: true,
            todayBtn: true,
            forceParse: false,
            keyboardNavigation: false,
            format: format,
            language: "de-DE"
        });
```

And it doesn't work? 

Try also `"language": "de"` instead "de-DE" in datepicker initialization.

If it still doesn't work, you may also try to clone datepicker package https://github.com/rajit/bootstrap3-datepicker.git locally in your generated program's `/packages/` directory, then `meteor remove rajit:bootstrap3-datepicker`, `meteor add rajit:bootstrap3-datepicker`, and change this package file:

`/packages/bootstrap3-datepicker/package.js` to something like this:

```
Package.describe({
  name: "rajit:bootstrap3-datepicker",
  git: "https://github.com/rajit/bootstrap3-datepicker.git",
  summary: "Meteor packaging of eternicode/bootstrap-datepicker for Bootstrap 3",
  "version": "1.3.1"
});

Package.onUse(function (api) {
  api.versionsFrom('0.9.0');
  api.use('jquery', 'client');
    
  api.addFiles('lib/bootstrap-datepicker/js/bootstrap-datepicker.js', 'client');
  api.addFiles('lib/bootstrap-datepicker/js/locales/bootstrap-datepicker.de.js', 'client');
  api.addFiles('lib/bootstrap-datepicker/css/datepicker3.css', 'client');
});
```

Of course, you still need to have "language": "de" in datepicker initialization code in your forms.

Let me know if it works.

**Comment by AirJordan6811** [comment]
Hmm, ok I have only change template from the code generator meteor-kitchen. But where in `client/lib` file must I change this?

    ;(function($){
    $.fn.datepicker.dates['de'] = {
        days: ["Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag", "Sonntag"],
        daysShort: ["Son", "Mon", "Die", "Mit", "Don", "Fre", "Sam", "Son"],
        daysMin: ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa", "So"],
        months: ["Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember"],
        monthsShort: ["Jan", "Feb", "Mär", "Apr", "Mai", "Jun", "Jul", "Aug", "Sep", "Okt", "Nov", "Dez"],
        today: "Heute",
        clear: "Löschen",
        weekStart: 1,
        format: "dd.mm.yyyy"
    };
}(jQuery));

**Comment by perak** [comment]
Add a new file and name it as you wish, for example "datepicker_fix.js" and
paste code there

**Comment by perak** [comment]
1. create file `datepicker_fix.js` in generated program's `/client/lib/` directory and paste this:

```
;(function($){
$.fn.datepicker.dates['de'] = {
    days: ["Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag", "Sonntag"],
    daysShort: ["Son", "Mon", "Die", "Mit", "Don", "Fre", "Sam", "Son"],
    daysMin: ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa", "So"],
    months: ["Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember"],
    monthsShort: ["Jan", "Feb", "Mär", "Apr", "Mai", "Jun", "Jul", "Aug", "Sep", "Okt", "Nov", "Dez"],
    today: "Heute",
    clear: "Löschen",
    weekStart: 1,
    format: "dd.mm.yyyy"
};}(jQuery));
```

2. In generated forms where datepicker is used, in `Template.XXX.rendered = function() { ... ` modify this:

```
$(this).datepicker({
            autoclose: true,
            todayHighlight: true,
            todayBtn: true,
            forceParse: false,
            keyboardNavigation: false,
            format: format,
            language: "de"
        });
```

(add `"language": "de"`) and that should work - but I didn't test it.

**Comment by AirJordan6811** [comment]
Thx @perak Good job! It works.

**Comment by perak** [comment]
@AirJordan6811 please let me know what you exactly did to make it work, that will help me modify/add that feature into meteor-kitchen.

**Comment by AirJordan6811** [comment]
@perak  I made it exactly as you wrote it ! Create in `/client/lib/` js file with function and add language "de" in template.

**Comment by perak** [comment]
OK. I'l create new datepicker package, include all languages there, and add "language" property to generator to automatically generate localized date/time formats.

Thanks for help :)
