### ISSUE TITLE
/lib64/libc.so.6: version `GLIBC_2.14' not found (required by meteor-kitchen)

### ISSUE THREAD

**Issue by noblestreet** [perak/kitchen-site#51]
Hi,
I have centos 6.6 running (command line only) and have tried to run meteor-kitchen but i get :
/lib64/libc.so.6: version `GLIBC_2.14' not found (required by meteor-kitchen)
I checked online but i cant find a solution to upgrade GLIBC. I have 2.12 running

**Comment by perak** [comment]
I'l compile it with older libc for you. Expect that in few hours.

**Comment by noblestreet** [comment]
Fantastic. Thanks for helping

Met vriendelijke groet / With kind regards,

Arnaud




Mobile
Address

 <http://www.noblestreet.eu/>
 
 <https://www.facebook.com/noblestreet.eu>	 <https://twitter.com/NOBLESTREET>	 <https://plus.google.com/u/0/b/118321742550701585480/118321742550701585480/about>
+31 (0) 6 24 444 266
Veenkade 48A
2513 EH Den Haag
Disclaimer This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. Internet communications are not secure and therefore Noblestreet does not accept legal responsibility for the contents of this message. Any views or opinions presented are solely those of the author and do not necessarily represent those of Noblestreet. If you are not the intended recipient or the person responsible for delivering to the intended recipient, be advised that you have received this mail in error and that any use is strictly prohibited.

**Comment by perak** [comment]
OK done. 

Just install meteor-kitchen again. 

Let me know if it works please.

**Comment by noblestreet** [comment]
Hi Petar,

Thanks for the update. I just ran the install and i was able to create an app based on your json example. Works great. I’m going to check it out.

Have a great evening/day

Met vriendelijke groet / With kind regards,

Arnaud




Mobile
Address

 <http://www.noblestreet.eu/>
 
 <https://www.facebook.com/noblestreet.eu>	 <https://twitter.com/NOBLESTREET>	 <https://plus.google.com/u/0/b/118321742550701585480/118321742550701585480/about>
+31 (0) 6 24 444 266
Veenkade 48A
2513 EH Den Haag
Disclaimer This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. Internet communications are not secure and therefore Noblestreet does not accept legal responsibility for the contents of this message. Any views or opinions presented are solely those of the author and do not necessarily represent those of Noblestreet. If you are not the intended recipient or the person responsible for delivering to the intended recipient, be advised that you have received this mail in error and that any use is strictly prohibited.

**Comment by perak** [comment]
Hi Arnaud,

I am glad that it works. Take a note that it's temporary (after next update maybe you'l have the same issue again), but I'l try to setup my toolchain to use older libc. 

Thanks for reporting this issue.

:)
