### ISSUE TITLE
Edit kitchen-site.json error

### ISSUE THREAD

**Issue by gbisheimer** [perak/kitchen-site#52]
Thank you for this great tool !! I have just found it and starting to play with it.

I was trying to import `kitchen-site.json` file into the site (to learn how it's made) but encountered 3 errors that prevented successful import.

1) misplaced comma con [line 185](https://github.com/perak/kitchen-site/blob/master/meteor-kitchen.json#L185)
2) Multiline string has to be converter to single line [here](https://github.com/perak/kitchen-site/blob/master/meteor-kitchen.json#L629-633).
3) (This line)[https://github.com/perak/kitchen-site/blob/master/meteor-kitchen.json#L654] gives me trouble. Works if changed to `"options": { "sort": { "name": 1 } }`. Also fails to save if I enter `profile.name` in the editor.

Changing these lines, I was able to import and edit the site with the GUI.

**Comment by perak** [comment]
Thanks dude! :+1:

**Comment by perak** [comment]
Just to inform you - you'l not be able to generate it using online editor - because project uses external files. GUI is also full of bugs and currently is just a playground...

**Comment by gbisheimer** [comment]
What do you meat with 'you'l not be able to generate it using online editor'? I saw the external files in the project sources and saw how they are included in the final meteor project. Also, cloned this repo and working locally on my computer.

So far, I was able to import the file and play around with it, download the JSON file, build, and run the site.

I will try to see why this is happening and fix it. The compiler works OK with this file, so should the online editor.

Also found that adding a scroll bar to the `object-tree-container` object helps a lot when editing the application. Will submit a PR for this.

**Comment by perak** [comment]
Cool! Thanks again.

**Comment by perak** [comment]
I just uploaded fixed file, and I'l close this issue.
