### ISSUE TITLE
Add roles 

### ISSUE THREAD

**Issue by AirJordan6811** [perak/kitchen-site#54]
How can I add roles later in an application? Where should I make adjustments anywhere?

**Comment by perak** [comment]
Are you talking about adding user roles in generated application (manually, without meteor kitchen) ?

Depending on what you want to do (what you want to restrict) with roles... I suggest you to generate one empty application that uses roles (create one dummy input file for meteor kitchen, add collection and set `roles_allowed_to_read`, `roles_allowed_to_update`, set "roles" array in some pages, etc.), generate application and then search generated code for "roles" - you'l see where and how it is used.
