### ISSUE TITLE
Access to userId and userFullName

### ISSUE THREAD

**Issue by AirJordan6811** [perak/kitchen-site#55]
How can I access the `this.userFullName` within the application in addition to the `this.userId`? For example, I do not want to access `this.userId`, but evaluate to` this.userFullName` in a meteor.publish routine.

**Comment by perak** [comment]
Hi,

I think your question is more general meteor programming question than "meteor kitchen" issue...

Anyway,

- First I need to ask: from which function you are trying that? `this` has different meaning depending on where it is referenced.

- Second: If you want to access current user data, you can do it with `Meteor.user()`

**Comment by AirJordan6811** [comment]
Hi @perak 
You're right , it's probably more a question of principle from meteor. 
But I try in a collection with a query does not retrieve the userId , but the user full name . Here is the example .
    Meteor.publish("supporter_list", function() {
    console.log(this.userFullName);
    if (this.userFullName=='Name, Vorname'||this.userFullName=='Name2, Vorname2')
	    return Supporters.find({ownerId:this.userId}, {});
});    
I do not know quite handy, but for the first experiments in Meteor , it is sufficient initially .

**Comment by perak** [comment]
In methods you got `this.userId` and from that you can access all user data:

```
Meteor.publish("supporter_list", function() {
var user = Metor.users.find({ _id: this.userId });
//console.log(this.userFullName);
console.log(user.userFullName);

if (user.userFullName=='Name, Vorname' || user.userFullName=='Name2, Vorname2')
    return Supporters.find({ownerId:this.userId}, {});}); 
```

**Comment by AirJordan6811** [comment]
Hi @perak Thx for your help. While it does not work yet as stated, but I'll keep trying. `userFullName` or `user.name` is `undefined` (error log console!).

**Comment by perak** [comment]
console.log(user) and see what you have there. `name` should be in `user.profile.name`

**Comment by AirJordan6811** [comment]
Yes!! That was the right way. Thx.
