### ISSUE TITLE
Improve mobile support

### ISSUE THREAD

**Issue by Tim-W** [perak/kitchen-site#57]
It would be great to see improved support for smaller devices. I'd suggest adding the META viewport tag like so:

`<meta name="viewport" content="width=device-width, initial-scale=1">`

This tag is copied straight from the Bootstrap getting started file.

**Comment by perak** [comment]
Thanks. I agree. Expect it in next update.

**Comment by AirJordan6811** [comment]
And how could I now activate a responcive desgin already?

**Comment by kadirerdogan** [comment]
Hi AirJordan6811,
While waiting for a fix, you can use below code in your json file. It'll update viewport meta tag for the client and bootstrap will work as it should be.

"client_startup_code":"var viewPortTag=document.createElement('meta'); viewPortTag.id='viewport'; viewPortTag.name = 'viewport'; viewPortTag.content = 'initial-scale=1 maximum-scale=1 user-scalable=0'; document.getElementsByTagName('head')[0].appendChild(viewPortTag);",

**Comment by perak** [comment]
Fixed. Enjoy! :)

**Comment by perak** [comment]
Just update meteor-kitchen to latest version.

P.S. I reopened this issue, please close it if it works correctly. Thanks.

**Comment by kadirerdogan** [comment]
It's not working. I have updated meteor-kitchen and it's 0.9.30 now.

**Comment by perak** [comment]
Strange, it adds `<meta name="viewport" content="width=device-width, initial-scale=1">`. Are you sure it doesn't work? (works for me).

**Comment by kadirerdogan** [comment]
is 0.9.30 the latest version? if yes it's not working for me, i dont see any meta tag at the inspector. 

I am using mac os x btw.

**Comment by perak** [comment]
Ooops, I didn't upload latest version. OK, I'l upload latest one in few hours...

**Comment by perak** [comment]
@kadirerdogan fixed. Please close this issue if it's OK now. Thanks!
