### ISSUE TITLE
getting started page disappears when you log in

### ISSUE THREAD

**Issue by javaknight** [perak/kitchen-site#60]
When you log in, the getting started page disappears. Its nice to refer to it as a reference, but you cant see it when you're logged in.

**Comment by perak** [comment]
Thanks. However, this is duplicate - already reported: https://github.com/perak/kitchen-site/issues/48

I'l fix it in next update (0.9.30).

P.S. You can expect improved and simplified GUI in next version. So, stay tuned! :)

**Comment by javaknight** [comment]
sorry. closing this
