### ISSUE TITLE
creating a page with a space causes an error.

### ISSUE THREAD

**Issue by javaknight** [perak/kitchen-site#61]
1. create a page called 'about us'
2. create a route to 'about us'
3. launch the app. you get an error:

=> Errors prevented startup:

   While building the application:
   both/router/controllers/about_ _us/about_ _us_controller.js:1:26: Unexpected
   identifier
   client/views/about_ _us/about_ _us.js:1:30: Unexpected identifier

expected result - either the user should not be able to create an "about us" page (instead, aboutus), or that it works

**Comment by perak** [comment]
You can name it `about_us`. Template will be named `AboutUs`, route name will be `about_us`, files will be named `about_us.html`, `about_us.js`

**Comment by perak** [comment]
I'l add check - names should not contains spaces.

**Comment by perak** [comment]
P.S. it's normal behavior - we cannot have spaces in javascript indentifiers. Page object has `title` property and here you can set "About Us" or whatever...

**Comment by javaknight** [comment]
got it. thanks!
