### ISSUE TITLE
meteor-kitchen error on windows

### ISSUE THREAD

**Issue by javaknight** [perak/kitchen-site#64]
Tried on both windows 7 and windows 8.

Getting an error message 

*** Meteor Kitchen v0.9.29 ***
Meteor Application Generator - www.meteorkitchen.com
Copyright (c) Petar Korponai─ç
<petar.korponaic@gmail.com>

Downloading input file...

Error downloading file.

Checking out the same file on Ubuntu works just fine.

**Comment by perak** [comment]
Well, version for windows is fresh and not tested well... It uses `curl` to download file. Try to install curl for Windows (don't know would that work, let me know please).

**Comment by javaknight** [comment]
Hello. I verified curl was in my path and installed the correct version for my machine.

C:\kitchen\bin>meteor-kitchen http://www.meteorkitchen.com/api/getapp/json/MyAppURL c:\test2

*** Meteor Kitchen v0.9.29 ***
Meteor Application Generator - www.meteorkitchen.com
Copyright (c) Petar Korponai─ç
<petar.korponaic@gmail.com>

Downloading input file...

Error downloading file.


C:\kitchen\bin>curl
curl: try 'curl --help' or 'curl --manual' for more information

C:\kitchen\bin>curl http://www.meteorkitchen.com/api/getapp/json/myAppURL

{
        "application": {
                "collections": [],
                "free_zone": {
                        "pages": [
                                {
                                        "name": "home",
                                        "title": "Hello world!",
                                        "type": "page",
                                        "class": "",
                                        "title_icon_class": "",
                                        "events_code": "",
                                        "helpers_code": "",
                                        "query": {
                                                "name": "",
                                                "collection": "",
                                                "find_one": false,
                                                "filter": {},
                                                "options": {},
                                                "params": []
                                        },
                                        "components": [],
                                        "template_rendered_code": "",
                                        "meta_description": "",
                                        "meta_title": "",
                                        "text": "",
                                        "container_class": "",
                                        "route_params": [],
                                        "close_route": "",
                                        "close_route_params": [],
                                        "back_route": "",
                                        "back_route_params": [],
                                        "roles": [],
                                        "menus": [],
                                        "pages": [],
                                        "queries": [],
                                        "force_yield_subpages": false,
                                        "zoneless": false
                                },
                                {
                                        "name": "aboutus",
                                        "template": "page_empty",
                                        "class": "",
                                        "title": "About Us",
                                        "title_icon_class": "",
                                        "events_code": "",
                                        "": "",
                                        "helpers_code": "",
                                        "template_rendered_code": "",
                                        "meta_description": "",
                                        "meta_title": "",
                                        "text": "",
                                        "container_class": "",
                                        "route_params": [],
                                        "close_route": "",
                                        "back_route": "",
                                        "roles": [],
                                        "force_yield_subpages": false,
                                        "zoneless": false,
                                        "type": "page",
                                        "query": {
                                                "name": "",
                                                "collection": "",
                                                "find_one": false,
                                                "filter": {},
                                                "options": {},
                                                "params": []
                                        },
                                        "components": [],
                                        "close_route_params": [],
                                        "back_route_params": [],
                                        "menus": [],
                                        "pages": [],
                                        "queries": []
                                }
                        ],
                        "menus": [
                                {
                                        "name": "main_menu",
                                        "class": "nav navbar-nav",
                                        "items": [
                                                {
                                                        "title": "Home page",
                                                        "route": "home",
                                                        "route_params": [],
                                                        "url": "",
                                                        "target": "",
                                                        "class": "",
                                                        "icon_class": "",
                                                        "items": []
                                                },
                                                {
                                                        "title": "About us",
                                                        "route": "aboutus",
                                                        "url": "",
                                                        "target": "",
                                                        "class": "",
                                                        "icon_class": "",
                                                        "route_params": [],
                                                        "items": []
                                                }
                                        ],
                                        "type": "menu",
                                        "dest_selector": "",
                                        "dest_position": "",
                                        "title": "",
                                        "title_icon_class": "",
                                        "events_code": "",
                                        "helpers_code": "",
                                        "query": {
                                                "name": "",
                                                "collection": "",
                                                "find_one": false,
                                                "filter": {},
                                                "options": {},
                                                "params": []
                                        },
                                        "components": [],
                                        "template_rendered_code": "",
                                        "scroll_spy_selector": ""
                                }
                        ],
                        "type": "zone",
                        "container_class": "",
                        "back_route_params": [],
                        "layout": "",
                        "navbar_class": ""
                },
                "title": "The Title",
                "meta_description": "",
                "meta_title": "",
                "template": "bootstrap",
                "theme": "bootswatch-cerulean",
                "footer_text": "",
                "roles": [],
                "default_role": "",
                "server_startup_code": "",
                "client_startup_code": "",
                "on_user_created_code": "",
                "on_user_logged_code": "",
                "server_startup_source_file": "",
                "client_startup_source_file": "",
                "on_user_created_source_file": "",
                "on_user_logged_source_file": "",
                "server_side_routes": [],
                "copy_files": [],
                "packages": {
                        "meteor": [],
                        "mrt": []
                },
                "router_config": {},
                "": ""
        }
}
C:\kitchen\bin>

**Comment by perak** [comment]
@javaknight It's fixed now. Please install latest version (I didn't changed build number, it's still 0.9.30 but uploaded just now)
