### ISSUE TITLE
Set value of params to integer

### ISSUE THREAD

**Issue by baysao** [perak/kitchen-site#66]
Dear Perak,
How can i set value of params to integer ? 
I set:
` "query": {
        "name": "admin_users",
        "collection": "users",
        "filter": {"\"profile.type\"":":kk"},
        "params": [{"name":"kk", "value": 1}]
      },
`
result generated controller files is:
`var kk = "1";
		return {
			params: this.params || {},
			admin_users: Users.find({"profile.type":kk}, {})
		};
`
Thanks for helping.

**Comment by perak** [comment]
Hi,

use `#kk` instead `:kk` as param name.

All add that into documentation.

**Comment by baysao** [comment]
Thanks Perak. I'm closes #66

**Comment by perak** [comment]
Hi @baysao 

Thanks for reporting this issue. I am currently busy with other things, but I hope I'l fix it in next 2 days.

**Comment by perak** [comment]
Update: bug is fixed, I will upload new version (0.9.33) later today.

**Comment by baysao** [comment]
Great. Thanks Perak.

**Comment by perak** [comment]
@baysao it's online now v0.9.33
