### ISSUE TITLE
Admin cannot get all rows from collection

### ISSUE THREAD

**Issue by kadirerdogan** [perak/kitchen-site#70]
I am trying to setup a collection where admin can see all the rows but users can see only their own. But unfortunately i couldnt succeed. With the below setup admin can't see other's data. If i make "read_owner_only":false then everyone sees everyhting.

                "read_owner_only": true,
                "write_owner_only": true,
                "roles_allowed_to_read":["user","admin"],
                "roles_allowed_to_update":["admin"],
                "roles_allowed_to_delete":[],

**Comment by perak** [comment]
You need to set "ownerField" to something, for example "ownerId" (see "invoices" example).

ownerField is name of collection field that sotres userId. That field will be automatically set, just name it.

**Comment by perak** [comment]
@kadirerdogan BTW, note: "roles_allowed_to_delete": [] in your example means: "All users can delete".

**Comment by kadirerdogan** [comment]
ownerField is already set to ownerId as below. I didn't paste it at first. Setting it to something else?  If i do that i think the real owner won't be able to see it. I've checked the invoices example and it is set to ownerId as well.

Btw, i dont want any rows to be deleted so i think i should set roles_allow_to_delete to a role which does not exist :)

                "owner_field": "ownerId",
                "read_owner_only": true,
                "write_owner_only": true,
                "roles_allowed_to_read":["user","admin"],
                "roles_allowed_to_update":["admin"],
                "roles_allowed_to_delete":[],

**Comment by perak** [comment]
- Ah, now I understand what's the problem! That feature doesn't exists yet. I'l try to include it in next version.

- There is (undocumented) built-in role named "nobody", so use that if you want to restrict access to all roles.

**Comment by kadirerdogan** [comment]
* Waiting for the next version then :)
* Thanks for the "nobody" hint. I was using a dummy "nodelete" role :)

**Comment by kadirerdogan** [comment]
A dirty fix until next release :)

* create a javascript file named 1.js which will override the auto generated publisher (we choose 1.js because of meteor's loading order)
```javascript
 Meteor.publish("admin_invoices", function() {
    if(!Users.isInRoles(this.userId, ["user","admin"])) return this.ready();
    if(Users.isInRoles(this.userId, ["admin"])){
            return Invoices.find({}, {});
    }
    return Invoices.find({ownerId:this.userId}, {});
 });
```
* add the copy directive to the json file. It should go to "SERVER_DIR/publish/" again because of meteor load order.

```javascript
"copy_files": [ { "source": "js/1.js", "dest": "SERVER_DIR/publish/1.js" } ]
```

Meteor will give a warning "Ignoring duplicate publish named 'admin_invoices'" but it will work.

**Comment by perak** [comment]
Thanks for dirty fix. 

I am thinking about removing "read_owner_only" and "write_owner_only" and adding special role "owner", so to allow admin and owner:

`"roles_allowed_to_read": ["admin", "owner"]`

What do you think?

**Comment by kadirerdogan** [comment]
Neat solution :)

I guess you'll do the same for delete and update too right?

**Comment by perak** [comment]
Yeah, update and delete too.

**Comment by kadirerdogan** [comment]
Perak,
How about a unix like permission system? 

"roles_allowed_to_read": ["admin","group", "owner"]

"group" is also a special role like owner.

Let's say we want to implement an invoice software for a company having different departments. Every department may have multiple accountants where each department can see/edit their own invoices and admin should be able to do everything.

To do this each record should have groupid like ownerid and users should belong to some groups. I know it's more complicated than your solution but it's more flexible.

What do you think?

**Comment by perak** [comment]
Sounds good. But don't expect it quickly. BTW, I'l upload later today new version, it supports "owner" role (and "read_owner_only", "write_owner_only" is removed).

**Comment by perak** [comment]
@kadirerdogan it's online now v0.9.33 see http://www.meteorkitchen.com/getting_started (at the bottom) for more details.

Please close this issue if everything works fine.

Thanks :)

**Comment by kadirerdogan** [comment]
It's still not working. After v0.9.33 generated code is like below. It's still filtering with ownerId. 		

My setup:
"owner_field": "ownerId",
"roles_allowed_to_read":["admin","owner"],
"roles_allowed_to_update":["admin"],
"roles_allowed_to_delete":["nobody"],

Generated code:
```javascript
Meteor.publish("invoices", function() {
    if(!Users.isInRoles(this.userId, ["admin"])) return this.ready();
    return Invoices.find({ownerId:this.userId}, {});
});
```

What it should be:
```javascript
Meteor.publish("invoices", function() {
    if(!Users.isInRoles(this.userId, ["admin"])) return this.ready();
    return Invoices.find({}, {});
});
```

**Comment by kadirerdogan** [comment]
Btw, with the new version regular users can't see their own records. So i think generated code should be like below where isInRoles check the special role "owner"

```javascript
Meteor.publish("invoices", function() {
    if(!Users.isInRoles(this.userId, ["admin","owner"])) return this.ready();
    if(!Users.isInRoles(this.userId, ["admin"]))
        return Invoices.find({ownerId:this.userId}, {}); 
    return Invoices.find({}, {});
});
```

**Comment by perak** [comment]
Ooops, yes you're right. :( I will fix it in 0.9.34, hopefully in next 24 hours...

**Comment by perak** [comment]
OK, **v0.9.34 is online.** Here is how generated code looks like now:

`"roles_allowed_to_read": ["owner"]`

```
Meteor.publish("customers", function() {
	return Customers.find({ ownerId: this.userId }, {});
});
```

`"roles_allowed_to_read": ["admin"]`

```
Meteor.publish("customers", function() {
	if(Users.isInRoles(this.userId, ["admin"])) {
		return Customers.find({}, {});
	}
	return this.ready();
});
```

`"roles_allowed_to_read": ["admin", "owner"]`

```
Meteor.publish("customers", function() {
	if(Users.isInRoles(this.userId, ["admin"])) {
		return Customers.find({}, {});
	}
	return Customers.find({ ownerId: this.userId }, {});
});
```

Also fixed `"roles_allowed_to_update"` and `"roles_allowed_to_delete"` (`userCanUpdate` and `userCanRemove` functions).

**Comment by kadirerdogan** [comment]
It seems like it's working :) I am closing this issue. Thanks
