### ISSUE TITLE
route parameters not applied

### ISSUE THREAD

**Issue by Billybobbonnet** [perak/kitchen-site#73]
Hello,

I added route parameters to an edit route from a dataview and the parameters aren't applied. The Client/views/router.js file doesn't include them. 

Here is the id of the project: 8Xq2KG5PsrCS5JLmM 

It is very close to the dataview example: 
- I have a page "group" acting as container
- I have a sub-page "all" with a dataview component "list_all"
- This dataview component include an edit route and an edit route parameter "groupId" with the value "this._id"
- I have another subpage of "group" called "edit" with a form component. This form component contains a query to the "group" collection  with a filter {"_id": ":groupId"}

I assume that I did things correctly and it might be a bug. From my understanding, the only difference in structure between the dataview example and mine is that my list_all component is in a subpage "group.all" of the "group" page

**Comment by perak** [comment]
Can you please copy & paste part with page "group" and subpages?

**Comment by perak** [comment]
Ah, OK, got it...

**Comment by Billybobbonnet** [comment]
you still need a copy/paste?

**Comment by perak** [comment]
No, I downlaoded app

**Comment by perak** [comment]
Params of a page are not automatically extracted from components/queries - you need to explicitly define them. In a properties of a "edit" page, you need to specify "route_params": ["groupId"].  
![groupid](https://cloud.githubusercontent.com/assets/5630814/7276537/83569d0e-e90a-11e4-8e9e-cf38b0a973bb.png)

**Comment by Billybobbonnet** [comment]
my bad! Sorry for raising the flag :) And thanks for your help

Problem solved

**Comment by Billybobbonnet** [comment]
Maybe it could be a feature to generate the route params field when a route and a parameter are set in a dataview.

**Comment by perak** [comment]
Great! :+1:

Please close this issue.

P.S. for things like long sentences in table row headers, such as "Les utilisateurs peuvent-ils supprimer de la corbeille les vidéos, projets et HowTOs du groupe?" - I'l add new property to field object "short_title" - and if specified, that short title will be shown in table header (and "title" in form labels).

**Comment by Billybobbonnet** [comment]
>P.S. for things like long sentences in table row headers, such as "Les utilisateurs peuvent-ils supprimer de la corbeille les vidéos, projets et HowTOs du groupe?" - I'l add new property to field object "short_title" - and if specified, that short title will be shown in table header (and "title" in form labels).

+1 :+1:

**Comment by perak** [comment]
("short_title" will be added in 0.9.35)
