### ISSUE TITLE
roles_allowed_to_update

### ISSUE THREAD

**Issue by zonelsk** [perak/kitchen-site#76]
I want to allow owner, admin, and moderator to update a collection.
When I do this:
`"roles_allowed_to_update": [
          "admin",
          "moderator"
        ]`
Admin and moderator can update,  owner can't (which is OK).
when i do this:
`"roles_allowed_to_update": [
          "owner"
        ]`
Only owner can update / edit collection (also OK).
and when i do this:
`"roles_allowed_to_update": [
          "admin",
          "moderator",
          "owner"
        ]`
generator fails with error:
`Collection "runners" references non-existing role "owner". Please add this role to application.roles array.`

Is this bug?

How can i allow, for owner, admin, and moderator to be able to update / edit or delete item form collection?

here is whole collection (without fields)
`"collections": [
      {
        "name": "runners",
        "fields": [...],
        "owner_field": "ownerId",
        "write_owner_only": false,
        "before_insert_code": "if(!doc.totalAmount) doc.totalAmount = 0;",
        "read_owner_only": false,
        "roles_allowed_to_update": [
          "admin",
          "moderator",
          "owner"
        ]
      }
    ]`

**Comment by perak** [comment]
Hi,

What is your meteor-kitchen version? (and OS?).

There was a bug with owner role, but it should be fixed in v0.9.34...

**Comment by zonelsk** [comment]
Oh, thx, I was on wrong version (v0.9.30).

After reinstall, it seams ok, but, I'll check / test it more.

I noticed that now I'm on v0.9.33, not v0.9.34.  Is this ok?
OS is ubuntu, x64

**Comment by zonelsk** [comment]
I have another question / problem.

Adding filter in dataview:
`"filter": {
                      "ownerId": "this.userId"
                    },`
Is ok parsed in publish method, but on client side is:
`return {
			params: this.params || {},
			runners_list_own: Runners.find({ownerId:"this.userId"}, {})
		};`
Shouldn't this be translated to:
`return {
			params: this.params || {},
			runners_list_own: Runners.find({ownerId:Meteor.userId()}, {})
		};`

**Comment by perak** [comment]
**About first problem:** it looks like I didn't uploaded latest linux build (0.9.34 is latest one, or maybe I just didn't change build number?). 0.9.33 have a bug when using role "owner" described here https://github.com/perak/kitchen-site/issues/70 I'l upload 0.9.35 tomorrow anyway (~24 hours from now).

**About second problem:** if you got only "owner" role in "roles_allowed_to_read" then your user will get only own documents and you don't need to filter it client side. 

If you are still in situation that you need to filter by current user, then you need to set `:userId` as parameter and set value to `Meteor.userId()`, like this:

```
"filter": { 
  "ownerId": ":userId"
},
"params": [
  { "name": "userId", "value": "Meteor.userId()" }
]
```

Now, your client will subscribe passing Meteor.userId() as argument to publish function, and publish function will look like this:
```
Meteor.publish("xxxxx", function(userId) {
	return Applications.find({ ownerId: userId }, { });
});
```
But, there is still a bug, your client will do:

`Meteor.subscribe("xxxxx", "Meteor.userId()")` instead `Meteor.subscribe("xxxxx", Meteor.userId())`, and I already fixed this - will be available in **v0.9.35**

Thanks for bug catch! :+1:

**Comment by zonelsk** [comment]
For first problem, probably just wrong build number, mine says v0.9.33 but it works.

glad to help..:) and to see new update so quickly

thx to you, for detailed response and great work. 
if i catch some time, i'll try to contribute more.

**Comment by perak** [comment]
Version v0.9.35 is up and running. You already closed this issue, but please test it and let me know (I tested it in rush).

**Comment by zonelsk** [comment]
@perak as I can see is working perfectly.
i've filtered it out as you explained earlier:
`"filter": { 
  "ownerId": ":userId"
},
"params": [
  { "name": "userId", "value": "Meteor.userId()" }
]`

on v0.9.35 is working as it should.

If i notice anything straneg I'll let you know.

**Comment by perak** [comment]
OK thanks!
