### ISSUE TITLE
Share components

### ISSUE THREAD

**Issue by baysao** [perak/kitchen-site#77]
Dear Perak,
In some case i need to reuse components of parent pages from childs pages. How can i do it ?

**Comment by perak** [comment]
Hi @baysao 

Are you using GUI or you are writing JSON manually?

- it's impossible in GUI (not yet)

- if you are writing JSON manually, and your component is defined in external files, then you can reuse it in any page.

Block like this you can put into multiple pages:
```
{
  "name": "my_component",
  "type": "custom_component",
  "custom_template": "relative_path_to_files/the_component"
  ...
}
```
you need to provide `the_component.html` and `the_component.js` at the specified path relative to input json file, with following content:

**the_component.html**
```
<template name="TEMPLATE_NAME">
  ...
</template>
```

**the_component.js**
```
Template.TEMPLATE_NAME.events({
  ...
});

Template.TEMPLATE_NAME.helpers({
  ...
});
```

Let me know it that helps (or if you got better idea...).

**Comment by baysao** [comment]
Dear Perak,
Thanks for explain. What i mean is the reusable in final meteor code generated. i think we can define an array components_share in pages and can reference element components in that array by name (static) in child pages. How about your idea ?
