### ISSUE TITLE
Not allow using the same query name of component and queries of page 

### ISSUE THREAD

**Issue by baysao** [perak/kitchen-site#94]
Dear @perak,
Generator not allow me to define the same *query name* with exactly the same options (will be build as publish in server) when:
- in query in component
  ```
"query": {
          "name": "loc_region",
          "collection": "loc_regions",
          "filter": {"_id": ":regionId"}
        }
```
- in queries array of page definition 
   ```
"queries": [
          {  "name": "loc_region",
            "collection": "loc_regions",
            "filter": {"_id": ":regionId"}
        ]
```

Message error is : Error: multiple queries named "loc_region" with different properties.

Thanks for help.

**Comment by perak** [comment]
@baysao sorry for my late answer, being in rush last days. 

I checked my code and for this I am using single (and simple) function that compares queries, don't know how is this possible. Can you please post working example (complete json) which reproduces this bug? (maybe "example-dataview", or "example-invoices" extended to reproduce this bug).

Thanks!

**Comment by perak** [comment]
@baysao Ahhh, I found where bug is: form component forces `findOne` for own query (it sets `findOne: true` automatically while reading input file). So if query with the same name exists both in form and in another component - you'l get this error.

**Comment by baysao** [comment]
thanks @perak . Try to add {"find_one":true} for query in queries to solved problem.
