### ISSUE TITLE
crud-table custom display

### ISSUE THREAD

**Issue by solace** [perak/kitchen-site#97]
Hi,

I have a `collection` which has a `field` that has `crud_fields`.  An instance of this collection is being rendered on a page in a `type: form, mode: update`.

The default settings for this renders all the `crud_fields` in a tabular format.

Using the input json, is there a way to configure which fields are displayed, or have custom fields? I know you can use `fields` to configure the top level collection `fields`, but I'm not sure how to do the same for `crud_fields`.  I've tried setting `show_in_dataview` and `show_in_read_only_form` to `false`, and manually specifying the fields in dot notation in `fields` breaks the crud table view.

If there is no mechanism available for this through the input json, I know I can do this by modifying the generated code and markup.

Thanks

**Comment by perak** [comment]
@solace  thanks for bug-catch, I'l include fix in the next version along with "U" from "CRUD". field visibility will be determined with show_in_dataview (in the same way as for dataview).

**Comment by solace** [comment]
Thanks!

**Comment by perak** [comment]
Version 0.9.39: now you can use `show_in_dataview`.

 "update" in CRUD still doesn't work - will be in next version, sorry :)

**Comment by solace** [comment]
Confirmed, `show_in_dataview` works as expected.
