### ISSUE TITLE
Problem combining examples onepage with accounts

### ISSUE THREAD

**Issue by lancefb** [perak/kitchen-site#98]
Noobie here. Loving MK, but I can't seem to combine your onepage example with a separate page with admin access. Getting a "component must have type" error.

**Comment by perak** [comment]
@lancefb the easiest way would be to copy complete "components" array from example-onepage "home" page into example-admin "home_public".

The error message you mentioned tells you that  some object insite some components array doesnt have a type property asigned. So it looks like you copied something into wrong place.

feel free to share your input json here, so I can tell you more.

**Comment by lancefb** [comment]
It worked! Thanks! Now onto more good stuff ...
