### ISSUE TITLE
action_code page option

### ISSUE THREAD

**Issue by solace** [perak/kitchen-site#99]
In the examples there's a page definition for `logout` that looks like:

`{ "name": "logout", "template": "logout", "action_code": "App.logout();" }`

I can't tell if this directive does anything (changing it doesn't seem to make a difference), but is `action_code` meant to add code to the page controller `action`?

**Comment by perak** [comment]
`action_code` is tail from past. I just didn't removed it from examples. Thanks for detailed code/docs review, you've found few interesting bugs.

**Comment by solace** [comment]
No problem. I like what you've been doing with this generator, and it seems to support more of what I want to do than any of the others I've seen so far. So thank you for putting in the work to make this. :)

**Comment by perak** [comment]
Removed `action_code` from all examples and docs (will be visible in v0.9.40)
